// Glossari CA → ES / AR / UR per a la traducció per hover.
// La web és sempre en català: aquestes traduccions apareixen com a
// tooltip en passar per sobre, perquè l'alumnat nouvingut entengui
// el català sense dependre de la llengua materna.
//
// Les entrades multi-paraula tenen prioritat (es tradueix l'expressió
// sencera quan paraula per paraula no tindria sentit).

export const GLOSSARY = [
  // ── Expressions i frases fetes ──────────────────────────
  { ca: 'es marceix', es: 'se marchita', ar: 'تذبل', ur: 'مرجھا جاتا ہے' },
  { ca: 'feina a casa', es: 'deberes', ar: 'واجب منزلي', ur: 'گھر کا کام' },
  { ca: 'data límit', es: 'fecha límite', ar: 'الموعد النهائي', ur: 'آخری تاریخ' },
  { ca: 'has faltat', es: 'has faltado a clase', ar: 'تغيّبت عن الصف', ur: 'آپ غیر حاضر تھے' },
  { ca: 'idees prèvies', es: 'ideas previas', ar: 'أفكارك المسبقة', ur: 'پہلے سے موجود خیالات' },
  { ca: 'exit tiquet', es: 'ticket de salida', ar: 'بطاقة الخروج', ur: 'ایگزٹ ٹکٹ (اختتامی سوال)' },
  { ca: 'en parelles', es: 'en parejas', ar: 'في أزواج', ur: 'جوڑوں میں' },
  { ca: 'en veu alta', es: 'en voz alta', ar: 'بصوت عالٍ', ur: 'بلند آواز میں' },
  { ca: 'a mà', es: 'a mano', ar: 'يدويًا', ur: 'ہاتھ سے' },
  { ca: 'pas a pas', es: 'paso a paso', ar: 'خطوة بخطوة', ur: 'قدم بہ قدم' },
  { ca: 'per quina raó', es: 'por qué razón', ar: 'لأي سبب', ur: 'کس وجہ سے' },
  { ca: 'posa en comú', es: 'puesta en común', ar: 'شاركها مع الصف', ur: 'سب کے ساتھ شیئر کریں' },
  { ca: 'membrana semipermeable', es: 'membrana semipermeable', ar: 'غشاء شبه نافذ', ur: 'نیم نفوذ پذیر جھلی' },
  { ca: 'respiració cel·lular', es: 'respiración celular', ar: 'التنفس الخلوي', ur: 'خلوی تنفس' },
  { ca: 'divisió cel·lular', es: 'división celular', ar: 'انقسام الخلية', ur: 'خلیے کی تقسیم' },
  { ca: 'cèl·lula mare', es: 'célula madre', ar: 'الخلية الأم', ur: 'مادر خلیہ' },
  { ca: 'cèl·lules filles', es: 'células hijas', ar: 'خلايا وليدة', ur: 'بیٹی خلیے' },
  { ca: 'cèl·lules sexuals', es: 'células sexuales', ar: 'الخلايا الجنسية', ur: 'جنسی خلیے' },
  { ca: 'freqüència cardíaca', es: 'frecuencia cardíaca', ar: 'معدل ضربات القلب', ur: 'دل کی دھڑکن کی رفتار' },
  { ca: 'doble circulació', es: 'doble circulación', ar: 'الدورة الدموية المزدوجة', ur: 'دوہری گردشِ خون' },
  { ca: 'intestí prim', es: 'intestino delgado', ar: 'الأمعاء الدقيقة', ur: 'چھوٹی آنت' },
  { ca: 'intestí gros', es: 'intestino grueso', ar: 'الأمعاء الغليظة', ur: 'بڑی آنت' },
  { ca: 'sistema digestiu', es: 'sistema digestivo', ar: 'الجهاز الهضمي', ur: 'نظامِ ہضم' },
  { ca: 'sistema circulatori', es: 'sistema circulatorio', ar: 'الجهاز الدوري', ur: 'دورانِ خون کا نظام' },
  { ca: 'sistema nerviós', es: 'sistema nervioso', ar: 'الجهاز العصبي', ur: 'اعصابی نظام' },
  { ca: 'sistema endocrí', es: 'sistema endocrino', ar: 'جهاز الغدد الصماء', ur: 'اینڈوکرائن نظام' },
  { ca: 'sistema excretor', es: 'sistema excretor', ar: 'الجهاز الإخراجي', ur: 'اخراجی نظام' },
  { ca: 'medul·la espinal', es: 'médula espinal', ar: 'النخاع الشوكي', ur: 'حرام مغز' },
  { ca: 'arc reflex', es: 'arco reflejo', ar: 'القوس الانعكاسي', ur: 'اضطراری قوس' },
  { ca: 'temps de reacció', es: 'tiempo de reacción', ar: 'زمن رد الفعل', ur: 'ردِعمل کا وقت' },
  { ca: 'àcid làctic', es: 'ácido láctico', ar: 'حمض اللاكتيك', ur: 'لیکٹک ایسڈ' },
  { ca: 'zona aeròbica', es: 'zona aeróbica', ar: 'المنطقة الهوائية', ur: 'ایروبک زون' },
  { ca: 'zona anaeròbica', es: 'zona anaeróbica', ar: 'المنطقة اللاهوائية', ur: 'اینیروبک زون' },
  { ca: 'sèrum fisiològic', es: 'suero fisiológico', ar: 'محلول ملحي طبي', ur: 'فزیولوجیکل سیرم' },
  { ca: 'aigua pura', es: 'agua pura', ar: 'ماء نقي', ur: 'خالص پانی' },
  { ca: 'sense closca', es: 'sin cáscara', ar: 'بدون قشرة', ur: 'بغیر چھلکے کے' },
  { ca: 'bolo alimentici', es: 'bolo alimenticio', ar: 'البلعة الغذائية', ur: 'نوالہ (بولس)' },
  { ca: 'vena porta', es: 'vena porta', ar: 'الوريد البابي', ur: 'پورٹل ورید' },
  { ca: 'hidrats de carboni', es: 'hidratos de carbono', ar: 'الكربوهيدرات', ur: 'کاربوہائیڈریٹس' },
  { ca: 'prova escrita', es: 'examen escrito', ar: 'اختبار كتابي', ur: 'تحریری امتحان' },
  { ca: 'full de treball', es: 'hoja de trabajo', ar: 'ورقة العمل', ur: 'ورک شیٹ' },

  // ── La cèl·lula (SA1) ───────────────────────────────────
  { ca: 'cèl·lula', es: 'célula', ar: 'خلية', ur: 'خلیہ' },
  { ca: 'cèl·lules', es: 'células', ar: 'خلايا', ur: 'خلیے' },
  { ca: 'membrana', es: 'membrana', ar: 'غشاء', ur: 'جھلی' },
  { ca: 'nucli', es: 'núcleo', ar: 'نواة', ur: 'مرکزہ' },
  { ca: 'mitocondri', es: 'mitocondria', ar: 'ميتوكوندريون', ur: 'مائٹوکونڈریا' },
  { ca: 'mitocondris', es: 'mitocondrias', ar: 'ميتوكوندريا', ur: 'مائٹوکونڈریا' },
  { ca: 'orgànul', es: 'orgánulo', ar: 'عضيّة', ur: 'عضوہ' },
  { ca: 'orgànuls', es: 'orgánulos', ar: 'عضيّات', ur: 'عضوے' },
  { ca: 'citoplasma', es: 'citoplasma', ar: 'سيتوبلازم', ur: 'سائٹوپلازم' },
  { ca: 'ADN', es: 'ADN', ar: 'الحمض النووي DNA', ur: 'ڈی این اے' },
  // «gens» és alhora el plural de gen i l'adverbi «gens ni mica».
  { ca: 'gens', es: 'genes; y en «no… gens» = nada en absoluto', ar: 'جينات؛ وفي «no… gens» تعني إطلاقًا (ولا قليلًا)', ur: 'جینز؛ اور «no… gens» یعنی بالکل نہیں' },
  { ca: 'proteïnes', es: 'proteínas', ar: 'بروتينات', ur: 'پروٹین' },
  { ca: 'teixit', es: 'tejido', ar: 'نسيج', ur: 'بافت' },
  { ca: 'teixits', es: 'tejidos', ar: 'أنسجة', ur: 'بافتیں' },
  { ca: 'òrgan', es: 'órgano', ar: 'عضو', ur: 'عضو' },
  { ca: 'òrgans', es: 'órganos', ar: 'أعضاء', ur: 'اعضاء' },
  { ca: 'organisme', es: 'organismo', ar: 'كائن حي', ur: 'جاندار' },
  { ca: 'procariota', es: 'procariota', ar: 'بدائية النواة', ur: 'پروکیریوٹ' },
  { ca: 'eucariota', es: 'eucariota', ar: 'حقيقية النواة', ur: 'یوکیریوٹ' },
  { ca: 'autòtrofs', es: 'autótrofos', ar: 'ذاتية التغذية', ur: 'خود خوراک ساز' },
  { ca: 'heteròtrofs', es: 'heterótrofos', ar: 'غيرية التغذية', ur: 'غیر خود خوراک ساز' },
  { ca: 'fotosíntesi', es: 'fotosíntesis', ar: 'التمثيل الضوئي', ur: 'ضیائی تالیف' },
  { ca: 'energia', es: 'energía', ar: 'طاقة', ur: 'توانائی' },
  { ca: 'glucosa', es: 'glucosa', ar: 'جلوكوز', ur: 'گلوکوز' },
  { ca: 'oxigen', es: 'oxígeno', ar: 'أكسجين', ur: 'آکسیجن' },
  { ca: 'aliment', es: 'alimento', ar: 'غذاء', ur: 'خوراک' },
  { ca: 'aliments', es: 'alimentos', ar: 'أغذية', ur: 'غذائیں' },
  { ca: 'menjar', es: 'comer / comida', ar: 'الأكل / الطعام', ur: 'کھانا' },
  { ca: 'respirar', es: 'respirar', ar: 'التنفس', ur: 'سانس لینا' },
  { ca: 'osmosi', es: 'ósmosis', ar: 'التناضح (الأسموزية)', ur: 'اوسموسس' },
  { ca: 'semipermeable', es: 'semipermeable', ar: 'شبه نافذ', ur: 'نیم نفوذ پذیر' },
  { ca: 'concentració', es: 'concentración', ar: 'تركيز', ur: 'ارتکاز' },
  { ca: 'solut', es: 'soluto', ar: 'مادة مذابة', ur: 'محلول مادہ' },
  { ca: 'isotònic', es: 'isotónico', ar: 'متساوي التوتر', ur: 'آئسوٹونک' },
  { ca: 'hipertònic', es: 'hipertónico', ar: 'مفرط التوتر', ur: 'ہائپرٹونک' },
  { ca: "s'infla", es: 'se hincha', ar: 'ينتفخ', ur: 'پھول جاتا ہے' },
  { ca: "s'encongeix", es: 'se encoge', ar: 'ينكمش', ur: 'سکڑ جاتا ہے' },
  { ca: 'ou', es: 'huevo', ar: 'بيضة', ur: 'انڈا' },
  { ca: 'vinagre', es: 'vinagre', ar: 'خل', ur: 'سرکہ' },
  { ca: 'closca', es: 'cáscara', ar: 'قشرة', ur: 'چھلکا' },
  { ca: 'sucre', es: 'azúcar', ar: 'سكر', ur: 'چینی' },
  { ca: 'got', es: 'vaso', ar: 'كوب', ur: 'گلاس' },
  { ca: 'gots', es: 'vasos', ar: 'أكواب', ur: 'گلاس' },
  { ca: 'adob', es: 'abono / fertilizante', ar: 'سماد', ur: 'کھاد' },
  { ca: 'mitosi', es: 'mitosis', ar: 'الانقسام المتساوي', ur: 'مائٹوسس' },
  { ca: 'meiosi', es: 'meiosis', ar: 'الانقسام المنصّف', ur: 'مییوسس' },
  { ca: 'idèntiques', es: 'idénticas', ar: 'متطابقة', ur: 'بالکل ایک جیسے' },
  { ca: 'meitat', es: 'mitad', ar: 'نصف', ur: 'آدھا' },
  { ca: 'espermatozoide', es: 'espermatozoide', ar: 'حيوان منوي', ur: 'سپرم' },
  { ca: 'òvul', es: 'óvulo', ar: 'بويضة', ur: 'بیضہ' },
  { ca: 'càncer', es: 'cáncer', ar: 'سرطان', ur: 'کینسر' },
  { ca: 'tumors', es: 'tumores', ar: 'أورام', ur: 'رسولیاں' },
  { ca: 'diferenciació', es: 'diferenciación', ar: 'التمايز', ur: 'تفریق' },
  { ca: 'ferida', es: 'herida', ar: 'جرح', ur: 'زخم' },
  { ca: 'ferides', es: 'heridas', ar: 'جروح', ur: 'زخم' },
  { ca: 'curar', es: 'curar', ar: 'شفاء', ur: 'ٹھیک کرنا' },
  { ca: 'créixer', es: 'crecer', ar: 'النمو', ur: 'بڑھنا' },
  { ca: 'reparar', es: 'reparar', ar: 'إصلاح', ur: 'مرمت کرنا' },
  { ca: 'substituir', es: 'sustituir', ar: 'استبدال', ur: 'بدلنا' },
  { ca: 'neurona', es: 'neurona', ar: 'خلية عصبية', ur: 'نیوران' },
  { ca: 'neurones', es: 'neuronas', ar: 'خلايا عصبية', ur: 'نیورانز' },
  { ca: 'pell', es: 'piel', ar: 'جلد', ur: 'جلد' },
  { ca: 'múscul', es: 'músculo', ar: 'عضلة', ur: 'پٹھا' },
  { ca: 'músculs', es: 'músculos', ar: 'عضلات', ur: 'پٹھے' },
  { ca: 'muscular', es: 'muscular', ar: 'عضلي', ur: 'عضلاتی' },

  // ── El cos humà (SA2) ───────────────────────────────────
  { ca: 'nutrients', es: 'nutrientes', ar: 'مغذيات', ur: 'غذائی اجزاء' },
  { ca: 'nutrient', es: 'nutriente', ar: 'مادة مغذية', ur: 'غذائی جز' },
  { ca: 'midó', es: 'almidón', ar: 'نشا', ur: 'نشاستہ' },
  { ca: 'greixos', es: 'grasas', ar: 'دهون', ur: 'چکنائیاں' },
  { ca: 'fosfolípids', es: 'fosfolípidos', ar: 'فوسفوليبيدات', ur: 'فاسفولپڈز' },
  { ca: 'aminoàcids', es: 'aminoácidos', ar: 'أحماض أمينية', ur: 'امینو ایسڈز' },
  { ca: 'vitamines', es: 'vitaminas', ar: 'فيتامينات', ur: 'وٹامنز' },
  { ca: 'ferro', es: 'hierro', ar: 'حديد', ur: 'فولاد (آئرن)' },
  { ca: 'hemoglobina', es: 'hemoglobina', ar: 'هيموجلوبين', ur: 'ہیموگلوبن' },
  { ca: 'sang', es: 'sangre', ar: 'دم', ur: 'خون' },
  { ca: 'plasma', es: 'plasma', ar: 'بلازما', ur: 'پلازما' },
  { ca: 'eritròcits', es: 'glóbulos rojos', ar: 'كريات الدم الحمراء', ur: 'سرخ خونی خلیے' },
  { ca: 'leucòcits', es: 'glóbulos blancos', ar: 'كريات الدم البيضاء', ur: 'سفید خونی خلیے' },
  { ca: 'plaquetes', es: 'plaquetas', ar: 'صفائح دموية', ur: 'پلیٹلیٹس' },
  { ca: 'anèmia', es: 'anemia', ar: 'فقر الدم', ur: 'خون کی کمی' },
  { ca: 'analítica', es: 'análisis de sangre', ar: 'تحليل الدم', ur: 'خون کا ٹیسٹ' },
  { ca: 'hematòcrit', es: 'hematocrito', ar: 'الهيماتوكريت', ur: 'ہیماٹوکرٹ' },
  { ca: 'digestió', es: 'digestión', ar: 'الهضم', ur: 'ہضم' },
  { ca: 'estómac', es: 'estómago', ar: 'معدة', ur: 'معدہ' },
  { ca: 'esòfag', es: 'esófago', ar: 'مريء', ur: 'غذائی نالی' },
  { ca: 'pàncrees', es: 'páncreas', ar: 'بنكرياس', ur: 'لبلبہ' },
  { ca: 'bilis', es: 'bilis', ar: 'الصفراء', ur: 'صفرا' },
  { ca: 'enzims', es: 'enzimas', ar: 'إنزيمات', ur: 'خامرے (انزائمز)' },
  { ca: 'àcid', es: 'ácido', ar: 'حمض', ur: 'تیزاب' },
  { ca: 'bicarbonat', es: 'bicarbonato', ar: 'بيكربونات', ur: 'بائی کاربونیٹ' },
  { ca: 'quimo', es: 'quimo', ar: 'الكيموس', ur: 'کائم' },
  { ca: 'peristaltisme', es: 'peristaltismo', ar: 'الحركة الدودية', ur: 'پیرسٹالسس' },
  { ca: 'vellositats', es: 'vellosidades', ar: 'زغابات معوية', ur: 'آنتوں کے ریشے' },
  { ca: 'absorció', es: 'absorción', ar: 'امتصاص', ur: 'جذب' },
  { ca: 'microbiota', es: 'microbiota', ar: 'الميكروبيوم المعوي', ur: 'مائکروبایوٹا' },
  { ca: 'bacteris', es: 'bacterias', ar: 'بكتيريا', ur: 'بیکٹیریا' },
  { ca: 'cor', es: 'corazón', ar: 'قلب', ur: 'دل' },
  { ca: 'aurícules', es: 'aurículas', ar: 'أذينان', ur: 'ایٹریا (بالائی خانے)' },
  { ca: 'ventricles', es: 'ventrículos', ar: 'بطينان', ur: 'وینٹریکلز (زیریں خانے)' },
  { ca: 'ventricle', es: 'ventrículo', ar: 'بطين', ur: 'وینٹریکل' },
  { ca: 'vàlvules', es: 'válvulas', ar: 'صمامات', ur: 'والوز' },
  { ca: 'tabi', es: 'tabique', ar: 'حاجز', ur: 'پردہ (سیپٹم)' },
  { ca: 'artèria', es: 'arteria', ar: 'شريان', ur: 'شریان' },
  { ca: 'artèries', es: 'arterias', ar: 'شرايين', ur: 'شریانیں' },
  { ca: 'vena', es: 'vena', ar: 'وريد', ur: 'ورید' },
  { ca: 'venes', es: 'venas', ar: 'أوردة', ur: 'وریدیں' },
  { ca: 'capil·lars', es: 'capilares', ar: 'شعيرات دموية', ur: 'کیپلریز' },
  { ca: 'aorta', es: 'aorta', ar: 'الشريان الأبهر', ur: 'شہ رگ' },
  { ca: 'coronàries', es: 'coronarias', ar: 'الشرايين التاجية', ur: 'کورونری شریانیں' },
  { ca: 'miocardi', es: 'miocardio', ar: 'عضلة القلب', ur: 'دل کا پٹھا' },
  { ca: 'infart', es: 'infarto', ar: 'احتشاء (نوبة قلبية)', ur: 'ہارٹ اٹیک' },
  { ca: 'batec', es: 'latido', ar: 'نبضة', ur: 'دھڑکن' },
  { ca: 'batecs', es: 'latidos', ar: 'نبضات', ur: 'دھڑکنیں' },
  { ca: 'pols', es: 'pulso · polvo · polos', ar: 'النبض · الغبار · الأقطاب', ur: 'نبض · گرد · قطبین' },
  { ca: 'canell', es: 'muñeca', ar: 'معصم', ur: 'کلائی' },
  { ca: 'pulmons', es: 'pulmones', ar: 'رئتان', ur: 'پھیپھڑے' },
  { ca: 'alvèols', es: 'alvéolos', ar: 'حويصلات هوائية', ur: 'ہوائی خانے (الویولائی)' },
  { ca: 'alvèol', es: 'alvéolo', ar: 'حويصلة هوائية', ur: 'ہوائی خانہ' },
  { ca: 'hormona', es: 'hormona', ar: 'هرمون', ur: 'ہارمون' },
  { ca: 'hormones', es: 'hormonas', ar: 'هرمونات', ur: 'ہارمونز' },
  { ca: 'adrenalina', es: 'adrenalina', ar: 'أدرينالين', ur: 'ایڈرینالین' },
  { ca: 'insulina', es: 'insulina', ar: 'إنسولين', ur: 'انسولین' },
  { ca: 'glàndula', es: 'glándula', ar: 'غدة', ur: 'غدود' },
  { ca: 'ronyó', es: 'riñón', ar: 'كلية', ur: 'گردہ' },
  { ca: 'ronyons', es: 'riñones', ar: 'كليتان', ur: 'گردے' },
  { ca: 'orina', es: 'orina', ar: 'بول', ur: 'پیشاب' },
  { ca: 'urea', es: 'urea', ar: 'يوريا', ur: 'یوریا' },
  { ca: 'homeòstasi', es: 'homeostasis', ar: 'الاتزان الداخلي', ur: 'ہومیوسٹیسس' },
  { ca: 'nervi', es: 'nervio', ar: 'عصب', ur: 'عصب' },
  { ca: 'nervis', es: 'nervios', ar: 'أعصاب', ur: 'اعصاب' },
  { ca: 'reflex', es: 'reflejo', ar: 'منعكس', ur: 'اضطراری حرکت' },
  { ca: 'cervell', es: 'cerebro', ar: 'دماغ', ur: 'دماغ' },
  { ca: 'fatiga', es: 'fatiga / cansancio', ar: 'تعب', ur: 'تھکاوٹ' },
  { ca: 'esforç', es: 'esfuerzo', ar: 'جهد', ur: 'محنت / زور' },
  { ca: 'exercici', es: 'ejercicio', ar: 'تمرين', ur: 'ورزش' },
  { ca: 'repòs', es: 'reposo', ar: 'راحة', ur: 'آرام' },
  { ca: 'corredor', es: 'corredor', ar: 'عدّاء', ur: 'دوڑنے والا' },
  { ca: 'corredora', es: 'corredora', ar: 'عدّاءة', ur: 'دوڑنے والی' },
  { ca: 'cursa', es: 'carrera', ar: 'سباق', ur: 'دوڑ' },
  { ca: 'residus', es: 'residuos', ar: 'فضلات', ur: 'فضلہ' },

  // ── Instruccions i vocabulari escolar ───────────────────
  { ca: 'observa', es: 'observa', ar: 'لاحظ', ur: 'مشاہدہ کریں' },
  { ca: 'mesura', es: 'mide', ar: 'قِس', ur: 'ناپیں' },
  { ca: 'pesa', es: 'pesa', ar: 'زِن', ur: 'وزن کریں' },
  { ca: 'anota', es: 'anota', ar: 'دوّن', ur: 'لکھ لیں' },
  { ca: 'registra', es: 'registra', ar: 'سجّل', ur: 'درج کریں' },
  { ca: 'dibuixa', es: 'dibuja', ar: 'ارسم', ur: 'بنائیں (ڈرائنگ)' },
  { ca: 'escriu', es: 'escribe', ar: 'اكتب', ur: 'لکھیں' },
  { ca: 'llegeix', es: 'lee', ar: 'اقرأ', ur: 'پڑھیں' },
  { ca: 'explica', es: 'explica', ar: 'اشرح', ur: 'وضاحت کریں' },
  { ca: 'justifica', es: 'justifica', ar: 'برّر', ur: 'دلیل دیں' },
  { ca: 'compara', es: 'compara', ar: 'قارن', ur: 'موازنہ کریں' },
  { ca: 'ordena', es: 'ordena', ar: 'رتّب', ur: 'ترتیب دیں' },
  { ca: 'classifica', es: 'clasifica', ar: 'صنّف', ur: 'درجہ بندی کریں' },
  { ca: 'omple', es: 'rellena', ar: 'املأ', ur: 'بھریں' },
  { ca: 'descarrega', es: 'descarga', ar: 'حمّل', ur: 'ڈاؤن لوڈ کریں' },
  { ca: 'comprova', es: 'comprueba', ar: 'تحقق', ur: 'جانچیں' },
  { ca: 'tria', es: 'elige', ar: 'اختر', ur: 'منتخب کریں' },
  { ca: 'marca', es: 'marca', ar: 'علّم', ur: 'نشان لگائیں' },
  { ca: 'predicció', es: 'predicción', ar: 'توقع', ur: 'پیشگوئی' },
  { ca: 'prediccions', es: 'predicciones', ar: 'توقعات', ur: 'پیشگوئیاں' },
  { ca: 'hipòtesi', es: 'hipótesis', ar: 'فرضية', ur: 'مفروضہ' },
  { ca: 'hipòtesis', es: 'hipótesis', ar: 'فرضيات', ur: 'مفروضے' },
  { ca: 'resultats', es: 'resultados', ar: 'نتائج', ur: 'نتائج' },
  { ca: 'taula', es: 'tabla', ar: 'جدول', ur: 'جدول' },
  { ca: 'gràfica', es: 'gráfica', ar: 'رسم بياني', ur: 'گراف' },
  { ca: 'gràfiques', es: 'gráficas', ar: 'رسوم بيانية', ur: 'گراف' },
  { ca: 'fitxa', es: 'ficha', ar: 'ورقة العمل', ur: 'ورک شیٹ' },
  { ca: 'full', es: 'hoja', ar: 'ورقة', ur: 'کاغذ / شیٹ' },
  { ca: 'apartat', es: 'apartado', ar: 'قسم', ur: 'حصہ' },
  { ca: 'apartats', es: 'apartados', ar: 'أقسام', ur: 'حصے' },
  { ca: 'pista', es: 'pista', ar: 'تلميح', ur: 'اشارہ' },
  { ca: 'pistes', es: 'pistas', ar: 'تلميحات', ur: 'اشارے' },
  { ca: 'pregunta', es: 'pregunta', ar: 'سؤال', ur: 'سوال' },
  { ca: 'preguntes', es: 'preguntas', ar: 'أسئلة', ur: 'سوالات' },
  { ca: 'resposta', es: 'respuesta', ar: 'إجابة', ur: 'جواب' },
  { ca: 'respostes', es: 'respuestas', ar: 'إجابات', ur: 'جوابات' },
  { ca: 'deures', es: 'deberes', ar: 'واجبات', ur: 'ہوم ورک' },
  { ca: 'termini', es: 'plazo', ar: 'مهلة', ur: 'مدت' },
  { ca: 'entrega', es: 'entrega', ar: 'تسليم', ur: 'جمع کرانا' },
  { ca: 'entregues', es: 'entregas', ar: 'تسليمات', ur: 'جمع کرانے کی چیزیں' },
  { ca: 'sessió', es: 'sesión', ar: 'حصة', ur: 'سیشن' },
  { ca: 'sessions', es: 'sesiones', ar: 'حصص', ur: 'سیشنز' },
  // A 4t «prova» gairebé sempre vol dir EVIDÈNCIA, no examen (SA1-SA7).
  { ca: 'prova', es: 'prueba = evidencia (casi siempre); también «prova» = ensaya, pone a prueba; y en clase, un examen', ar: 'دليل / برهان (غالبًا)؛ وكفعل: يختبر، يُجرّب؛ وفي الصف قد تعني اختبارًا', ur: 'ثبوت / شہادت (عموماً)؛ بطورِ فعل: آزماتا ہے؛ کلاس میں کبھی امتحان' },
  { ca: 'provar', es: 'probar, ensayar (poner a prueba)', ar: 'يختبر، يُجرّب', ur: 'آزمانا، جانچنا' },
  { ca: 'rúbrica', es: 'rúbrica', ar: 'سلم التقييم', ur: 'روبرک (جانچ پیمانہ)' },
  { ca: 'pòster', es: 'póster', ar: 'ملصق', ur: 'پوسٹر' },
  { ca: 'grup', es: 'grupo', ar: 'مجموعة', ur: 'گروپ' },
  { ca: 'materials', es: 'materiales', ar: 'أدوات', ur: 'سامان' },
  { ca: 'durada', es: 'duración', ar: 'مدة', ur: 'دورانیہ' },
  { ca: 'objectius', es: 'objetivos', ar: 'أهداف', ur: 'مقاصد' },
  { ca: 'competències', es: 'competencias', ar: 'كفاءات', ur: 'صلاحیتیں' },
  { ca: 'recuperació', es: 'recuperación', ar: 'استدراك / تعويض', ur: 'تلافی' },
  { ca: 'autoavaluació', es: 'autoevaluación', ar: 'تقييم ذاتي', ur: 'خود تشخیص' },
  { ca: 'reflexió', es: 'reflexión', ar: 'تأمل', ur: 'غور و فکر' },
  { ca: 'repte', es: 'reto', ar: 'تحدٍّ', ur: 'چیلنج' },
  { ca: 'enigma', es: 'enigma', ar: 'لغز', ur: 'پہیلی' },
  { ca: 'enigmes', es: 'enigmas', ar: 'ألغاز', ur: 'پہیلیاں' },
  { ca: 'maqueta', es: 'maqueta', ar: 'مجسّم', ur: 'ماڈل' },
  { ca: 'dies', es: 'días', ar: 'أيام', ur: 'دن' },
  { ca: 'setmanes', es: 'semanas', ar: 'أسابيع', ur: 'ہفتے' },
  { ca: 'queden', es: 'quedan / faltan', ar: 'تبقّى', ur: 'باقی ہیں' },

  // ══════════════════════════════════════════════════════════
  // VOCABULARI DE 4t ESO (afegit 2026-08-21)
  // El bloc de dalt venia del projecte de 3r ESO i no cobria
  // res de genètica, evolució, geologia ni origen de la vida.
  // ══════════════════════════════════════════════════════════
  // ── 4t ESO · SA1 · Ciència i pseudociència
  { ca: 'ciència', es: 'ciencia', ar: 'العِلم', ur: 'سائنس' },
  { ca: 'pseudociència', es: 'pseudociencia', ar: 'العِلم الزائف', ur: 'جعلی سائنس' },
  { ca: 'científic', es: 'científico', ar: 'عِلمي', ur: 'سائنسی' },
  { ca: 'científica', es: 'científica', ar: 'عِلمية', ur: 'سائنسی' },
  // `inferència` i `conclusió` tenien la MATEIXA paraula àrab, i SA3·S2 demana
  // literalment distingir «què he observat» de «què infereixo». Diferenciades.
  { ca: 'inferència', es: 'inferencia: lo que deduces de lo que ves (puede fallar)', ar: 'استنتاج مؤقّت مما تراه (قد يكون خطأ)', ur: 'جو دیکھا اُس سے اخذ کیا (غلط بھی ہو سکتا ہے)' },
  { ca: 'infereixo', es: 'infiero (deduzco, no lo veo directamente)', ar: 'أستنتج (لا أراه مباشرة)', ur: 'میں اخذ کرتا ہوں (براہِ راست نہیں دیکھتا)' },
  { ca: 'observo', es: 'observo (lo veo directamente)', ar: 'أُلاحظ (أراه مباشرة)', ur: 'میں دیکھتا ہوں (براہِ راست)' },
  { ca: 'conclusió', es: 'conclusión (lo que deduces de los datos)', ar: 'استنتاج نهائي مبني على الأدلة', ur: 'شواہد سے اخذ کردہ نتیجہ' },
  { ca: 'argument', es: 'argumento', ar: 'حُجّة', ur: 'دلیل' },
  { ca: 'autoritat', es: 'autoridad', ar: 'السلطة (من يقولها)', ur: 'اتھارٹی (کہنے والا)' },
  // A SA1 «garantia» NO és la d'un producte: és allò en què recolzes una
  // afirmació (dades, models, hàbits, autoritat, identitat/valors).
  { ca: 'garantia', es: 'garantía: en qué apoyas lo que afirmas', ar: 'المُسوِّغ: الأساس الذي تبني عليه ادعاءك', ur: 'دلیل کی بنیاد: آپ بات کس چیز پر رکھتے ہیں' },
  { ca: 'hàbit', es: 'hábito / costumbre', ar: 'عادة: «هكذا كان دائمًا»', ur: 'عادت / روایت' },
  { ca: 'identitat', es: 'identidad', ar: 'الهوية: من أنا وبماذا أؤمن', ur: 'شناخت: میں کون ہوں' },
  { ca: 'valors', es: 'valores', ar: 'القيم', ur: 'اقدار' },
  { ca: 'biaix', es: 'sesgo', ar: 'تحيّز: ميل يجعلك ترى ما تريد', ur: 'تعصب / جھکاؤ' },
  { ca: 'cert', es: 'cierto / verdadero', ar: 'أكيد / صحيح', ur: 'یقینی / سچ' },
  { ca: 'certa', es: 'cierta / verdadera', ar: 'أكيدة / صحيحة', ur: 'یقینی / سچی' },
  { ca: 'segur', es: 'seguro', ar: 'متأكد', ur: 'پُریقین' },
  { ca: 'segura', es: 'segura', ar: 'متأكدة', ur: 'پُریقین' },
  { ca: 'afirmació', es: 'afirmación', ar: 'عبارة / ادعاء', ur: 'دعویٰ / بیان' },
  { ca: 'retalla', es: 'recorta', ar: 'قُصّ بالمقص', ur: 'کاٹیں' },
  { ca: 'retallables', es: 'recortables', ar: 'أوراق للقصّ', ur: 'کاٹنے والے کارڈ' },
  { ca: 'enganxa', es: 'pega', ar: 'الصق', ur: 'چپکائیں' },
  { ca: 'consens', es: 'consenso / acuerdo del grupo', ar: 'توافق المجموعة', ur: 'گروپ کا اتفاق' },
  { ca: 'mesures', es: 'medidas: números que has medido · o acciones que se toman', ar: 'قياسات (أرقام قِسْتَها) · أو إجراءات تُتَّخذ', ur: 'پیمائشیں (ناپے ہوئے اعداد) · یا اقدامات' },
  { ca: 'mesures de prevenció', es: 'medidas de prevención (acciones para evitar el daño)', ar: 'إجراءات وقائية (لتفادي الضرر)', ur: 'حفاظتی اقدامات' },
  { ca: 'a mesura que', es: 'a medida que, conforme', ar: 'كلّما، بقدر ما', ur: 'جوں جوں' },
  { ca: 'marques', es: 'marcas comerciales', ar: 'علامات تجارية', ur: 'برانڈز' },
  { ca: 'plaça', es: 'plaza', ar: 'ساحة', ur: 'چوک' },
  { ca: 'verificar', es: 'verificar', ar: 'التحقّق', ur: 'تصدیق کرنا' },
  { ca: 'exageració', es: 'exageración', ar: 'مبالغة', ur: 'مبالغہ' },
  { ca: 'opinió', es: 'opinión', ar: 'رأي', ur: 'رائے' },
  { ca: 'criteri', es: 'criterio', ar: 'معيار', ur: 'معیار' },
  { ca: 'mètode', es: 'método', ar: 'منهج / طريقة', ur: 'طریقہ کار' },
  { ca: 'rigor', es: 'rigor', ar: 'دقّة صارمة', ur: 'سختی و احتیاط' },
  { ca: 'fiable', es: 'fiable', ar: 'موثوق', ur: 'قابلِ اعتماد' },
  { ca: 'certesa', es: 'certeza', ar: 'درجة اليقين', ur: 'یقین کا درجہ' },
  { ca: 'contrastable', es: 'contrastable', ar: 'قابل للاختبار', ur: 'قابلِ جانچ' },
  { ca: 'indagació', es: 'indagación', ar: 'الاستقصاء', ur: 'تحقیق و تفتیش' },
  { ca: 'bioètica', es: 'bioética', ar: 'أخلاقيات علم الأحياء', ur: 'حیاتیاتی اخلاقیات' },
  { ca: 'ètica', es: 'ética', ar: 'الأخلاق', ur: 'اخلاقیات' },
  { ca: 'coavaluació', es: 'coevaluación', ar: 'التقييم بين الأقران', ur: 'ہم جماعت تشخیص' },
  { ca: 'congrés', es: 'congreso', ar: 'مؤتمر', ur: 'کانفرنس' },
  { ca: 'tendència', es: 'tendencia', ar: 'اتجاه عام', ur: 'عمومی رجحان' },
  { ca: 'percentatge', es: 'porcentaje', ar: 'نسبة مئوية', ur: 'فیصد' },
  { ca: 'probable', es: 'probable (más que posible)', ar: 'مُرجَّح (أكثر من مجرد ممكن)', ur: 'غالب امکان / زیادہ امکان والا' },
  { ca: 'atzar', es: 'azar', ar: 'الصدفة (بلا سبب ولا قدَر)', ur: 'اتفاقیہ / بے ترتیبی (کوئی وجہ یا قسمت نہیں)' },
  { ca: 'moneda', es: 'moneda', ar: 'قطعة نقدية', ur: 'سکہ' },
  { ca: 'perfil epistèmic', es: 'tu perfil: cómo decides qué te crees', ar: 'طريقتك في تحديد ما تصدّقه', ur: 'آپ کیسے طے کرتے ہیں کہ کیا ماننا ہے' },
  { ca: 'hipòtesi contrastable', es: 'hipótesis contrastable', ar: 'فرضية قابلة للاختبار', ur: 'قابلِ جانچ مفروضہ' },
  { ca: 'qüestió sociocientífica', es: 'cuestión sociocientífica', ar: 'قضية علمية اجتماعية', ur: 'سماجی سائنسی مسئلہ' },
  { ca: 'pòster científic', es: 'póster científico', ar: 'ملصق علمي', ur: 'سائنسی پوسٹر' },
  // Ampliats el 24/08: dir només «control negativo» no ajuda ningú que
  // encara no sàpiga què és un control. La glossa ha d'explicar-ho.
  { ca: 'control negatiu', es: 'control negativo (sin el factor; no debería pasar nada)', ar: 'ضابط سالب (بدون العامل؛ يُتوقّع ألّا يحدث شيء)', ur: 'منفی کنٹرول (عامل کے بغیر؛ کچھ نہیں ہونا چاہیے)' },
  { ca: 'control positiu', es: 'control positivo (sabemos de antemano que sí funciona)', ar: 'ضابط موجب (نعرف مسبقًا أنه ينجح)', ur: 'مثبت کنٹرول (جس کا کام کرنا پہلے سے معلوم ہے)' },
  { ca: 'a cegues', es: 'a ciegas (sin saber qué muestra es cuál)', ar: 'بشكل أعمى (دون معرفة أيّ عيّنة هي أيّ)', ur: 'بغیر جانے کہ کون سا نمونہ کون سا ہے' },
  // ── 4t ESO · SA2 · La cèl·lula
  { ca: 'interfase', es: 'interfase', ar: 'الطور البيني', ur: 'انٹرفیز' },
  { ca: 'profase', es: 'profase', ar: 'الطور التمهيدي', ur: 'پروفیز' },
  { ca: 'metafase', es: 'metafase', ar: 'الطور الاستوائي', ur: 'میٹا فیز' },
  { ca: 'anafase', es: 'anafase', ar: 'الطور الانفصالي', ur: 'اینا فیز' },
  { ca: 'telofase', es: 'telofase', ar: 'الطور النهائي', ur: 'ٹیلو فیز' },
  { ca: 'cicle cel·lular', es: 'ciclo celular', ar: 'دورة الخلية', ur: 'خلوی چکر' },
  { ca: 'índex mitòtic', es: 'índice mitótico', ar: 'المؤشر الانقسامي', ur: 'مائٹوٹک انڈیکس' },
  { ca: 'tumor', es: 'tumor', ar: 'ورم', ur: 'رسولی' },
  { ca: 'tumoral', es: 'tumoral', ar: 'ورمي', ur: 'رسولی سے متعلق' },
  { ca: 'quimioteràpia', es: 'quimioterapia', ar: 'العلاج الكيميائي', ur: 'کیمو تھراپی' },
  { ca: 'gàmeta', es: 'gameto', ar: 'خلية جنسية (مشيج)', ur: 'جنسی خلیہ' },
  { ca: 'zigot', es: 'cigoto', ar: 'اللاقحة', ur: 'زائیگوٹ' },
  { ca: 'fecundació', es: 'fecundación', ar: 'الإخصاب', ur: 'بارآوری' },
  { ca: 'somàtica', es: 'somática', ar: 'جسدية (خلية الجسم)', ur: 'جسمانی' },
  { ca: 'germinal', es: 'germinal', ar: 'تناسلية (خلية جنسية)', ur: 'تولیدی' },
  // ── 4t ESO · SA3 · El codi de la vida
  { ca: 'arn', es: 'ARN', ar: 'الرنا (RNA)', ur: 'آر این اے' },
  // ⚠️ Fals amic detectat el 24/08: l'alumnat nouvingut fa servir justament
  // una EINA de traducció, i el tooltip li deia «الترجمة / ترجمہ», o sigui
  // que entenia que es parlava de la web i no del ribosoma. Cal explicitar
  // de quina traducció/transcripció es parla.
  { ca: 'transcripció', es: 'transcripción: copiar el ADN a ARN dentro del núcleo', ar: 'النسخ: نسخ الدنا إلى رنا داخل النواة', ur: 'نقل: مرکزے میں ڈی این اے سے آر این اے بنانا' },
  { ca: 'traducció', es: 'traducción: leer el ARN en el ribosoma para fabricar la proteína', ar: 'الترجمة: قراءة الرنا في الريبوسوم لصنع البروتين', ur: 'ترجمہ: رائبوسوم میں آر این اے پڑھ کر پروٹین بنانا' },
  { ca: 'codó', es: 'codón', ar: 'الكودون', ur: 'کوڈون' },
  { ca: 'anticodó', es: 'anticodón', ar: 'الكودون المضاد', ur: 'اینٹی کوڈون' },
  { ca: 'aminoàcid', es: 'aminoácido', ar: 'حمض أميني', ur: 'امینو ایسڈ' },
  { ca: 'proteïna', es: 'proteína', ar: 'بروتين', ur: 'پروٹین' },
  { ca: 'ribosoma', es: 'ribosoma', ar: 'الريبوسوم', ur: 'رائبوسوم' },
  { ca: 'complementarietat', es: 'complementariedad', ar: 'التكامل بين القواعد', ur: 'بیسوں کی تکمیلیت' },
  { ca: 'seqüència', es: 'secuencia', ar: 'تسلسل', ur: 'ترتیب' },
  { ca: 'mutació', es: 'mutación', ar: 'طفرة', ur: 'جینیاتی تبدیلی' },
  { ca: 'embrió', es: 'embrión', ar: 'جنين', ur: 'جنین' },
  { ca: 'soluble', es: 'soluble', ar: 'قابل للذوبان', ur: 'حل پذیر' },
  { ca: 'precipita', es: 'precipita', ar: 'يترسّب', ur: 'جم کر الگ ہوتا ہے' },
  { ca: 'triturar', es: 'triturar', ar: 'يُهرَس', ur: 'پیسنا' },
  { ca: 'doble hèlix', es: 'doble hélice', ar: 'اللولب المزدوج', ur: 'ڈبل ہیلکس' },
  { ca: 'doble cadena', es: 'doble cadena', ar: 'سلسلة مزدوجة', ur: 'دوہری لڑی' },
  { ca: 'arn missatger', es: 'ARN mensajero', ar: 'الرنا الرسول', ur: 'میسنجر آر این اے' },
  { ca: 'tisores moleculars', es: 'tijeras moleculares', ar: 'مقص جزيئي', ur: 'مالیکیولر قینچی' },
  { ca: 'anèmia falciforme', es: 'anemia falciforme', ar: 'فقر الدم المنجلي', ur: 'سکل سیل انیمیا' },
  { ca: 'mutació silenciosa', es: 'mutación silenciosa', ar: 'طفرة صامتة', ur: 'خاموش تبدیلی' },
  // ── 4t ESO · SA4 · Herència
  { ca: 'gen', es: 'gen', ar: 'الجين', ur: 'جین' },
  { ca: 'al·lel', es: 'alelo', ar: 'الأليل', ur: 'ایلیل' },
  { ca: 'genotip', es: 'genotipo', ar: 'النمط الجيني', ur: 'جینوٹائپ' },
  { ca: 'fenotip', es: 'fenotipo', ar: 'النمط الظاهري', ur: 'فینوٹائپ' },
  { ca: 'homozigot', es: 'homocigoto', ar: 'متماثل اللواقح', ur: 'ہومو زائگس' },
  { ca: 'heterozigot', es: 'heterocigoto', ar: 'متغاير اللواقح', ur: 'ہیٹرو زائگس' },
  { ca: 'dominant', es: 'dominante', ar: 'سائد', ur: 'غالب' },
  { ca: 'recessiu', es: 'recesivo', ar: 'متنحٍّ', ur: 'مغلوب' },
  { ca: 'portador', es: 'portador', ar: 'حامل للجين', ur: 'جین کا حامل' },
  { ca: 'portadora', es: 'portadora', ar: 'حاملة للجين', ur: 'جین کی حامل' },
  { ca: 'hemizigot', es: 'hemicigoto: solo tiene una copia del gen', ar: 'يملك نسخة واحدة فقط من الجين (الذكر وكروموسوم X)', ur: 'جین کی صرف ایک نقل رکھنے والا' },
  { ca: 'pedigrí', es: 'árbol genealógico', ar: 'شجرة العائلة', ur: 'خاندانی شجرہ' },
  { ca: 'codominància', es: 'codominancia', ar: 'السيادة المشتركة', ur: 'مشترکہ غلبہ' },
  { ca: 'poligènia', es: 'poligenia', ar: 'تعدد الجينات', ur: 'کثیر جینی وراثت' },
  { ca: 'multifactorial', es: 'multifactorial', ar: 'متعدد العوامل', ur: 'کئی عوامل والا' },
  { ca: 'hemofília', es: 'hemofilia', ar: 'الناعور (الهيموفيليا)', ur: 'ہیموفیلیا' },
  { ca: 'daltonisme', es: 'daltonismo', ar: 'عمى الألوان', ur: 'رنگ اندھا پن' },
  { ca: 'quadre de punnett', es: 'cuadro de Punnett', ar: 'مربع بانيت', ur: 'پنیٹ اسکوائر' },
  { ca: 'consell genètic', es: 'consejo genético', ar: 'الاستشارة الوراثية', ur: 'جینیاتی مشاورت' },
  { ca: 'dominància incompleta', es: 'dominancia incompleta', ar: 'السيادة الناقصة', ur: 'نامکمل غلبہ' },
  { ca: 'al·lelisme múltiple', es: 'alelismo múltiple', ar: 'تعدد الأليلات', ur: 'متعدد ایلیل' },
  { ca: 'grups sanguinis', es: 'grupos sanguíneos', ar: 'فصائل الدم', ur: 'خون کے گروپ' },
  { ca: 'cromosomes sexuals', es: 'cromosomas sexuales', ar: 'الصبغيات الجنسية', ur: 'جنسی کروموسوم' },
  { ca: 'variació contínua', es: 'variación continua', ar: 'تغاير متصل', ur: 'مسلسل تغیر' },
  // ── 4t ESO · SA5 · Evolució
  { ca: 'evolució', es: 'evolución', ar: 'التطوّر', ur: 'ارتقا' },
  { ca: 'adaptació', es: 'adaptación', ar: 'تكيّف', ur: 'موافقت' },
  { ca: 'variabilitat', es: 'variabilidad', ar: 'التباين', ur: 'تنوع' },
  { ca: 'biodiversitat', es: 'biodiversidad', ar: 'التنوع البيولوجي', ur: 'حیاتیاتی تنوع' },
  { ca: 'fixisme', es: 'fijismo', ar: 'ثبات الأنواع', ur: 'ثباتِ انواع' },
  { ca: 'lamarckisme', es: 'lamarckismo', ar: 'اللاماركية', ur: 'لامارک ازم' },
  { ca: 'darwinisme', es: 'darwinismo', ar: 'الداروينية', ur: 'ڈارون ازم' },
  { ca: 'neodarwinisme', es: 'neodarwinismo', ar: 'الداروينية الحديثة', ur: 'نو ڈارون ازم' },
  { ca: 'homologia', es: 'homología', ar: 'التماثل البنيوي', ur: 'ہم ساختی' },
  { ca: 'analogia', es: 'analogía', ar: 'التشابه الوظيفي', ur: 'ہم عملی' },
  { ca: 'espècie', es: 'especie', ar: 'نوع', ur: 'نوع' },
  { ca: 'gènere', es: 'género', ar: 'جنس (تصنيف)', ur: 'جنس (درجہ بندی)' },
  { ca: 'domesticació', es: 'domesticación', ar: 'التدجين', ur: 'پالتو بنانا' },
  { ca: 'húmer', es: 'húmero', ar: 'عظم العضد', ur: 'عضد کی ہڈی' },
  { ca: 'cúbit', es: 'cúbito', ar: 'عظم الزند', ur: 'النا' },
  { ca: 'pelvis', es: 'pelvis', ar: 'الحوض', ur: 'شرونی' },
  { ca: 'còccix', es: 'cóccix', ar: 'العصعص', ur: 'دُم چہ' },
  { ca: 'apèndix', es: 'apéndice', ar: 'الزائدة الدودية', ur: 'اپینڈکس' },
  { ca: 'selecció natural', es: 'selección natural', ar: 'الانتقاء الطبيعي', ur: 'قدرتی انتخاب' },
  { ca: 'selecció artificial', es: 'selección artificial', ar: 'الانتقاء الاصطناعي', ur: 'مصنوعی انتخاب' },
  { ca: 'estructura vestigial', es: 'estructura vestigial', ar: 'بنية أثرية', ur: 'باقیاتی ساخت' },
  { ca: 'nomenclatura binomial', es: 'nomenclatura binomial', ar: 'التسمية الثنائية', ur: 'دو نامی نظام' },
  { ca: 'arbre de semblances', es: 'árbol de semejanzas', ar: 'شجرة التشابهات', ur: 'مشابہت کا شجرہ' },
  // ── 4t ESO · SA6 · Geologia i riscos
  { ca: 'litosfera', es: 'litosfera', ar: 'الغلاف الصخري', ur: 'لیتھوسفیئر' },
  { ca: 'mantell', es: 'manto', ar: 'الوشاح', ur: 'مینٹل' },
  { ca: 'placa', es: 'placa', ar: 'صفيحة', ur: 'پلیٹ' },
  { ca: 'convecció', es: 'convección: lo caliente sube y lo frío baja', ar: 'الحمل الحراري: الساخن يصعد والبارد ينزل', ur: 'گرم مادّے کا اوپر اور ٹھنڈے کا نیچے بہاؤ (کنویکشن)' },
  { ca: 'subducció', es: 'subducción', ar: 'الاندساس', ur: 'سبڈکشن' },
  { ca: 'dorsal', es: 'dorsal oceánica', ar: 'الحيد المحيطي', ur: 'سمندری قلاچ' },
  { ca: 'fossa', es: 'fosa oceánica', ar: 'خندق محيطي', ur: 'سمندری خندق' },
  { ca: 'orogen', es: 'orógeno', ar: 'سلسلة جبلية ناشئة', ur: 'کوہ زائی' },
  { ca: 'divergent', es: 'divergente: se separan', ar: 'متباعد: يبتعدان عن بعضهما', ur: 'ایک دوسرے سے دور ہٹتی ہوئی (ڈائیورجنٹ)' },
  { ca: 'convergent', es: 'convergente: chocan', ar: 'متقارب: يصطدمان', ur: 'ایک دوسرے کی طرف بڑھتی ہوئی (کنورجنٹ)' },
  { ca: 'transformant', es: 'transformante', ar: 'تحويلي', ur: 'ٹرانسفارم' },
  { ca: 'falla', es: 'falla', ar: 'صدع', ur: 'فالٹ (شگاف)' },
  { ca: 'estrat', es: 'estrato', ar: 'طبقة صخرية', ur: 'چٹانی تہہ' },
  { ca: 'superposició', es: 'superposición', ar: 'التراكب', ur: 'تہہ بندی' },
  { ca: 'horitzontalitat', es: 'horizontalidad', ar: 'الأفقية', ur: 'افقیت' },
  { ca: 'intersecció', es: 'intersección', ar: 'التقاطع', ur: 'قطع کرنا' },
  { ca: 'discordança', es: 'discordancia', ar: 'عدم التوافق', ur: 'ناہمواری' },
  { ca: 'erosió', es: 'erosión', ar: 'التعرية', ur: 'کٹاؤ' },
  { ca: 'actualisme', es: 'actualismo', ar: 'مبدأ الحاضر مفتاح الماضي', ur: 'یکسانیت کا اصول' },
  { ca: 'neocatastrofisme', es: 'neocatastrofismo', ar: 'الكارثية الجديدة', ur: 'نو تباہیت' },
  { ca: 'paleozoic', es: 'paleozoico', ar: 'الحقب القديم', ur: 'قدیم حیاتی دور' },
  { ca: 'mesozoic', es: 'mesozoico', ar: 'الحقب الوسيط', ur: 'وسطی حیاتی دور' },
  { ca: 'cenozoic', es: 'cenozoico', ar: 'الحقب الحديث', ur: 'جدید حیاتی دور' },
  { ca: 'calcària', es: 'caliza', ar: 'الحجر الجيري', ur: 'چونا پتھر' },
  { ca: 'gres', es: 'arenisca', ar: 'الحجر الرملي', ur: 'ریتیلا پتھر' },
  { ca: 'cendra', es: 'ceniza', ar: 'رماد', ur: 'راکھ' },
  { ca: 'terratrèmol', es: 'terremoto', ar: 'زلزال', ur: 'زلزلہ' },
  { ca: 'vulcanisme', es: 'vulcanismo', ar: 'النشاط البركاني', ur: 'آتش فشانیت' },
  { ca: 'risc', es: 'riesgo', ar: 'الخطر', ur: 'خطرہ' },
  { ca: 'perillositat', es: 'peligrosidad', ar: 'درجة الخطورة', ur: 'خطرناکی' },
  { ca: 'exposició', es: 'exposición oral · exposición al riesgo (SA6)', ar: 'عرض شفوي · التعرّض للخطر', ur: 'زبانی پیشکش · خطرے کے سامنے ہونا' },
  { ca: 'vulnerabilitat', es: 'vulnerabilidad', ar: 'الهشاشة', ur: 'کمزوری' },
  { ca: 'esllavissada', es: 'deslizamiento de tierra', ar: 'انزلاق أرضي', ur: 'لینڈ سلائیڈ' },
  { ca: 'inundació', es: 'inundación', ar: 'فيضان', ur: 'سیلاب' },
  { ca: 'embassament', es: 'embalse', ar: 'خزان مائي', ur: 'ذخیرۂ آب' },
  { ca: 'sediment', es: 'sedimento', ar: 'رواسب', ur: 'تلچھٹ' },
  { ca: 'delta', es: 'delta', ar: 'دلتا النهر', ur: 'دریائی ڈیلٹا' },
  { ca: 'litologia', es: 'litología', ar: 'نوع الصخر', ur: 'چٹان کی قسم' },
  { ca: 'relleu', es: 'relieve', ar: 'التضاريس', ur: 'ارضی خدوخال' },
  { ca: 'vegetació', es: 'vegetación', ar: 'الغطاء النباتي', ur: 'نباتاتی احاطہ' },
  { ca: 'reforestar', es: 'reforestar', ar: 'إعادة التشجير', ur: 'دوبارہ شجرکاری' },
  { ca: 'simulacre', es: 'simulacro', ar: 'تدريب على الإخلاء', ur: 'مشقی مشق' },
  { ca: 'sismoresistent', es: 'sismorresistente', ar: 'مقاوم للزلازل', ur: 'زلزلہ مزاحم' },
  { ca: 'cicle de wilson', es: 'ciclo de Wilson', ar: 'دورة ويلسون', ur: 'ولسن سائیکل' },
  { ca: 'fòssils guia', es: 'fósiles guía', ar: 'الأحافير الدالة', ur: 'ہدایتی فوسل' },
  { ca: 'deriva continental', es: 'deriva continental', ar: 'زحف القارات', ur: 'براعظمی بہاؤ' },
  { ca: 'datació relativa', es: 'datación relativa', ar: 'التأريخ النسبي', ur: 'اضافی تاریخ سازی' },
  { ca: 'datació absoluta', es: 'datación absoluta', ar: 'التأريخ المطلق', ur: 'مطلق تاریخ سازی' },
  // ── 4t ESO · SA7 · L'origen de tot
  { ca: 'big bang', es: 'Big Bang', ar: 'الانفجار العظيم', ur: 'بگ بینگ' },
  { ca: 'semivida', es: 'vida media: tiempo en que se desintegra la mitad', ar: 'عمر النصف: الزمن الذي يتحلل فيه نصف المادة', ur: 'نصف زندگی: جس میں آدھا مادہ ٹوٹ جاتا ہے' },
  { ca: 'radioactivitat', es: 'radiactividad', ar: 'النشاط الإشعاعي', ur: 'تابکاری' },
  { ca: 'datació', es: 'datación', ar: 'التأريخ (تحديد العمر)', ur: 'تاریخ سازی' },
  { ca: 'meteorit', es: 'meteorito', ar: 'نيزك', ur: 'شہابیہ' },
  { ca: 'exoplaneta', es: 'exoplaneta', ar: 'كوكب خارج المجموعة الشمسية', ur: 'خارجی سیارہ' },
  { ca: 'panspèrmia', es: 'panspermia: la vida vino del espacio', ar: 'البذر الكوني: الحياة جاءت من الفضاء', ur: 'پین اسپرمیا: زندگی خلا سے آئی' },
  { ca: 'astrobiologia', es: 'astrobiología', ar: 'علم الأحياء الفلكي', ur: 'فلکی حیاتیات' },
  { ca: 'especulació', es: 'especulación', ar: 'تكهّن', ur: 'قیاس آرائی' },
  { ca: 'estromatòlits', es: 'estromatolitos: rocas hechas por bacterias antiguas', ar: 'صخور بنَتْها بكتيريا قديمة', ur: 'قدیم بیکٹیریا کی بنائی ہوئی چٹانیں' },
  { ca: 'fumaroles hidrotermals', es: 'fumarolas hidrotermales', ar: 'فوهات مائية حرارية', ur: 'گرم آبی سوراخ' },
  { ca: 'món arn', es: 'mundo ARN', ar: 'عالم الرنا', ur: 'آر این اے کی دنیا' },
  // ── 4t ESO · Vocabulari transversal (surt a totes les SA)
  { ca: 'fòssil', es: 'fósil', ar: 'أحفورة', ur: 'رکاز (فوسل)' },
  { ca: 'dada', es: 'dato', ar: 'مُعطى / بيانات', ur: 'ڈیٹا' },
  { ca: 'model', es: 'modelo', ar: 'نموذج', ur: 'ماڈل' },
  { ca: 'teoria', es: 'teoría', ar: 'نظرية', ur: 'نظریہ' },
  { ca: 'cromosoma', es: 'cromosoma', ar: 'صبغي (كروموسوم)', ur: 'کروموسوم' },
  { ca: 'herència', es: 'herencia', ar: 'الوراثة', ur: 'وراثت' },
  { ca: 'variable', es: 'variable', ar: 'متغيّر', ur: 'متغیر' },
  { ca: 'experiment', es: 'experimento', ar: 'تجربة', ur: 'تجربہ' },
  { ca: 'resultat', es: 'resultado', ar: 'نتيجة', ur: 'نتیجہ' },
  { ca: 'observar', es: 'observar', ar: 'يُلاحِظ', ur: 'مشاہدہ کرنا' },
  { ca: 'inferir', es: 'inferir', ar: 'يستنتج', ur: 'نتیجہ اخذ کرنا' },
  { ca: 'ambient', es: 'ambiente / entorno', ar: 'البيئة', ur: 'ماحول' },
  { ca: 'límit', es: 'límite', ar: 'حدّ', ur: 'حد' },
  { ca: 'temps', es: 'tiempo (cronológico) · el tiempo (meteorología)', ar: 'الزمن · حالة الطقس', ur: 'وقت · موسم' },
  { ca: 'nivell', es: 'nivel', ar: 'مستوى', ur: 'سطح' },
  { ca: 'divisió', es: 'división', ar: 'انقسام', ur: 'تقسیم' },
  { ca: 'reproducció', es: 'reproducción', ar: 'التكاثر', ur: 'تولید' },
  { ca: 'diagnòstic', es: 'diagnóstico', ar: 'تشخيص', ur: 'تشخیص' },
  { ca: 'mostra', es: 'muestra', ar: 'عيّنة', ur: 'نمونہ' },
  { ca: 'gràfic', es: 'gráfico', ar: 'رسم بياني', ur: 'گراف' },
  { ca: 'calor', es: 'calor', ar: 'الحرارة', ur: 'حرارت' },
  { ca: 'ordre', es: 'orden', ar: 'ترتيب', ur: 'ترتیب' },
  { ca: 'mecanisme', es: 'mecanismo', ar: 'آليّة', ur: 'طریقۂ کار' },
  { ca: 'gravetat', es: 'gravedad', ar: 'الجاذبية', ur: 'کششِ ثقل' },
  { ca: 'sorra', es: 'arena', ar: 'رمل', ur: 'ریت' },
  { ca: 'barreja', es: 'mezcla', ar: 'خليط', ur: 'آمیزہ / ملاوٹ' },
  { ca: 'prevenció', es: 'prevención', ar: 'الوقاية', ur: 'روک تھام' },
  { ca: 'correcció', es: 'corrección', ar: 'التصحيح / المعالجة', ur: 'درستی' },
  { ca: 'rellotge', es: 'reloj', ar: 'ساعة', ur: 'گھڑی' },
  { ca: 'postura', es: 'postura', ar: 'موقف', ur: 'مؤقف' },
  { ca: 'benefici', es: 'beneficio', ar: 'فائدة', ur: 'فائدہ' },
  { ca: 'versió', es: 'versión', ar: 'نسخة', ur: 'نسخہ' },
  { ca: 'quadrat', es: 'cuadrado', ar: 'مربّع', ur: 'مربع' },
  { ca: 'cercle', es: 'círculo', ar: 'دائرة', ur: 'دائرہ' },
  { ca: 'alçada', es: 'altura', ar: 'الطول (القامة)', ur: 'قد' },
  { ca: 'nerviós', es: 'nervioso', ar: 'عصبي', ur: 'اعصابی' },
  { ca: 'tòxic', es: 'tóxico', ar: 'سام', ur: 'زہریلا' },
  { ca: 'intern', es: 'interno', ar: 'داخلي', ur: 'اندرونی' },
  { ca: 'extern', es: 'externo', ar: 'خارجي', ur: 'بیرونی' },
  { ca: 'induït', es: 'inducido', ar: 'مُستحَث (بفعل الإنسان)', ur: 'انسانی سبب سے پیدا شدہ' },
  { ca: 'marí', es: 'marino', ar: 'بحري', ur: 'سمندری' },
  { ca: 'relativa', es: 'relativa', ar: 'نسبية', ur: 'اضافی' },
  { ca: 'absoluta', es: 'absoluta', ar: 'مطلقة', ur: 'مطلق' },
  { ca: 'sabó', es: 'jabón', ar: 'صابون', ur: 'صابن' },
  { ca: 'alcohol', es: 'alcohol', ar: 'كحول', ur: 'الکحل' },
  { ca: 'ésser viu', es: 'ser vivo', ar: 'كائن حيّ', ur: 'جاندار' },

  // ═══════════════════════════════════════════════════════════
  // TANDA 2 (2026-08-24) · Cobertura de les paraules ressaltades
  // ═══════════════════════════════════════════════════════════
  // L'auditoria de les 30 sessions va trobar que dels 1.865 tokens
  // marcats amb ==…== només 495 tenien entrada. El buit es reparteix
  // en tres blocs, i aquesta tanda els ataca tots tres:
  //   A) EXPRESSIONS terminològiques de diverses paraules — són EL
  //      concepte, i traduïdes paraula per paraula no volen dir res
  //      («encara no comprovat», «índex mitòtic», «a l'atzar»).
  //   B) PARAULES DE CONTINGUT que faltaven (científiques i, sobretot,
  //      epistèmiques: tot el vocabulari amb què es parla de proves).
  //   C) CATALÀ GENERAL d'alta freqüència dins dels trams ressaltats.
  //      El 39 % dels tokens marcats són paraules com «encara», «prou»,
  //      «cap», «sota» o «gairebé»: sense elles, una frase clau sencera
  //      es queda literalment sense cap tooltip. Es van descartar el
  //      21/08 per «no ser de ciències»; l'error era mirar la paraula i
  //      no la frase on viu.
  // ⚠️ NO es donen d'alta els NOMS PROPIS ressaltats (Wegener, Mendel,
  //    Miller-Urey, Hutton, Lyell, Rosalind Franklin, Mesosaurus,
  //    Archaeopteryx, Gallus gallus, Amposta, Castor, James Webb…):
  //    un nom no es tradueix. Són 39 tokens que no s'han de perseguir
  //    en auditories futures.
  // ⚠️ Àrab i urdú fets per Claude: correctes pel que sap, però
  //    pendents de revisió d'algú que els tingui com a llengua materna.

  // ── A) Expressions terminològiques ──────────────────────
  { ca: 'encara no comprovat', es: 'aún no comprobado', ar: 'لم يُثبَت بعد', ur: 'ابھی تک ثابت نہیں' },
  { ca: 'encara no comprovada', es: 'aún no comprobada', ar: 'لم تُثبَت بعد', ur: 'ابھی تک ثابت نہیں' },
  // (índex mitòtic · perfil epistèmic · cicle cel·lular · quadre de Punnett ·
  //  selecció natural/artificial · hipòtesi contrastable · anèmia falciforme ·
  //  nomenclatura binomial · estructura vestigial · arbre de semblances ·
  //  fòssils guia · cicle de Wilson · Big Bang · doble hèlix · doble cadena ·
  //  ARN missatger · mutació silenciosa · tisores moleculars · dominància
  //  incompleta · al·lelisme múltiple · grups sanguinis · qüestió
  //  sociocientífica · control negatiu/positiu · a cegues · món ARN
  //  ja hi eren de la tanda 1: no es dupliquen aquí.)
  { ca: 'ARN polimerasa', es: 'ARN polimerasa (copia el ADN a ARN)', ar: 'بوليميراز الرنا', ur: 'آر این اے پولیمریز' },
  { ca: 'grup sanguini', es: 'grupo sanguíneo', ar: 'فصيلة الدم', ur: 'خون کا گروپ' },
  { ca: 'lligada al sexe', es: 'ligada al sexo', ar: 'مرتبطة بالجنس', ur: 'جنس سے منسلک' },
  { ca: 'lligat al sexe', es: 'ligado al sexo', ar: 'مرتبط بالجنس', ur: 'جنس سے منسلک' },
  { ca: 'fet contrastat', es: 'hecho contrastado (comprobado)', ar: 'حقيقة مؤكَّدة', ur: 'تصدیق شدہ حقیقت' },
  { ca: 'titular sensacionalista', es: 'titular sensacionalista (exagerado)', ar: 'عنوان مثير ومبالَغ فيه', ur: 'سنسنی خیز سرخی' },
  { ca: 'notícia rigorosa', es: 'noticia rigurosa (seria y bien hecha)', ar: 'خبر دقيق ورصين', ur: 'محتاط اور معیاری خبر' },
  { ca: 'mètode experimental', es: 'método experimental', ar: 'المنهج التجريبي', ur: 'تجرباتی طریقہ' },
  { ca: 'a l\'atzar', es: 'al azar (sin ninguna intención)', ar: 'عشوائيًا (بلا قصد)', ur: 'بے ترتیب طور پر (بغیر کسی ارادے کے)' },
  { ca: 'posar a prova', es: 'poner a prueba', ar: 'يضع على المحكّ / يختبر', ur: 'آزمانا، جانچنا' },
  { ca: 'avantpassat comú', es: 'antepasado común', ar: 'سلف مشترك', ur: 'مشترکہ جدِ امجد' },
  { ca: 'escalfament global', es: 'calentamiento global', ar: 'الاحترار العالمي', ur: 'عالمی حدت' },
  { ca: 'zona inundable', es: 'zona inundable', ar: 'منطقة معرّضة للفيضان', ur: 'سیلاب زدہ علاقہ' },
  { ca: 'temps geològic', es: 'tiempo geológico (millones de años)', ar: 'الزمن الجيولوجي (ملايين السنين)', ur: 'ارضیاتی وقت (لاکھوں کروڑوں سال)' },
  { ca: 'sopa primordial', es: 'sopa primordial', ar: 'الحساء البدائي', ur: 'ابتدائی شوربہ' },
  { ca: 'prova viva', es: 'prueba viva (un ser vivo actual que lo demuestra)', ar: 'دليل حيّ (كائن حيّ اليوم يثبت ذلك)', ur: 'زندہ ثبوت' },
  { ca: 'estructures homòlogues', es: 'estructuras homólogas (mismo origen)', ar: 'بنى متماثلة الأصل', ur: 'ہم اصل ساختیں' },
  { ca: 'estructures anàlogues', es: 'estructuras análogas (misma función, distinto origen)', ar: 'بنى متشابهة الوظيفة مختلفة الأصل', ur: 'ہم کام مگر مختلف اصل کی ساختیں' },
  { ca: 'certesa social', es: 'certeza social (lo cree todo el mundo)', ar: 'يقين اجتماعي (يصدّقه الجميع)', ur: 'سماجی یقین (سب مانتے ہیں)' },
  { ca: 'primera generació', es: 'primera generación (los hijos)', ar: 'الجيل الأول (الأبناء)', ur: 'پہلی نسل (اولاد)' },
  { ca: 'cromosomes condensats', es: 'cromosomas condensados (apretados, ya se ven)', ar: 'كروموسومات متكثّفة (مضغوطة وظاهرة)', ur: 'گاڑھے ہوئے کروموسوم (نظر آنے لگتے ہیں)' },
  { ca: 'material genètic', es: 'material genético', ar: 'المادة الوراثية', ur: 'جینیاتی مواد' },
  { ca: 'no n\'hi ha prou', es: 'no basta, no es suficiente', ar: 'لا يكفي', ur: 'یہ کافی نہیں' },
  { ca: 'abans i després', es: 'antes y después', ar: 'قبل وبعد', ur: 'پہلے اور بعد میں' },

  // ── B) Paraules de contingut ────────────────────────────
  // Ciència
  // ⚠️ Dos sentits ben diferents i tots dos són centrals al curs: a SA2 «el
  // control del cicle» vol dir REGULACIÓ (que la cèl·lula no es descontroli);
  // a SA1/SA2·S3 «el control» és el grup de comparació de l'experiment.
  { ca: 'control', es: 'control: (1) que algo no se descontrole; (2) grupo de comparación del experimento', ar: 'الضبط (ألّا ينفلت الشيء)؛ وفي التجربة: مجموعة المقارنة', ur: 'قابو/ضبط (بے قابو نہ ہو)؛ تجربے میں: موازنہ گروپ' },
  { ca: 'estructura', es: 'estructura (cómo está hecho)', ar: 'البنية (كيف هو مكوَّن)', ur: 'ساخت (کس طرح بنا ہے)' },
  { ca: 'funció', es: 'función (para qué sirve)', ar: 'الوظيفة (ما فائدته)', ur: 'کام (کس لیے ہے)' },
  { ca: 'motor', es: 'motor (lo que hace que algo se mueva)', ar: 'المحرّك (ما يجعل الشيء يتحرّك)', ur: 'محرک (جو حرکت دیتا ہے)' },
  { ca: 'senyal', es: 'señal (indicio que avisa)', ar: 'علامة (مؤشر ينبّه)', ur: 'نشانی (اشارہ)' },
  { ca: 'detector', es: 'detector (herramienta para descubrir algo)', ar: 'كاشف (أداة لاكتشاف شيء)', ur: 'ڈیٹیکٹر (پتہ لگانے کا آلہ)' },
  { ca: 'factor', es: 'factor (algo que influye)', ar: 'عامل (شيء يؤثّر)', ur: 'عامل (اثر ڈالنے والی چیز)' },
  { ca: 'rèplica', es: 'réplica: la respuesta con la que rebates un argumento en un debate', ar: 'الردّ المضادّ على حجّة في مناظرة', ur: 'بحث میں جوابی دلیل' },
  { ca: 'rèpliques', es: 'réplicas: repeticiones del experimento', ar: 'تكرارات التجربة', ur: 'تجربے کی تکرار' },
  { ca: 'evidència', es: 'evidencia, prueba', ar: 'دليل', ur: 'ثبوت' },
  { ca: 'experimental', es: 'experimental (se comprueba con un experimento de verdad)', ar: 'تجريبي (يُختبَر بتجربة حقيقية)', ur: 'تجرباتی (اصل تجربے سے جانچا جائے)' },
  { ca: 'metodologia', es: 'metodología (cómo se ha hecho)', ar: 'المنهجية (كيف أُجري العمل)', ur: 'طریقۂ کار' },
  { ca: 'protocol', es: 'protocolo (los pasos a seguir)', ar: 'بروتوكول (الخطوات المتّبعة)', ur: 'طریقۂ عمل (اقدامات)' },
  { ca: 'graella', es: 'tabla de análisis, parrilla', ar: 'جدول تحليل', ur: 'تجزیاتی خانہ' },
  { ca: 'escala', es: 'escala', ar: 'مقياس / سُلَّم', ur: 'پیمانہ' },
  { ca: 'columna', es: 'columna', ar: 'عمود', ur: 'کالم' },
  { ca: 'informació', es: 'información', ar: 'معلومات', ur: 'معلومات' },
  { ca: 'memòria', es: 'memoria (lo que queda registrado)', ar: 'ذاكرة (ما يبقى مسجَّلًا)', ur: 'یادداشت (جو محفوظ رہ جاتا ہے)' },
  { ca: 'edat', es: 'edad (cuántos años tiene)', ar: 'العمر (كم سنة له)', ur: 'عمر' },
  { ca: 'milió', es: 'millón', ar: 'مليون', ur: 'دس لاکھ (ملین)' },
  { ca: 'lletra', es: 'letra', ar: 'حرف', ur: 'حرف' },
  { ca: 'cas', es: 'caso (ejemplo real que se estudia)', ar: 'حالة (مثال حقيقي يُدرَس)', ur: 'کیس (زیرِ مطالعہ حقیقی مثال)' },
  { ca: 'llei', es: 'ley (regla que siempre se cumple)', ar: 'قانون (قاعدة تتحقّق دائمًا)', ur: 'قانون (ہمیشہ لاگو ہونے والا اصول)' },
  { ca: 'principi', es: 'principio (regla básica)', ar: 'مبدأ (قاعدة أساسية)', ur: 'اصول (بنیادی قاعدہ)' },
  // Genètica i cèl·lula
  { ca: 'arnm', es: 'ARNm (ARN mensajero)', ar: 'الرنا المرسال', ur: 'ایم آر این اے' },
  { ca: 'polimerasa', es: 'polimerasa (enzima que copia)', ar: 'بوليميراز (إنزيم ينسخ)', ur: 'پولیمریز (نقل کرنے والا اینزائم)' },
  { ca: 'ribozim', es: 'ribozima (ARN que además actúa como enzima)', ar: 'رايبوزيم (رنا يعمل أيضًا كإنزيم)', ur: 'رائبوزائم (آر این اے جو اینزائم کا کام بھی کرے)' },
  { ca: 'glutamat', es: 'glutamato (un aminoácido)', ar: 'الغلوتامات (حمض أميني)', ur: 'گلوٹامیٹ (ایک امینو ایسڈ)' },
  { ca: 'valina', es: 'valina (un aminoácido)', ar: 'الفالين (حمض أميني)', ur: 'ویلین (ایک امینو ایسڈ)' },
  { ca: 'antigen', es: 'antígeno (marca de la superficie de la célula)', ar: 'مستضدّ (علامة على سطح الخلية)', ur: 'اینٹیجن (خلیے کی سطح کا نشان)' },
  { ca: 'antígens', es: 'antígenos (marcas de la superficie de la célula)', ar: 'مستضدّات (علامات على سطح الخلية)', ur: 'اینٹیجنز (خلیے کی سطح کے نشان)' },
  { ca: 'codominant', es: 'codominante (los dos se ven a la vez)', ar: 'سائد مشارك (كلاهما يظهر معًا)', ur: 'شریک غالب (دونوں ایک ساتھ ظاہر)' },
  { ca: 'poligènic', es: 'poligénico (dependen de muchos genes)', ar: 'متعدّد الجينات', ur: 'کئی جینز پر منحصر' },
  { ca: 'segregació', es: 'segregación (los alelos se separan)', ar: 'انعزال (انفصال الأليلات)', ur: 'علیحدگی (ایلیل الگ ہو جاتے ہیں)' },
  { ca: 'descendència', es: 'descendencia (los hijos y sus hijos)', ar: 'الذرّية (الأبناء وأبناؤهم)', ur: 'نسل (اولاد اور ان کی اولاد)' },
  { ca: 'descendent', es: 'descendiente (hijo, nieto…)', ar: 'سليل (ابن، حفيد…)', ur: 'اولاد میں سے (بیٹا، پوتا…)' },
  { ca: 'avantpassat', es: 'antepasado', ar: 'سلف / جدّ', ur: 'جدِ امجد، پرکھا' },
  { ca: 'parentiu', es: 'parentesco (de qué familia es)', ar: 'صلة القرابة', ur: 'رشتہ داری' },
  { ca: 'generació', es: 'generación', ar: 'جيل', ur: 'نسل' },
  { ca: 'sexe', es: 'sexo', ar: 'الجنس (ذكر/أنثى)', ur: 'جنس (نر/مادہ)' },
  { ca: 'ovari', es: 'ovario', ar: 'مبيض', ur: 'بیضہ دانی' },
  { ca: 'testicle', es: 'testículo', ar: 'خصية', ur: 'خصیہ' },
  { ca: 'pare', es: 'padre', ar: 'الأب', ur: 'باپ' },
  { ca: 'mare', es: 'madre', ar: 'الأم', ur: 'ماں' },
  { ca: 'fill', es: 'hijo', ar: 'ابن', ur: 'بیٹا' },
  { ca: 'filla', es: 'hija', ar: 'ابنة', ur: 'بیٹی' },
  { ca: 'home', es: 'el ser humano (la especie); o un hombre', ar: 'الإنسان (النوع البشري)؛ أو رجل', ur: 'انسان (نوعِ انسانی)؛ یا مرد' },
  { ca: 'hemofílic', es: 'hemofílico (que tiene hemofilia)', ar: 'مصاب بالناعور (الهيموفيليا)', ur: 'ہیموفیلیا کا مریض' },
  { ca: 'falç', es: 'hoz (herramienta curvada; forma del glóbulo enfermo)', ar: 'منجل (شكل منحنٍ، كشكل الكرية المريضة)', ur: 'درانتی (خمدار شکل، بیمار خلیے کی طرح)' },
  { ca: 'porus', es: 'poro (agujero muy pequeño)', ar: 'مسام (ثقب صغير جدًا)', ur: 'مسام (بہت چھوٹا سوراخ)' },
  { ca: 'queixal', es: 'muela', ar: 'ضرس', ur: 'داڑھ' },
  { ca: 'greix', es: 'grasa', ar: 'دهن', ur: 'چربی' },
  { ca: 'detergent', es: 'detergente', ar: 'منظّف', ur: 'ڈٹرجنٹ' },
  { ca: 'mescla', es: 'mezcla', ar: 'خليط', ur: 'آمیزہ' },
  { ca: 'solubilitat', es: 'solubilidad (si se disuelve o no)', ar: 'الذوبانية (هل يذوب أم لا)', ur: 'حل پذیری (گھلتا ہے یا نہیں)' },
  { ca: 'precipitació', es: 'precipitación (se separa y se ve, en sólido)', ar: 'الترسيب (ينفصل ويظهر صلبًا)', ur: 'ترسیب (الگ ہو کر ٹھوس شکل میں نظر آنا)' },
  // Evolució
  { ca: 'homòleg', es: 'homólogo (mismo origen)', ar: 'متماثل الأصل', ur: 'ہم اصل' },
  { ca: 'anàleg', es: 'análogo (misma función, distinto origen)', ar: 'متشابه الوظيفة مختلف الأصل', ur: 'ہم کام مگر مختلف اصل' },
  { ca: 'vestigial', es: 'vestigial (resto que ya no sirve)', ar: 'أثري (بقية لم تعد تعمل)', ur: 'باقیاتی (اب بے کار باقیات)' },
  { ca: 'anatòmica', es: 'anatómica (de la forma del cuerpo)', ar: 'تشريحية (تتعلق بشكل الجسم)', ur: 'جسمانی ساخت سے متعلق' },
  { ca: 'embriològica', es: 'embriológica (del embrión)', ar: 'جنينية (تتعلق بالجنين)', ur: 'جنین سے متعلق' },
  { ca: 'paleontològica', es: 'paleontológica (de los fósiles)', ar: 'أحفورية (تتعلق بالمستحاثات)', ur: 'فوسل سے متعلق' },
  { ca: 'biogeogràfica', es: 'biogeográfica (de dónde vive cada especie)', ar: 'حيوية جغرافية (أين يعيش كل نوع)', ur: 'حیاتی جغرافیائی (کون کہاں رہتا ہے)' },
  { ca: 'bioquímica', es: 'bioquímica (de las moléculas de los seres vivos)', ar: 'كيميائية حيوية (جزيئات الكائنات الحية)', ur: 'حیاتی کیمیائی (جانداروں کے مالیکیول)' },
  { ca: 'ala', es: 'ala', ar: 'جناح', ur: 'پَر، بازو' },
  { ca: 'ocell', es: 'pájaro, ave', ar: 'طائر', ur: 'پرندہ' },
  { ca: 'insecte', es: 'insecto', ar: 'حشرة', ur: 'کیڑا' },
  { ca: 'ossos', es: 'huesos', ar: 'عظام', ur: 'ہڈیاں' },
  { ca: 'arrel', es: 'raíz', ar: 'جذر', ur: 'جڑ' },
  { ca: 'tret', es: 'rasgo, característica', ar: 'صفة، سمة', ur: 'خصوصیت' },
  { ca: 'característica', es: 'característica (cómo es)', ar: 'صفة (كيف يبدو)', ur: 'خصوصیت' },
  { ca: 'creacionisme', es: 'creacionismo (creencia religiosa sobre el origen)', ar: 'الخلقوية (اعتقاد ديني حول أصل الكائنات)', ur: 'تخلیقیت (اصل کے بارے میں مذہبی عقیدہ)' },
  { ca: 'evolutiva', es: 'evolutiva (del cambio de las especies con el tiempo)', ar: 'تطورية (تغيّر الأنواع عبر الزمن)', ur: 'ارتقائی (وقت کے ساتھ انواع کی تبدیلی)' },
  // Geologia i univers
  { ca: 'escorça', es: 'corteza (la capa de fuera de la Tierra)', ar: 'القشرة (الطبقة الخارجية للأرض)', ur: 'قشر (زمین کی بیرونی تہہ)' },
  { ca: 'orògens', es: 'orógenos (cordilleras que se levantan)', ar: 'سلاسل جبلية ناشئة', ur: 'اٹھتے ہوئے پہاڑی سلسلے' },
  { ca: 'tectònica', es: 'tectónica (movimiento de las placas)', ar: 'التكتونية (حركة الصفائح)', ur: 'ٹیکٹونکس (پلیٹوں کی حرکت)' },
  { ca: 'magnetisme', es: 'magnetismo (como un imán)', ar: 'المغناطيسية (كالمغناطيس)', ur: 'مقناطیسیت' },
  { ca: 'sísmica', es: 'sísmica (de los terremotos)', ar: 'زلزالية', ur: 'زلزلوں سے متعلق' },
  { ca: 'radiació', es: 'radiación (energía que sale de una materia inestable)', ar: 'إشعاع (طاقة تخرج من مادة غير مستقرّة)', ur: 'شعاعیں (غیر مستحکم مادے سے نکلنے والی توانائی)' },
  { ca: 'expansió', es: 'expansión (se hace más grande)', ar: 'تمدّد (يكبر ويتّسع)', ur: 'پھیلاؤ' },
  { ca: 'fusió', es: 'fusión (unirse en uno)', ar: 'اندماج (اتحاد في واحد)', ur: 'ملاپ، فیوژن' },
  { ca: 'còsmica', es: 'cósmica (del universo)', ar: 'كونية (تتعلق بالكون)', ur: 'کائناتی' },
  { ca: 'inorgànica', es: 'inorgánica (que no viene de seres vivos)', ar: 'غير عضوية (لا تأتي من كائنات حية)', ur: 'غیر نامیاتی (جانداروں سے نہیں آتی)' },
  { ca: 'terrestre', es: 'terrestre (de la Tierra)', ar: 'أرضي', ur: 'زمینی' },
  { ca: 'rocós', es: 'rocoso (de roca)', ar: 'صخري', ur: 'چٹانی' },
  { ca: 'gasós', es: 'gaseoso (de gas)', ar: 'غازي', ur: 'گیسی' },
  { ca: 'desert', es: 'desierto', ar: 'صحراء', ur: 'صحرا' },
  { ca: 'paisatge', es: 'paisaje', ar: 'المشهد الطبيعي', ur: 'منظر، خطہ' },
  { ca: 'muntanya', es: 'montaña', ar: 'جبل', ur: 'پہاڑ' },
  { ca: 'riu', es: 'río', ar: 'نهر', ur: 'دریا' },
  { ca: 'fang', es: 'barro, lodo', ar: 'طين', ur: 'کیچڑ' },
  { ca: 'sal', es: 'sal', ar: 'ملح', ur: 'نمک' },
  { ca: 'aire', es: 'aire', ar: 'هواء', ur: 'ہوا' },
  { ca: 'llum', es: 'luz', ar: 'ضوء', ur: 'روشنی' },
  { ca: 'aigua', es: 'agua', ar: 'ماء', ur: 'پانی' },
  { ca: 'fred', es: 'frío', ar: 'بارد', ur: 'ٹھنڈا' },
  { ca: 'calent', es: 'caliente', ar: 'ساخن', ur: 'گرم' },
  { ca: 'càlid', es: 'cálido (clima caliente)', ar: 'دافئ (مناخ حار)', ur: 'گرم (آب و ہوا)' },
  { ca: 'dens', es: 'denso (pesa mucho para su tamaño)', ar: 'كثيف (ثقيل بالنسبة لحجمه)', ur: 'کثیف (حجم کے لحاظ سے بھاری)' },
  { ca: 'fluid', es: 'fluido (líquido o gas, que fluye)', ar: 'مائع أو غاز يتدفّق', ur: 'سیال (بہنے والا)' },
  { ca: 'distància', es: 'distancia', ar: 'مسافة', ur: 'فاصلہ' },
  { ca: 'franja', es: 'franja (banda entre dos límites)', ar: 'نطاق (شريط بين حدّين)', ur: 'پٹی (دو حدوں کے درمیان)' },
  { ca: 'amplada', es: 'anchura', ar: 'العرض', ur: 'چوڑائی' },
  { ca: 'pes', es: 'peso', ar: 'الوزن', ur: 'وزن' },
  { ca: 'cos', es: 'cuerpo', ar: 'الجسم', ur: 'جسم' },
  { ca: 'inundable', es: 'inundable (se puede inundar)', ar: 'معرّض للفيضان', ur: 'سیلاب کا خطرہ رکھنے والا' },
  { ca: 'cremat', es: 'quemado', ar: 'محترق', ur: 'جلا ہوا' },
  { ca: 'desastre', es: 'desastre, catástrofe', ar: 'كارثة', ur: 'آفت' },
  { ca: 'dany', es: 'daño', ar: 'ضرر', ur: 'نقصان' },
  // Epistèmiques (el vocabulari amb què es parla de proves)
  { ca: 'comprovat', es: 'comprobado (ya se ha verificado)', ar: 'مُثبَت (تمّ التحقق منه)', ur: 'ثابت شدہ (تصدیق ہو چکی)' },
  { ca: 'comprovada', es: 'comprobada', ar: 'مُثبَتة', ur: 'ثابت شدہ' },
  { ca: 'contrastat', es: 'contrastado (comparado con pruebas)', ar: 'مُتحقَّق منه بالأدلة', ur: 'شواہد سے جانچا ہوا' },
  { ca: 'establert', es: 'establecido (aceptado por toda la ciencia)', ar: 'راسخ (مقبول علميًا)', ur: 'مستحکم (سائنس میں تسلیم شدہ)' },
  { ca: 'rebutjada', es: 'rechazada (las pruebas dicen que no)', ar: 'مرفوضة (الأدلة تنفيها)', ur: 'مسترد (شواہد اس کے خلاف ہیں)' },
  { ca: 'rebutjar', es: 'rechazar', ar: 'يرفض', ur: 'مسترد کرنا' },
  { ca: 'veredicte', es: 'veredicto (tu decisión razonada)', ar: 'الحكم (قرارك المُعلَّل)', ur: 'فیصلہ (دلیل کے ساتھ)' },
  { ca: 'fals', es: 'falso', ar: 'خاطئ / زائف', ur: 'جھوٹا، غلط' },
  { ca: 'falsa', es: 'falsa', ar: 'خاطئة / زائفة', ur: 'جھوٹی، غلط' },
  { ca: 'correcta', es: 'correcta', ar: 'صحيحة', ur: 'درست' },
  { ca: 'incorrecta', es: 'incorrecta', ar: 'غير صحيحة', ur: 'غلط' },
  { ca: 'justificada', es: 'justificada (con razones)', ar: 'مبرَّرة (مدعّمة بأسباب)', ur: 'دلیل کے ساتھ' },
  { ca: 'fonamentada', es: 'fundamentada (apoyada en algo sólido)', ar: 'مؤسَّسة على أساس متين', ur: 'ٹھوس بنیاد پر' },
  { ca: 'rigorosa', es: 'rigurosa (hecha con cuidado y seriedad)', ar: 'دقيقة ورصينة', ur: 'محتاط اور معیاری' },
  { ca: 'honest', es: 'honesto (dice la verdad aunque no le convenga)', ar: 'أمين (يقول الحقيقة ولو ضدّه)', ur: 'دیانت دار (اپنے خلاف بھی سچ کہے)' },
  { ca: 'sensacionalista', es: 'sensacionalista (exagera para llamar la atención)', ar: 'مثير ومبالِغ لجذب الانتباه', ur: 'سنسنی پھیلانے والا' },
  { ca: 'exagerat', es: 'exagerado', ar: 'مبالَغ فيه', ur: 'بڑھا چڑھا کر' },
  { ca: 'titular', es: 'titular (el título grande de la noticia)', ar: 'العنوان الرئيسي للخبر', ur: 'خبر کی سرخی' },
  { ca: 'notícia', es: 'noticia', ar: 'خبر', ur: 'خبر' },
  { ca: 'font', es: 'fuente: de dónde sale la información; también fuente de agua', ar: 'مصدر (من أين جاءت المعلومة)؛ وأيضًا نبع ماء', ur: 'ماخذ (معلومات کہاں سے آئی)؛ نیز پانی کا چشمہ' },
  { ca: 'revisió', es: 'revisión (que otros lo comprueben)', ar: 'مراجعة (أن يتحقّق منه آخرون)', ur: 'نظرثانی (دوسرے جانچیں)' },
  { ca: 'revisor', es: 'revisor (quien comprueba el trabajo de otro)', ar: 'مُراجِع (من يتحقّق من عمل غيره)', ur: 'نظرثانی کرنے والا' },
  { ca: 'simplificació', es: 'simplificación (versión más simple de la realidad)', ar: 'تبسيط (نسخة أبسط من الواقع)', ur: 'سادہ بنایا ہوا نمونہ' },
  { ca: 'incerta', es: 'incierta (no se sabe seguro)', ar: 'غير مؤكَّدة', ur: 'غیر یقینی' },
  { ca: 'neutral', es: 'neutral (no toma partido)', ar: 'محايد (لا ينحاز)', ur: 'غیر جانبدار' },
  { ca: 'trampa', es: 'trampa (engaño)', ar: 'خدعة', ur: 'دھوکہ، چال' },
  { ca: 'enganyar', es: 'engañar', ar: 'يخدع', ur: 'دھوکہ دینا' },
  { ca: 'sospitar', es: 'sospechar', ar: 'يشكّ', ur: 'شک کرنا' },
  { ca: 'ignorar', es: 'ignorar (no hacer caso a propósito)', ar: 'يتجاهل (لا يعير انتباهًا عمدًا)', ur: 'جان بوجھ کر نظر انداز کرنا' },
  { ca: 'admet', es: 'admite, acepta', ar: 'يقبل، يعترف', ur: 'مانتا ہے، قبول کرتا ہے' },
  { ca: 'afirma', es: 'afirma (dice que es así)', ar: 'يؤكّد (يقول إنه كذلك)', ur: 'دعویٰ کرتا ہے' },
  { ca: 'afirmar', es: 'afirmar', ar: 'يؤكّد', ur: 'دعویٰ کرنا' },
  { ca: 'crítica', es: 'crítica (que le digan qué falla)', ar: 'نقد (أن يُقال له ما الخطأ)', ur: 'تنقید (خامی بتائی جائے)' },
  { ca: 'actitud', es: 'actitud (cómo te comportas ante algo)', ar: 'موقف (كيف تتصرّف تجاه شيء)', ur: 'رویہ' },
  { ca: 'intenció', es: 'intención (qué quiere conseguir)', ar: 'نيّة (ما الذي يريد تحقيقه)', ur: 'ارادہ، نیت' },
  { ca: 'qualitat', es: 'calidad (si está bien hecho)', ar: 'الجودة (هل هو متقن)', ur: 'معیار' },
  { ca: 'eina', es: 'herramienta', ar: 'أداة', ur: 'اوزار، آلہ' },
  { ca: 'observat', es: 'observado (lo que has visto de verdad)', ar: 'مُلاحَظ (ما رأيته فعلًا)', ur: 'مشاہدہ شدہ (جو واقعی دیکھا)' },
  { ca: 'esperat', es: 'esperado (lo que predecías)', ar: 'متوقَّع (ما تنبّأت به)', ur: 'متوقع (جس کی پیش گوئی کی)' },
  { ca: 'indici', es: 'indicio (pista, aún no es prueba)', ar: 'مؤشر (قرينة، ليست دليلًا بعد)', ur: 'اشارہ (ابھی ثبوت نہیں)' },
  { ca: 'dilema', es: 'dilema (hay que elegir y ninguna opción es fácil)', ar: 'معضلة (خيار صعب بين بديلين)', ur: 'مخمصہ (دونوں راستے مشکل)' },
  { ca: 'bioètic', es: 'bioético (qué está bien o mal hacer con seres vivos)', ar: 'أخلاقي حيوي (ما يجوز فعله بالكائنات الحية)', ur: 'حیاتی اخلاقیات (جانداروں کے ساتھ کیا درست ہے)' },
  { ca: 'sociocientífica', es: 'sociocientífica (la ciencia sola no decide: hay valores)', ar: 'علمية اجتماعية (العلم وحده لا يقرّر: هناك قيم)', ur: 'سماجی-سائنسی (صرف سائنس فیصلہ نہیں کرتی: اقدار بھی ہیں)' },
  { ca: 'tecnofília', es: 'tecnofilia (creer que la tecnología siempre es buena)', ar: 'حبّ مفرط للتقنية (اعتقاد أنها دائمًا خير)', ur: 'ٹیکنالوجی کو ہمیشہ اچھا سمجھنا' },
  { ca: 'tecnofòbia', es: 'tecnofobia (miedo a la tecnología)', ar: 'رهاب التقنية', ur: 'ٹیکنالوجی سے خوف' },
  { ca: 'decisió', es: 'decisión', ar: 'قرار', ur: 'فیصلہ' },
  { ca: 'decidir', es: 'decidir', ar: 'يقرّر', ur: 'فیصلہ کرنا' },
  { ca: 'col·lectiva', es: 'colectiva (de todo el grupo)', ar: 'جماعية (للمجموعة كلها)', ur: 'اجتماعی (پورے گروپ کی)' },
  { ca: 'col·lectiu', es: 'colectivo (de todo el grupo)', ar: 'جماعي', ur: 'اجتماعی' },
  { ca: 'crispr', es: 'CRISPR (técnica para editar el ADN)', ar: 'كريسبر (تقنية لتعديل الحمض النووي)', ur: 'کرسپر (ڈی این اے میں ترمیم کی تکنیک)' },
  { ca: 'editar', es: 'editar (cambiar a propósito)', ar: 'يعدّل (يغيّر عن قصد)', ur: 'ترمیم کرنا (جان بوجھ کر بدلنا)' },
  // Verbs freqüents en la forma en què surten al text
  { ca: 'atura', es: 'para, detiene', ar: 'يوقف', ur: 'روک دیتا ہے' },
  { ca: 'aturar', es: 'parar, detener', ar: 'يوقف', ur: 'روکنا' },
  { ca: 'aturen', es: 'paran, detienen', ar: 'يوقفون', ur: 'روک دیتے ہیں' },
  { ca: 'salta', es: 'salta (se lo salta, no aparece en esa generación)', ar: 'يتخطّى (لا يظهر في ذلك الجيل)', ur: 'چھوڑ دیتا ہے، اُس نسل میں ظاہر نہیں ہوتا' },
  { ca: 'saltes', es: 'saltos: solo unos pocos valores separados, sin intermedios', ar: 'قفزات: قيم منفصلة قليلة بلا قيم وسطى', ur: 'چھلانگیں: چند الگ الگ قدریں، درمیانی نہیں' },
  { ca: 'puja', es: 'sube', ar: 'يرتفع', ur: 'اوپر جاتا ہے' },
  { ca: 'baixa', es: 'baja', ar: 'ينخفض', ur: 'نیچے جاتا ہے' },
  { ca: 'xoquen', es: 'chocan', ar: 'تصطدم', ur: 'ٹکراتی ہیں' },
  { ca: 'llisquen', es: 'se deslizan (una al lado de la otra)', ar: 'تنزلق (إحداهما بجانب الأخرى)', ur: 'ایک دوسرے کے ساتھ سرکتی ہیں' },
  { ca: 'enfonsa', es: 'hunde, se hunde', ar: 'يغوص / ينغمر', ur: 'ڈوبتا ہے، دھنستا ہے' },
  { ca: 'separen', es: 'se separan (se alejan una de otra)', ar: 'تتباعد، ينفصل بعضها عن بعض', ur: 'ایک دوسرے سے الگ ہو جاتی ہیں' },
  { ca: 'encaixa', es: 'encaja (se ajusta bien)', ar: 'يتلاءم (ينطبق تمامًا)', ur: 'ٹھیک بیٹھتا ہے' },
  { ca: 'transmet', es: 'transmite (pasa a otro)', ar: 'ينقل (يمرّره لغيره)', ur: 'منتقل کرتا ہے' },
  { ca: 'hereta', es: 'hereda', ar: 'يرث', ur: 'وراثت میں پاتا ہے' },
  { ca: 'sobreviure', es: 'sobrevivir', ar: 'ينجو، يبقى حيًّا', ur: 'زندہ بچنا' },
  { ca: 'desapareixen', es: 'desaparecen', ar: 'تختفي', ur: 'غائب ہو جاتے ہیں' },
  { ca: 'refreda', es: 'enfría, se enfría', ar: 'يبرد', ur: 'ٹھنڈا ہوتا ہے' },
  { ca: 'expandeix', es: 'expande, se hace más grande', ar: 'يتمدّد، يكبر', ur: 'پھیلتا ہے' },
  { ca: 'copia', es: 'copia', ar: 'ينسخ', ur: 'نقل کرتا ہے' },
  { ca: 'copiar', es: 'copiar', ar: 'ينسخ', ur: 'نقل کرنا' },
  { ca: 'divideix', es: 'divide, se divide', ar: 'ينقسم', ur: 'تقسیم ہوتا ہے' },
  { ca: 'dividir', es: 'dividir', ar: 'يقسّم', ur: 'تقسیم کرنا' },
  { ca: 'canviar', es: 'cambiar', ar: 'يغيّر', ur: 'بدلنا' },
  { ca: 'canvien', es: 'cambian', ar: 'تتغيّر', ur: 'بدلتے ہیں' },
  { ca: 'canviat', es: 'cambiado', ar: 'تغيّر / مُغيَّر', ur: 'بدلا ہوا' },
  { ca: 'corregeix', es: 'corrige', ar: 'يصحّح', ur: 'درست کرتا ہے' },
  { ca: 'corregir', es: 'corregir', ar: 'يصحّح', ur: 'درست کرنا' },
  { ca: 'explora', es: 'explora (busca sin saber aún qué encontrará)', ar: 'يستكشف (يبحث دون أن يعرف ماذا سيجد)', ur: 'کھوج لگاتا ہے' },
  { ca: 'explorar', es: 'explorar', ar: 'يستكشف', ur: 'کھوج لگانا' },
  { ca: 'reconèixer', es: 'reconocer (identificar qué es)', ar: 'يتعرّف على (يحدّد ما هو)', ur: 'پہچاننا' },
  { ca: 'respondre', es: 'responder, contestar', ar: 'يجيب', ur: 'جواب دینا' },
  { ca: 'resoldre', es: 'resolver', ar: 'يحلّ', ur: 'حل کرنا' },
  { ca: 'revisa', es: 'revisa (mira otra vez para comprobar)', ar: 'يراجع (ينظر مرة أخرى للتأكد)', ur: 'دوبارہ جانچتا ہے' },
  { ca: 'talla', es: 'corta', ar: 'يقطع', ur: 'کاٹتا ہے' },
  { ca: 'tallar', es: 'cortar', ar: 'يقطع', ur: 'کاٹنا' },
  { ca: 'trenca', es: 'rompe', ar: 'يكسر', ur: 'توڑتا ہے' },
  { ca: 'tapar', es: 'tapar, cubrir', ar: 'يغطّي', ur: 'ڈھانپنا' },
  { ca: 'triar', es: 'elegir, escoger', ar: 'يختار', ur: 'چننا' },
  { ca: 'predir', es: 'predecir (decir qué pasará antes de que pase)', ar: 'يتنبّأ (يقول ماذا سيحدث قبل حدوثه)', ur: 'پیش گوئی کرنا' },
  { ca: 'aplicar', es: 'aplicar (usar lo aprendido en un caso nuevo)', ar: 'يطبّق (يستعمل ما تعلّمه في حالة جديدة)', ur: 'لاگو کرنا (نئی صورت میں استعمال)' },
  { ca: 'avaluar', es: 'evaluar (decidir cómo de bueno es)', ar: 'يقيّم', ur: 'جانچنا، درجہ دینا' },
  { ca: 'classificar', es: 'clasificar (poner cada cosa en su grupo)', ar: 'يصنّف (يضع كل شيء في مجموعته)', ur: 'درجہ بندی کرنا' },

  // ── C) Català general dins dels trams ressaltats ─────────
  // Sense aquestes, una frase clau sencera es queda sense cap tooltip.
  { ca: 'encara', es: 'todavía, aún', ar: 'ما زال، بعدُ', ur: 'ابھی تک' },
  { ca: 'prou', es: 'suficiente, bastante', ar: 'كافٍ', ur: 'کافی' },
  { ca: 'gairebé', es: 'casi', ar: 'تقريبًا', ur: 'تقریباً' },
  { ca: 'només', es: 'solo, solamente', ar: 'فقط', ur: 'صرف' },
  { ca: 'sempre', es: 'siempre', ar: 'دائمًا', ur: 'ہمیشہ' },
  { ca: 'mai', es: 'nunca', ar: 'أبدًا', ur: 'کبھی نہیں' },
  { ca: 'abans', es: 'antes', ar: 'قبل', ur: 'پہلے' },
  { ca: 'després', es: 'después', ar: 'بعد', ur: 'بعد میں' },
  { ca: 'sota', es: 'debajo de', ar: 'تحت', ur: 'نیچے' },
  { ca: 'dins', es: 'dentro de', ar: 'داخل', ur: 'اندر' },
  { ca: 'entre', es: 'entre', ar: 'بين', ur: 'درمیان' },
  { ca: 'enrere', es: 'hacia atrás', ar: 'إلى الوراء', ur: 'پیچھے کی طرف' },
  { ca: 'endins', es: 'hacia dentro', ar: 'إلى الداخل', ur: 'اندر کی طرف' },
  { ca: 'avall', es: 'hacia abajo', ar: 'إلى الأسفل', ur: 'نیچے کی طرف' },
  { ca: 'lluny', es: 'lejos', ar: 'بعيد', ur: 'دور' },
  { ca: 'prop', es: 'cerca', ar: 'قريب', ur: 'قریب' },
  { ca: 'menys', es: 'menos', ar: 'أقلّ', ur: 'کم' },
  { ca: 'sencer', es: 'entero, completo', ar: 'كامل', ur: 'مکمل، سالم' },
  { ca: 'sencers', es: 'enteros, completos', ar: 'كاملة (غير منقوصة)', ur: 'مکمل، سالم' },
  { ca: 'complet', es: 'completo', ar: 'كامل', ur: 'مکمل' },
  { ca: 'normal', es: 'normal (lo habitual)', ar: 'طبيعي (المعتاد)', ur: 'معمول کے مطابق' },
  { ca: 'jove', es: 'joven (más reciente)', ar: 'حديث (أقلّ قِدَمًا)', ur: 'کم عمر، زیادہ حالیہ' },
  { ca: 'antiga', es: 'antigua (más vieja)', ar: 'قديمة', ur: 'قدیم' },
  { ca: 'recent', es: 'reciente (de hace poco)', ar: 'حديث (منذ وقت قصير)', ur: 'حالیہ' },
  { ca: 'igual', es: 'igual', ar: 'مساوٍ، نفس الشيء', ur: 'برابر، ایک جیسا' },
  { ca: 'diferent', es: 'diferente, distinto', ar: 'مختلف', ur: 'مختلف' },
  { ca: 'alt', es: 'alto (mucha cantidad)', ar: 'مرتفع (كمية كبيرة)', ur: 'زیادہ، بلند' },
  { ca: 'baix', es: 'bajo (poca cantidad)', ar: 'منخفض (كمية قليلة)', ur: 'کم، نیچا' },
  { ca: 'sola', es: 'sola, única', ar: 'وحيدة، واحدة فقط', ur: 'اکیلی، صرف ایک' },
  { ca: 'única', es: 'única', ar: 'وحيدة، فريدة', ur: 'واحد، منفرد' },
  { ca: 'mateixa', es: 'misma', ar: 'نفسها', ur: 'وہی' },
  { ca: 'possible', es: 'posible', ar: 'ممكن', ur: 'ممکن' },
  { ca: 'raó', es: 'razón, motivo', ar: 'سبب', ur: 'وجہ' },
  { ca: 'problema', es: 'problema', ar: 'مشكلة', ur: 'مسئلہ' },
  { ca: 'situació', es: 'situación', ar: 'وضع، حالة', ur: 'صورتِ حال' },
  { ca: 'obstacle', es: 'obstáculo (dificultad a superar)', ar: 'عائق (صعوبة يجب تجاوزها)', ur: 'رکاوٹ' },
  { ca: 'origen', es: 'origen (de dónde viene)', ar: 'أصل (من أين جاء)', ur: 'اصل، ابتدا' },
  { ca: 'inici', es: 'inicio, principio', ar: 'البداية', ur: 'آغاز' },
  { ca: 'nom', es: 'nombre', ar: 'اسم', ur: 'نام' },
  { ca: 'nombre', es: 'número, cantidad', ar: 'عدد', ur: 'تعداد' },
  { ca: 'paraula', es: 'palabra', ar: 'كلمة', ur: 'لفظ' },
  { ca: 'majúscula', es: 'mayúscula (A, B, C)', ar: 'حرف كبير (A, B, C)', ur: 'بڑا حرف (A, B, C)' },
  { ca: 'minúscula', es: 'minúscula (a, b, c)', ar: 'حرف صغير (a, b, c)', ur: 'چھوٹا حرف (a, b, c)' },
  { ca: 'cursiva', es: 'cursiva (letra inclinada)', ar: 'خط مائل', ur: 'ترچھا حرف' },
  { ca: 'informe', es: 'informe (texto donde explicas lo que has hecho)', ar: 'تقرير (نصّ تشرح فيه ما فعلت)', ur: 'رپورٹ' },
  { ca: 'targeta', es: 'tarjeta', ar: 'بطاقة', ur: 'کارڈ' },
  { ca: 'equip', es: 'equipo (grupo de trabajo)', ar: 'فريق', ur: 'ٹیم' },
  { ca: 'parella', es: 'pareja: dos que van juntos (personas, o bases del ADN)', ar: 'زوج: اثنان معًا (شخصان، أو قاعدتان في الحمض النووي)', ur: 'جوڑا: دو جو ساتھ ہوں (افراد، یا ڈی این اے کے بیس)' },
  { ca: 'tasca', es: 'tarea', ar: 'مهمّة', ur: 'کام، ٹاسک' },
  { ca: 'guia', es: 'guía (lo que te orienta)', ar: 'دليل إرشادي', ur: 'رہنما' },
  { ca: 'espai', es: 'espacio (sitio; también el universo)', ar: 'حيّز (مكان؛ وأيضًا الفضاء)', ur: 'جگہ؛ خلا' },
  { ca: 'lloc', es: 'lugar, sitio', ar: 'مكان', ur: 'جگہ' },

  // ── D) Segona passada sobre el que encara quedava ───────
  // Noms i adjectius que apareixen dins de trams ressaltats
  { ca: 'selecció', es: 'selección (quién pasa el filtro y quién no)', ar: 'انتقاء (من يجتاز التصفية ومن لا)', ur: 'چناؤ (کون بچتا ہے اور کون نہیں)' },
  { ca: 'cicle', es: 'ciclo (vuelve al punto de partida)', ar: 'دورة (تعود إلى نقطة البداية)', ur: 'چکر (شروع پر واپس آتا ہے)' },
  { ca: 'codi', es: 'código (reglas para leer un mensaje)', ar: 'شيفرة (قواعد لقراءة رسالة)', ur: 'کوڈ (پیغام پڑھنے کے اصول)' },
  { ca: 'clau', es: 'clave: lo más importante; también una clave para clasificar (y una llave)', ar: 'الأهمّ، الأساسي؛ وأيضًا مفتاح تصنيف (أو مفتاح باب)', ur: 'کلیدی، سب سے اہم؛ نیز درجہ بندی کی کلید (اور چابی)' },
  { ca: 'forma', es: 'forma (cómo es por fuera)', ar: 'شكل', ur: 'شکل' },
  { ca: 'fons', es: 'fondo (la parte de abajo o de detrás); «de fons» = de base, lo que hay por debajo', ar: 'القاع أو الخلفية؛ «de fons» أي الأساسي الكامن وراء الأمر', ur: 'تہہ یا پس منظر؛ «de fons» یعنی بنیادی، جو پیچھے چھپا ہے' },
  { ca: 'natura', es: 'naturaleza', ar: 'الطبيعة', ur: 'قدرت، فطرت' },
  { ca: 'valor', es: 'valor (lo que consideras importante o correcto)', ar: 'قيمة (ما تعتبره مهمًّا أو صوابًا)', ur: 'قدر (جسے آپ اہم یا درست سمجھتے ہیں)' },
  { ca: 'vida', es: 'vida', ar: 'الحياة', ur: 'زندگی' },
  { ca: 'història', es: 'historia (lo que ha ido pasando)', ar: 'التاريخ (ما جرى عبر الزمن)', ur: 'تاریخ (جو گزرا)' },
  { ca: 'sistema', es: 'sistema (conjunto de partes que trabajan juntas)', ar: 'نظام (أجزاء تعمل معًا)', ur: 'نظام (مل کر کام کرنے والے حصے)' },
  { ca: 'tipus', es: 'tipo, clase', ar: 'نوع', ur: 'قسم' },
  { ca: 'tècnica', es: 'técnica (manera de hacerlo)', ar: 'تقنية (طريقة العمل)', ur: 'تکنیک (کرنے کا طریقہ)' },
  { ca: 'recerca', es: 'investigación', ar: 'بحث علمي', ur: 'تحقیق' },
  { ca: 'referència', es: 'referencia (con qué lo comparas)', ar: 'مرجع (ما تقارن به)', ur: 'حوالہ (جس سے موازنہ کریں)' },
  { ca: 'document', es: 'documento', ar: 'وثيقة', ur: 'دستاویز' },
  { ca: 'arxiu', es: 'archivo (donde se guarda)', ar: 'أرشيف (حيث يُحفظ)', ur: 'ریکارڈ، محفوظ خانہ' },
  { ca: 'nota', es: 'nota (apunte breve)', ar: 'ملاحظة قصيرة', ur: 'مختصر نوٹ' },
  { ca: 'missatge', es: 'mensaje', ar: 'رسالة', ur: 'پیغام' },
  { ca: 'escena', es: 'escena: un momento de la historia; también un trozo de vídeo', ar: 'مشهد: لحظة من القصة؛ وأيضًا جزء من فيديو', ur: 'منظر: کہانی کا ایک لمحہ؛ نیز ویڈیو کا حصہ' },
  { ca: 'fenomen', es: 'fenómeno (algo que pasa y se puede observar)', ar: 'ظاهرة (شيء يحدث ويمكن ملاحظته)', ur: 'مظہر (جو ہوتا ہے اور دیکھا جا سکتا ہے)' },
  { ca: 'compartiment', es: 'compartimento (espacio cerrado y separado)', ar: 'حجيرة (حيّز مغلق منفصل)', ur: 'خانہ (بند اور الگ جگہ)' },
  { ca: 'combinació', es: 'combinación (mezcla de piezas)', ar: 'توليفة (مزيج من العناصر)', ur: 'امتزاج' },
  { ca: 'convergència', es: 'convergencia (se acercan y chocan)', ar: 'تقارب (تقترب وتصطدم)', ur: 'قربت (قریب آ کر ٹکراؤ)' },
  { ca: 'divergència', es: 'divergencia (se separan)', ar: 'تباعد (تبتعد عن بعضها)', ur: 'دوری (الگ ہونا)' },
  { ca: 'uniformitat', es: 'uniformidad: todos iguales (1ª ley de Mendel); en geología, que las leyes naturales no han cambiado', ar: 'تجانس: الجميع متشابهون (قانون مندل الأول)؛ وفي الجيولوجيا: أن قوانين الطبيعة لم تتغيّر', ur: 'یکسانیت: سب ایک جیسے (مینڈل کا پہلا قانون)؛ ارضیات میں: قدرتی قوانین نہیں بدلے' },
  { ca: 'continuïtat', es: 'continuidad (sigue sin cortarse)', ar: 'استمرارية (يستمر دون انقطاع)', ur: 'تسلسل (بغیر رکے جاری)' },
  { ca: 'interpretació', es: 'interpretación (qué significa lo que ves)', ar: 'تفسير (ماذا يعني ما تراه)', ur: 'تعبیر (جو دیکھا اس کا مطلب)' },
  { ca: 'explosió', es: 'explosión; en «Big Bang» no es una explosión dentro del espacio, es el espacio expandiéndose', ar: 'انفجار؛ وفي «الانفجار العظيم» ليس انفجارًا داخل الفضاء بل تمدّد الفضاء نفسه', ur: 'دھماکہ؛ ”بگ بینگ“ میں خلا کے اندر دھماکہ نہیں، خود خلا کا پھیلنا' },
  { ca: 'àtom', es: 'átomo', ar: 'ذرّة', ur: 'ایٹم' },
  { ca: 'gas', es: 'gas', ar: 'غاز', ur: 'گیس' },
  { ca: 'planeta', es: 'planeta', ar: 'كوكب', ur: 'سیارہ' },
  { ca: 'solar', es: 'solar (del Sol)', ar: 'شمسي (يتعلق بالشمس)', ur: 'شمسی (سورج کا)' },
  { ca: 'nuclear', es: 'nuclear (del núcleo del átomo)', ar: 'نووي (يتعلق بنواة الذرة)', ur: 'جوہری (ایٹم کے مرکزے کا)' },
  { ca: 'oceànic', es: 'oceánico (del océano)', ar: 'محيطي', ur: 'سمندری' },
  { ca: 'ona', es: 'onda', ar: 'موجة', ur: 'لہر' },
  { ca: 'llamp', es: 'rayo (de tormenta)', ar: 'برق (صاعقة)', ur: 'بجلی (آسمانی)' },
  { ca: 'llacuna', es: 'laguna (agua poco profunda; también un vacío)', ar: 'بحيرة ضحلة؛ وأيضًا فجوة', ur: 'اتھلی جھیل؛ نیز خلا' },
  { ca: 'terrassa', es: 'terraza (escalón de terreno)', ar: 'مصطبة (درجة أرضية)', ur: 'سیڑھی نما زمین' },
  { ca: 'malla', es: 'malla, red', ar: 'شبكة', ur: 'جالی' },
  { ca: 'corda', es: 'cuerda', ar: 'حبل', ur: 'رسی' },
  { ca: 'campana', es: 'campana (forma de la curva)', ar: 'جرس (شكل المنحنى)', ur: 'گھنٹی (منحنی کی شکل)' },
  { ca: 'bloc', es: 'bloque', ar: 'كتلة', ur: 'بلاک، ٹکڑا' },
  { ca: 'base', es: 'base (A, T, G o C del ADN; o la parte de abajo)', ar: 'قاعدة (A, T, G, C في الحمض النووي؛ أو الجزء السفلي)', ur: 'بیس (ڈی این اے کا اے/ٹی/جی/سی؛ یا نچلا حصہ)' },
  { ca: 'node', es: 'nodo (punto donde se separa una rama)', ar: 'عقدة (نقطة تفرّع)', ur: 'گرہ (شاخ الگ ہونے کا مقام)' },
  { ca: 'tall', es: 'corte (cortar algo); en geología, sección vertical del terreno', ar: 'قَطْع أو جُرح؛ وفي الجيولوجيا: مقطع رأسي للأرض', ur: 'کٹ، چیرا؛ ارضیات میں: زمین کا عمودی مقطع' },
  { ca: 'mapa', es: 'mapa', ar: 'خريطة', ur: 'نقشہ' },
  { ca: 'foto', es: 'foto', ar: 'صورة', ur: 'تصویر' },
  { ca: 'soroll', es: 'ruido (variación que molesta la medida)', ar: 'ضجيج (تشويش يعكّر القياس)', ur: 'شور (پیمائش میں خلل)' },
  { ca: 'seny', es: 'sentido común', ar: 'الحسّ السليم', ur: 'عام فہم' },
  { ca: 'massa', es: 'masa (cantidad de materia); también "demasiado"', ar: 'كتلة (كمية المادة)؛ وأيضًا «أكثر من اللازم»', ur: 'کمیت (مادے کی مقدار)؛ نیز ”حد سے زیادہ“' },
  // Adjectius
  { ca: 'abundant', es: 'abundante (hay mucho)', ar: 'وفير (يوجد بكثرة)', ur: 'وافر (بہت زیادہ)' },
  { ca: 'concret', es: 'concreto (uno en particular, no en general)', ar: 'محدَّد (واحد بعينه)', ur: 'مخصوص (کوئی ایک خاص)' },
  { ca: 'comú', es: 'común (compartido por varios)', ar: 'مشترك', ur: 'مشترکہ' },
  { ca: 'enorme', es: 'enorme (muy grande)', ar: 'هائل (كبير جدًا)', ur: 'بہت بڑا' },
  { ca: 'estret', es: 'estrecho (poco ancho)', ar: 'ضيّق', ur: 'تنگ' },
  { ca: 'estreta', es: 'estrecha', ar: 'ضيّقة', ur: 'تنگ' },
  { ca: 'fort', es: 'fuerte', ar: 'قويّ', ur: 'مضبوط، شدید' },
  { ca: 'força', es: 'fuerza; también "bastante"', ar: 'قوة؛ وأيضًا «إلى حدّ كبير»', ur: 'قوت؛ نیز ”کافی حد تک“' },
  { ca: 'líquid', es: 'líquido', ar: 'سائل', ur: 'مائع' },
  { ca: 'líquida', es: 'líquida', ar: 'سائلة', ur: 'مائع' },
  { ca: 'majoritària', es: 'mayoritaria (pasa a ser la más frecuente)', ar: 'الأكثر شيوعًا (صارت هي الغالبة)', ur: 'سب سے عام (غالب ہو گئی)' },
  { ca: 'malalta', es: 'enferma', ar: 'مريضة', ur: 'بیمار' },
  { ca: 'sana', es: 'sana (no enferma)', ar: 'سليمة (غير مريضة)', ur: 'صحت مند' },
  { ca: 'ple', es: 'lleno', ar: 'ممتلئ', ur: 'بھرا ہوا' },
  { ca: 'present', es: 'presente (ahora; o que está)', ar: 'الحاضر (الآن؛ أو موجود)', ur: 'حال (اب؛ یا موجود)' },
  { ca: 'real', es: 'real (que existe de verdad)', ar: 'حقيقي (موجود فعلًا)', ur: 'حقیقی' },
  { ca: 'humà', es: 'humano', ar: 'بشري', ur: 'انسانی' },
  { ca: 'idèntic', es: 'idéntico (exactamente igual)', ar: 'مطابق تمامًا', ur: 'بالکل ایک جیسا' },
  { ca: 'independent', es: 'independiente (no depende del otro)', ar: 'مستقلّ (لا يعتمد على غيره)', ur: 'خودمختار (دوسرے پر منحصر نہیں)' },
  { ca: 'inestable', es: 'inestable (cambia o se rompe fácilmente)', ar: 'غير مستقرّ (يتغيّر أو ينهار بسهولة)', ur: 'غیر مستحکم' },
  { ca: 'intens', es: 'intenso (muy fuerte)', ar: 'شديد (قويّ جدًا)', ur: 'شدید' },
  { ca: 'intermedi', es: 'intermedio (en medio de los dos)', ar: 'وسيط (بين الاثنين)', ur: 'درمیانی' },
  { ca: 'interna', es: 'interna (de dentro)', ar: 'داخلية', ur: 'اندرونی' },
  { ca: 'inclinat', es: 'inclinado (torcido, no horizontal)', ar: 'مائل (غير أفقي)', ur: 'ترچھا (افقی نہیں)' },
  { ca: 'horitzontal', es: 'horizontal (plano, como el suelo)', ar: 'أفقي (مستوٍ كالأرض)', ur: 'افقی (زمین کی طرح سیدھا)' },
  { ca: 'vertical', es: 'vertical (de arriba abajo)', ar: 'عمودي (من أعلى إلى أسفل)', ur: 'عمودی' },
  { ca: 'visible', es: 'visible (se puede ver)', ar: 'مرئي (يمكن رؤيته)', ur: 'قابلِ دید' },
  { ca: 'aïllada', es: 'aislada (separada de las demás)', ar: 'معزولة (منفصلة عن غيرها)', ur: 'الگ تھلگ' },
  { ca: 'emparentada', es: 'emparentada (de la misma familia)', ar: 'ذات صلة قرابة (من العائلة نفسها)', ur: 'رشتہ دار (ایک ہی خاندان کی)' },
  { ca: 'canviant', es: 'cambiante (no siempre igual)', ar: 'متغيّر (ليس ثابتًا)', ur: 'بدلتا رہنے والا' },
  { ca: 'congelada', es: 'congelada (parada en un instante)', ar: 'مجمَّدة (متوقفة في لحظة)', ur: 'منجمد (ایک لمحے میں رکی ہوئی)' },
  { ca: 'dirigit', es: 'dirigido (a propósito, hacia un punto)', ar: 'موجَّه (عن قصد نحو هدف)', ur: 'ہدف کی طرف، جان بوجھ کر' },
  { ca: 'dissolt', es: 'disuelto (mezclado en el líquido)', ar: 'مذاب (ممتزج في السائل)', ur: 'حل شدہ (مائع میں گھلا ہوا)' },
  { ca: 'explícit', es: 'explícito (dicho claramente)', ar: 'صريح (مذكور بوضوح)', ur: 'واضح طور پر کہا گیا' },
  { ca: 'acumulat', es: 'acumulado (se ha ido juntando)', ar: 'متراكم (تجمّع شيئًا فشيئًا)', ur: 'جمع ہوا ہوا' },
  { ca: 'addicional', es: 'adicional (una más)', ar: 'إضافي', ur: 'اضافی' },
  { ca: 'afectat', es: 'afectado (le pasa a él)', ar: 'مصاب / متأثّر', ur: 'متاثرہ' },
  { ca: 'sobtat', es: 'repentino (pasa de golpe)', ar: 'مفاجئ', ur: 'اچانک' },
  { ca: 'geològic', es: 'geológico (de las rocas y la Tierra)', ar: 'جيولوجي (يتعلق بالصخور والأرض)', ur: 'ارضیاتی' },
  { ca: 'genètica', es: 'genética (de los genes)', ar: 'وراثية (تتعلق بالجينات)', ur: 'جینیاتی' },
  // Verbs i connectors que queden
  { ca: 'pot', es: 'puede; también un bote o tarro', ar: 'يستطيع، يمكن؛ وأيضًا وعاء أو مرطبان', ur: 'کر سکتا ہے؛ نیز مرتبان/ڈبہ' },
  { ca: 'toca', es: 'toca (cuando corresponde hacerlo)', ar: 'يحين دوره (عندما يجب)', ur: 'جب کرنا چاہیے' },
  { ca: 'falta', es: 'falta (no está, se echa en falta)', ar: 'ينقص (غير موجود)', ur: 'کمی ہے، موجود نہیں' },
  { ca: 'fixa', es: 'fíjate (mira con atención); o fija (que no se mueve)', ar: 'انتبه (انظر بتمعّن)؛ أو ثابتة (لا تتحرّك)', ur: 'غور سے دیکھو؛ یا ثابت (جو ہلتا نہیں)' },
  { ca: 'millora', es: 'mejora', ar: 'تحسّن', ur: 'بہتری' },
  { ca: 'millorar', es: 'mejorar', ar: 'يحسّن', ur: 'بہتر بنانا' },
  { ca: 'conèixer', es: 'conocer', ar: 'يعرف', ur: 'جاننا' },
  { ca: 'creure', es: 'creer', ar: 'يعتقد، يصدّق', ur: 'ماننا، یقین کرنا' },
  { ca: 'llegir', es: 'leer', ar: 'يقرأ', ur: 'پڑھنا' },
  { ca: 'manté', es: 'mantiene (sigue igual)', ar: 'يحافظ (يبقى كما هو)', ur: 'برقرار رکھتا ہے' },
  { ca: 'mouen', es: 'mueven, se mueven', ar: 'تتحرّك', ur: 'حرکت کرتی ہیں' },
  { ca: 'creixen', es: 'crecen', ar: 'تنمو', ur: 'بڑھتے ہیں' },
  { ca: 'neixen', es: 'nacen', ar: 'تولد', ur: 'پیدا ہوتے ہیں' },
  { ca: 'néixer', es: 'nacer', ar: 'يولد', ur: 'پیدا ہونا' },
  { ca: 'aparèixer', es: 'aparecer (empezar a estar)', ar: 'يظهر (يبدأ بالوجود)', ur: 'ظاہر ہونا' },
  { ca: 'perd', es: 'pierde', ar: 'يفقد', ur: 'کھو دیتا ہے' },
  { ca: 'dura', es: 'dura: cuánto tiempo tarda; o dura = sólida, no blanda', ar: 'يدوم (كم من الوقت)؛ أو صلبة قاسية (غير طريّة)', ur: 'دورانیہ (کتنا وقت)؛ یا سخت (نرم نہیں)' },
  { ca: 'funciona', es: 'funciona', ar: 'يعمل، ينجح', ur: 'کام کرتا ہے' },
  { ca: 'promet', es: 'promete (dice que dará)', ar: 'يَعِد (يقول إنه سيعطي)', ur: 'وعدہ کرتا ہے' },
  { ca: 'signa', es: 'firma (quién lo escribe y da la cara)', ar: 'يوقّع (من يكتبه ويتحمّل مسؤوليته)', ur: 'دستخط کرتا ہے (کون ذمہ دار ہے)' },
  { ca: 'simula', es: 'simula (imita para poder estudiarlo)', ar: 'يحاكي (يقلّد لدراسته)', ur: 'نقل کرتا ہے (مطالعے کے لیے)' },
  { ca: 'notar', es: 'notar (darse cuenta)', ar: 'يلاحظ (ينتبه)', ur: 'محسوس کرنا' },
  { ca: 'descriure', es: 'describir (decir cómo es)', ar: 'يصف (يقول كيف هو)', ur: 'بیان کرنا' },
  { ca: 'explicar', es: 'explicar (decir por qué)', ar: 'يفسّر (يقول لماذا)', ur: 'وضاحت کرنا (کیوں)' },
  { ca: 'comunicar', es: 'comunicar (contarlo a los demás)', ar: 'ينقل للآخرين', ur: 'دوسروں کو بتانا' },
  { ca: 'comprovar', es: 'comprobar (mirar si es verdad)', ar: 'يتحقّق (ينظر هل هو صحيح)', ur: 'جانچنا (سچ ہے یا نہیں)' },
  { ca: 'decideix', es: 'decide', ar: 'يقرّر', ur: 'فیصلہ کرتا ہے' },
  { ca: 'determina', es: 'determina (es lo que lo decide)', ar: 'يحدّد (هو ما يقرّره)', ur: 'طے کرتا ہے' },
  { ca: 'domina', es: 'domina (uno tapa al otro)', ar: 'يسود (يغطّي الآخر)', ur: 'غالب آتا ہے' },
  { ca: 'influeix', es: 'influye (afecta un poco)', ar: 'يؤثّر', ur: 'اثر ڈالتا ہے' },
  { ca: 'permeten', es: 'permiten (dejan hacer)', ar: 'تسمح', ur: 'اجازت دیتے ہیں' },
  { ca: 'prohibeixen', es: 'prohíben (no dejan)', ar: 'تمنع', ur: 'منع کرتے ہیں' },
  { ca: 'consentir', es: 'consentir (decir que sí sabiendo qué es)', ar: 'يوافق عن علم', ur: 'باخبر رضامندی دینا' },
  { ca: 'renoven', es: 'renuevan (fabrican células nuevas)', ar: 'تُجدِّد (تصنع خلايا جديدة)', ur: 'نئے خلیے بناتے ہیں' },
  { ca: 'resisteix', es: 'resiste (aguanta)', ar: 'يقاوم (يتحمّل)', ur: 'مزاحمت کرتا ہے، برداشت کرتا ہے' },
  { ca: 'transmeten', es: 'transmiten (pasan a otros)', ar: 'ينقلون', ur: 'منتقل کرتے ہیں' },
  { ca: 'trasllada', es: 'traslada (mueve el problema a otro sitio)', ar: 'ينقل (يزيح المشكلة إلى مكان آخر)', ur: 'مسئلہ کہیں اور منتقل کر دیتا ہے' },
  { ca: 'destrueix', es: 'destruye', ar: 'يدمّر', ur: 'تباہ کرتا ہے' },
  { ca: 'desforestar', es: 'deforestar (quitar el bosque)', ar: 'إزالة الغابات', ur: 'جنگل کاٹنا' },
  { ca: 'contradiu', es: 'contradice (dice lo contrario)', ar: 'يناقض (يقول العكس)', ur: 'تردید کرتا ہے' },
  { ca: 'reproduir', es: 'reproducir (repetirlo igual)', ar: 'يُعيد إنتاجه بنفس الطريقة', ur: 'ہو بہو دہرانا' },
  { ca: 'agrupen', es: 'agrupan (juntan por parecidos)', ar: 'تُجمَّع حسب التشابه', ur: 'مشابہت کے مطابق گروپ بناتے ہیں' },
  { ca: 'arrossega', es: 'arrastra (se lo lleva)', ar: 'يجرف (يحمله معه)', ur: 'بہا لے جاتا ہے' },
  { ca: 'aparella', es: 'empareja (une de dos en dos)', ar: 'يقرن (يجمع اثنين اثنين)', ur: 'جوڑا بناتا ہے' },
  { ca: 'apel·la', es: 'apela (se dirige a lo que quieres creer)', ar: 'يستميل (يخاطب ما تودّ تصديقه)', ur: 'اُس بات کو چھوتا ہے جو آپ ماننا چاہتے ہیں' },
  { ca: 'perquè', es: 'porque; por qué', ar: 'لأنّ؛ لماذا', ur: 'کیونکہ؛ کیوں' },
  { ca: 'alhora', es: 'a la vez, al mismo tiempo', ar: 'في الوقت نفسه', ur: 'ایک ہی وقت میں' },
  { ca: 'davant', es: 'delante de; ante', ar: 'أمام', ur: 'سامنے' },
  { ca: 'dalt', es: 'arriba', ar: 'أعلى', ur: 'اوپر' },
  { ca: 'just', es: 'justo, exactamente', ar: 'تمامًا، بالضبط', ur: 'بالکل، ٹھیک' },
  { ca: 'ben', es: 'bien (delante de un adjetivo: muy)', ar: 'جيدًا؛ (أمام صفة) جدًا', ur: 'اچھی طرح؛ (صفت سے پہلے) بہت' },
  { ca: 'ningú', es: 'nadie', ar: 'لا أحد', ur: 'کوئی نہیں' },
  { ca: 'zero', es: 'cero', ar: 'صفر', ur: 'صفر' },
  { ca: 'minut', es: 'minuto', ar: 'دقيقة', ur: 'منٹ' },
  { ca: 'dia', es: 'día', ar: 'يوم', ur: 'دن' },
  { ca: 'nit', es: 'noche', ar: 'ليل', ur: 'رات' },
  { ca: 'alba', es: 'amanecer', ar: 'الفجر', ur: 'صبح، طلوعِ آفتاب' },
  { ca: 'curs', es: 'curso (el año escolar)', ar: 'العام الدراسي', ur: 'تعلیمی سال' },
  { ca: 'classe', es: 'clase (el grupo o la sesión)', ar: 'الصف (المجموعة أو الحصة)', ur: 'کلاس (گروپ یا سبق)' },
  { ca: 'blanc', es: 'blanco', ar: 'أبيض', ur: 'سفید' },
  { ca: 'blanca', es: 'blanca', ar: 'بيضاء', ur: 'سفید' },
  { ca: 'vermell', es: 'rojo', ar: 'أحمر', ur: 'سرخ' },
  { ca: 'rosa', es: 'rosa (color)', ar: 'وردي (لون)', ur: 'گلابی' },
  { ca: 'color', es: 'color', ar: 'لون', ur: 'رنگ' },
  { ca: 'centre', es: 'centro (el medio)', ar: 'المركز (الوسط)', ur: 'مرکز (درمیان)' },
  { ca: 'radi', es: 'radio: hueso del antebrazo (con el cúbito); en geometría, del centro al borde', ar: 'الكعبرة: عظم الساعد (مع الزند)؛ وفي الهندسة: نصف القطر', ur: 'ریڈیس: بازو کی ہڈی (النا کے ساتھ)؛ ہندسے میں: رداس' },
  { ca: 'disc', es: 'disco (forma plana y redonda)', ar: 'قرص (شكل مسطّح مستدير)', ur: 'قرص (چپٹی گول شکل)' },
  { ca: 'punta', es: 'punta (el extremo)', ar: 'طرف، قمة', ur: 'نوک، سرا' },
  { ca: 'tirada', es: 'tirada (una vez que lanzas la moneda o el dado)', ar: 'رمية واحدة (للعملة أو النرد)', ur: 'ایک بار پھینکنا (سکہ یا پانسہ)' },
  { ca: 'de partida', es: 'de partida (inicial, del que se parte)', ar: 'الأصلية، التي ننطلق منها', ur: 'ابتدائی، جس سے شروع کرتے ہیں' },
  { ca: 'sortida', es: 'salida: resultado posible; o una excursión', ar: 'نتيجة ممكنة؛ أو خرجة ميدانية', ur: 'ممکنہ نتیجہ؛ یا فیلڈ ٹرپ' },

  // ── E) Formes verbals concretes que surten a les consignes ──
  // El matcher només sap desfer PLURALS, no conjugacions: per això es
  // donen d'alta les formes exactes que apareixen als enunciats.
  { ca: 'vols', es: 'quieres', ar: 'تريد', ur: 'آپ چاہتے ہیں' },
  { ca: 'voler', es: 'querer', ar: 'يريد', ur: 'چاہنا' },
  { ca: 'voluntat', es: 'voluntad (a propósito, porque se quiere)', ar: 'إرادة (عن قصد)', ur: 'ارادہ (جان بوجھ کر)' },
  { ca: 'corregeixin', es: 'que lo corrijan (otros)', ar: 'أن يصحّحه آخرون', ur: 'کہ دوسرے درست کریں' },
  { ca: 'sàpiga', es: 'que sepa', ar: 'أن يعرف', ur: 'کہ اسے معلوم ہو' },
  { ca: 'saps', es: 'sabes', ar: 'تعرف', ur: 'آپ جانتے ہیں' },
  { ca: 'sabem', es: 'sabemos', ar: 'نعرف', ur: 'ہم جانتے ہیں' },
  { ca: 'podem', es: 'podemos', ar: 'نستطيع', ur: 'ہم کر سکتے ہیں' },
  { ca: 'hauríem', es: 'deberíamos', ar: 'ينبغي لنا', ur: 'ہمیں چاہیے' },
  { ca: 'diguis', es: 'que digas', ar: 'أن تقول', ur: 'کہ آپ کہیں' },
  { ca: 'justifiquis', es: 'que justifiques (que des las razones)', ar: 'أن تبرّر (أن تذكر الأسباب)', ur: 'کہ آپ وجہ بتائیں' },
  { ca: 'dedueixes', es: 'deduces (sacas de las pistas)', ar: 'تستنتج (من القرائن)', ur: 'اخذ کرتے ہیں (شواہد سے)' },
  { ca: 'revisi', es: 'que revise', ar: 'أن يراجع', ur: 'کہ نظرثانی کرے' },
  { ca: 'mostrava', es: 'mostraba (enseñaba)', ar: 'كان يُظهر', ur: 'دکھاتا تھا' },
  { ca: 'necessitava', es: 'necesitaba', ar: 'كان يحتاج', ur: 'ضرورت تھی' },
  { ca: 'faltava', es: 'faltaba (no lo tenía)', ar: 'كان ينقصه', ur: 'اس کے پاس نہیں تھا' },
  { ca: 'desmentiria', es: 'desmentiría (demostraría que es falso)', ar: 'سيُكذّبها (يثبت أنها خاطئة)', ur: 'جھٹلا دیتا (غلط ثابت کرتا)' },
  { ca: 'doblaria', es: 'doblaría (se haría el doble)', ar: 'سيتضاعف', ur: 'دگنا ہو جاتا' },
  { ca: 'quadren', es: 'cuadran (encajan con lo esperado)', ar: 'تتوافق (تنسجم مع المتوقَّع)', ur: 'میل کھاتے ہیں' },
  { ca: 'amplifiquen', es: 'amplifican (hacen más grande el efecto)', ar: 'تضخّم (تكبّر الأثر)', ur: 'اثر بڑھا دیتے ہیں' },
  { ca: 'arruguen', es: 'arrugan (pliegan como un papel)', ar: 'تتجعّد (تنطوي كالورق)', ur: 'سلوٹیں ڈالتے ہیں' },
  { ca: 'emergir', es: 'emerger (aparecer del conjunto)', ar: 'ينبثق (يظهر من المجموع)', ur: 'ابھرنا (مجموعے سے ظاہر ہونا)' },
  { ca: 'correlacionar', es: 'correlacionar (emparejar dos columnas por lo que tienen igual)', ar: 'يربط عمودين بما يشتركان فيه', ur: 'دو کالموں کو مشترکہ چیز سے جوڑنا' },

  // ── F) Correccions de la revisió d'alumna nouvinguda (24/08) ──
  // Totes surten de mirar frases ressaltades reals i comprovar què li
  // sortiria a l'alumna. Les tres primeres eren errors greus: la paraula
  // resolia a una entrada EQUIVOCADA (no pas a cap).
  { ca: 'et bases', es: 'te basas (en qué te apoyas para decirlo)', ar: 'تستند إلى (على ماذا تعتمد في قولك)', ur: 'آپ کس چیز پر بھروسا کرتے ہیں' },
  { ca: 'què bases', es: 'en qué te apoyas', ar: 'على ماذا تستند', ur: 'آپ کس چیز پر بھروسا کرتے ہیں' },
  { ca: 'bases', es: 'bases: las letras A, T, G, C del ADN', ar: 'القواعد النيتروجينية (A, T, G, C) في الحمض النووي', ur: 'بیسز: ڈی این اے کے حروف A, T, G, C' },
  // ↑ sense aquesta entrada, «en què et bases» (la pregunta central de SA1,
  //   5 aparicions) queia per la regla del plural a `base` = base de l'ADN.
  { ca: 'queixals del seny', es: 'muelas del juicio', ar: 'ضروس العقل', ur: 'عقل داڑھ' },
  // ↑ `queixal` + `seny` per separat donaven «queixal del sentit comú».
  { ca: 'aturada', es: 'parada, detención', ar: 'توقّف', ur: 'رکاوٹ، ٹھہراؤ' },
  { ca: "codó d'aturada", es: 'codón de parada (la señal de STOP del mensaje)', ar: 'كودون التوقّف: إشارة «قف» في نهاية الرسالة', ur: 'اسٹاپ کوڈون (پیغام کے اختتام کا اشارہ)' },
  { ca: 'dic', es: 'digo (yo digo)', ar: 'أقول', ur: 'میں کہتا ہوں' },
  { ca: 'dic volcànic', es: 'dique (lengua de magma que atraviesa las capas)', ar: 'قاطع ناري (لسان من الصهارة يخترق الطبقات)', ur: 'ڈائک (تہوں کو چیرتا ہوا میگما)' },
  { ca: 'mateix', es: 'mismo', ar: 'نفسه', ur: 'وہی' },
  { ca: 'sol', es: 'solo, único; y también el Sol', ar: 'وحيد، واحد فقط؛ وأيضًا الشمس', ur: 'اکیلا، صرف ایک؛ نیز سورج' },
  { ca: 'anys', es: 'años', ar: 'سنوات', ur: 'سال' },
  { ca: 'any', es: 'año', ar: 'سنة', ur: 'سال' },
  { ca: 'avui', es: 'hoy', ar: 'اليوم', ur: 'آج' },
  { ca: 'junts', es: 'juntos', ar: 'معًا', ur: 'ایک ساتھ' },
  { ca: 'juntes', es: 'juntas', ar: 'معًا', ur: 'ایک ساتھ' },
  { ca: 'aixecar', es: 'levantar', ar: 'يرفع', ur: 'اٹھانا' },
  { ca: 'usa', es: 'usa (se utiliza)', ar: 'يُستعمَل', ur: 'استعمال ہوتا ہے' },
  { ca: 'primer', es: 'primero', ar: 'الأول', ur: 'پہلا' },
  { ca: 'més', es: 'más', ar: 'أكثر', ur: 'زیادہ' },
  { ca: 'tot', es: 'todo', ar: 'كلّ، الجميع', ur: 'سب، تمام' },
  { ca: 'totes', es: 'todas', ar: 'كلّهنّ، جميعها', ur: 'سب (مؤنث)' },
  { ca: 'dau', es: 'dado (para tirar)', ar: 'حجر نرد', ur: 'پانسہ' },
  { ca: 'daus', es: 'dados (para tirar)', ar: 'أحجار نرد', ur: 'پانسے' },
  { ca: 'corba', es: 'curva (la línea del gráfico)', ar: 'منحنى (خط الرسم البياني)', ur: 'منحنی (گراف کی لکیر)' },
  { ca: 'cadena', es: 'cadena (una de las dos hebras del ADN)', ar: 'سلسلة (أحد شريطَي الحمض النووي)', ur: 'زنجیر (ڈی این اے کی ایک لڑی)' },
  { ca: 'còpia', es: 'copia', ar: 'نسخة', ur: 'نقل، کاپی' },
  { ca: 'part', es: 'parte (un trozo del total)', ar: 'جزء (قطعة من الكل)', ur: 'حصہ' },
  { ca: 'pas', es: 'paso (cada acción del procedimiento)', ar: 'خطوة (كل إجراء في العملية)', ur: 'قدم (طریقے کا ہر مرحلہ)' },
  { ca: 'passos', es: 'pasos', ar: 'خطوات', ur: 'مراحل، قدم' },
  { ca: 'no pas', es: 'no, en absoluto (refuerza la negación)', ar: 'ليس البتّة (توكيد النفي)', ur: 'ہرگز نہیں (نفی کی تاکید)' },
  { ca: 'tira', es: 'tira (trozo largo y estrecho de papel)', ar: 'شريط (قطعة ورق طويلة ضيّقة)', ur: 'پٹی (کاغذ کا لمبا تنگ ٹکڑا)' },
  { ca: 'tires', es: 'lanzas, tiras (la moneda o el dado)', ar: 'تَرمي (العملة أو النرد)', ur: 'آپ پھینکتے ہیں (سکہ یا پانسہ)' },
  { ca: 'havia', es: 'había (+ participio: una acción anterior a otra pasada)', ar: 'كان قد… (فعل سابق على ماضٍ آخر)', ur: 'تھا / چکا تھا (پہلے ہو چکا)' },
  { ca: 'hi havia', es: 'había, existía', ar: 'كان هناك، كان موجودًا', ur: 'موجود تھا' },
  { ca: 'queda', es: 'queda (lo que aún hay)', ar: 'يتبقّى (ما زال موجودًا)', ur: 'باقی رہتا ہے' },
  { ca: 'tingui', es: 'tenga', ar: 'أن يملك', ur: 'کہ اُس کے پاس ہو' },
  { ca: 'perdent', es: 'perdiendo (poco a poco)', ar: 'يفقد شيئًا فشيئًا', ur: 'رفتہ رفتہ کھوتا جا رہا ہے' },
  { ca: 'posa a prova', es: 'pon a prueba', ar: 'اختبِر، ضعه على المحكّ', ur: 'آزماؤ، جانچو' },
  { ca: 'posem a prova', es: 'ponemos a prueba', ar: 'نختبر', ur: 'ہم آزماتے ہیں' },
  { ca: 'posarem a prova', es: 'pondremos a prueba', ar: 'سنختبر', ur: 'ہم آزمائیں گے' },
  { ca: 'sortida de camp', es: 'salida de campo (excursión para observar)', ar: 'خرجة ميدانية (رحلة للملاحظة)', ur: 'فیلڈ ٹرپ (مشاہدے کے لیے)' },

  // ── G) 2a ronda de revisió (alumne nouvingut, 24/08) ────
  // Els noms concrets amb què estan escrites SA2, SA5, SA6 i SA7: sense
  // ells hi havia trams ressaltats sencers on l'única paraula amb tooltip
  // era «i» o «més».
  { ca: 'os', es: 'hueso', ar: 'عظم', ur: 'ہڈی' },
  { ca: 'ossets', es: 'huesecillos (huesos pequeños)', ar: 'عُظيمات (عظام صغيرة)', ur: 'چھوٹی ہڈیاں' },
  // `mà` és segura: la regla -ans→à converteix «mans» en «mà», que és
  // justament el correcte (l'avís antic de T.jsx era inexacte).
  { ca: 'mà', es: 'mano', ar: 'يد', ur: 'ہاتھ' },
  { ca: 'aleta', es: 'aleta (de un pez o una ballena)', ar: 'زعنفة', ur: 'مچھلی کا پَر' },
  { ca: 'pollastre', es: 'pollo', ar: 'دجاجة', ur: 'مرغی' },
  { ca: 'ratpenat', es: 'murciélago', ar: 'خفّاش', ur: 'چمگادڑ' },
  { ca: 'balena', es: 'ballena', ar: 'حوت', ur: 'وھیل' },
  { ca: 'fulla', es: 'hoja (de una planta)', ar: 'ورقة شجر', ur: 'پتّا' },
  { ca: 'pluja', es: 'lluvia', ar: 'مطر', ur: 'بارش' },
  // ⚠️ `sòl` i `sol` són dues paraules diferents i totes dues surten a SA6·S4.
  { ca: 'sòl', es: 'suelo: la tierra de encima (≠ «sol», que es solo/el Sol)', ar: 'التربة: الطبقة السطحية من الأرض (تختلف عن «sol»)', ur: 'مٹی، زمین کی اوپری تہہ («sol» سے مختلف)' },
  { ca: 'vessant', es: 'ladera (el lado inclinado de la montaña)', ar: 'منحدر (جانب الجبل المائل)', ur: 'ڈھلان (پہاڑ کا ترچھا رخ)' },
  { ca: 'pendent', es: 'pendiente, inclinación', ar: 'انحدار، ميل', ur: 'ڈھلان کا جھکاؤ' },
  { ca: 'barranc', es: 'barranco (valle estrecho y hondo)', ar: 'وادٍ ضيّق عميق', ur: 'گہری تنگ گھاٹی' },
  { ca: 'fàrmac', es: 'fármaco, medicamento', ar: 'دواء', ur: 'دوا' },
  { ca: 'biòpsia', es: 'biopsia (trozo de tejido que se saca para mirarlo)', ar: 'خزعة (قطعة نسيج تُؤخذ للفحص)', ur: 'بایوپسی (جانچ کے لیے لیا گیا ٹشو)' },
  { ca: 'llindar', es: 'umbral: el número a partir del cual ya hace sospechar', ar: 'عتبة: الرقم الذي يبدأ عنده الشكّ', ur: 'حد: وہ عدد جس کے بعد شک ہونے لگے' },
  { ca: 'dosi', es: 'dosis (cuánto medicamento se da)', ar: 'جرعة (كمية الدواء)', ur: 'خوراک (دوا کی مقدار)' },
  { ca: 'ratolí', es: 'ratón', ar: 'فأر', ur: 'چوہا' },
  { ca: 'demostrar', es: 'demostrar (probarlo de forma que no quede duda)', ar: 'يُثبت (بما لا يدع مجالًا للشكّ)', ur: 'ثابت کرنا (بغیر شک کے)' },
  { ca: 'demostra', es: 'demuestra', ar: 'يُثبت', ur: 'ثابت کرتا ہے' },
  { ca: 'molècula', es: 'molécula (grupo de átomos unidos)', ar: 'جزيء (ذرّات مرتبطة)', ur: 'مالیکیول (جُڑے ہوئے ایٹم)' },
  { ca: 'forat', es: 'agujero: lo que la hipótesis todavía NO explica', ar: 'ثغرة: ما لا تفسّره الفرضية بعد', ur: 'خلا: جو مفروضہ ابھی بیان نہیں کرتا' },
  { ca: 'escenari', es: 'escenario: cada una de las situaciones que se proponen', ar: 'سيناريو: كل وضع مقترح', ur: 'منظرنامہ: ہر تجویز کردہ صورت' },
  { ca: 'peça', es: 'pieza (cada trozo del conjunto)', ar: 'قطعة (كل جزء من المجموع)', ur: 'پُرزہ (مجموعے کا ہر حصہ)' },
  { ca: 'aparell', es: 'aparato (el montaje del experimento)', ar: 'جهاز (تركيب التجربة)', ur: 'آلہ (تجربے کا سیٹ اپ)' },
  { ca: 'munt', es: 'montón (un grupo grande)', ar: 'كومة (مجموعة كبيرة)', ur: 'ڈھیر (بڑا مجموعہ)' },
  // ⚠️ EL terme de SA4: 92 aparicions i no tenia entrada.
  { ca: 'caràcter', es: 'carácter: cada rasgo que se hereda (color de ojos, altura…)', ar: 'صفة وراثية (لون العينين، الطول…)', ur: 'وراثتی خصوصیت (آنکھوں کا رنگ، قد…)' },
  { ca: 'exemple', es: 'ejemplo', ar: 'مثال', ur: 'مثال' },
  { ca: 'canvi', es: 'cambio', ar: 'تغيّر', ur: 'تبدیلی' },
  { ca: 'sense', es: 'sin', ar: 'بدون', ur: 'بغیر' },
  { ca: 'servir', es: 'servir (para qué se usa)', ar: 'يصلح لـ، يُستعمل لـ', ur: 'کام آنا' },
  { ca: 'molts', es: 'muchos', ar: 'كثيرون، كثير من', ur: 'بہت سے' },
  { ca: 'assaig', es: 'ensayo (prueba controlada de un fármaco)', ar: 'تجربة سريرية مضبوطة لدواء', ur: 'دوا کی کنٹرول شدہ آزمائش' },
  // Expressions que sense donar d'alta feien entendre el contrari
  { ca: 'amb prou feines', es: 'a duras penas, casi no', ar: 'بالكاد', ur: 'مشکل سے، بمشکل' },
  { ca: "n'hi ha prou", es: 'basta con, es suficiente', ar: 'يكفي أن', ur: 'اتنا کافی ہے' },
  { ca: 'pel seu compte', es: 'por su cuenta, de forma independiente', ar: 'بمفرده، بشكل مستقلّ', ur: 'اپنے طور پر، آزادانہ' },
  { ca: 'tenir en compte', es: 'tener en cuenta', ar: 'أخذ بعين الاعتبار', ur: 'مدنظر رکھنا' },
  { ca: 'compte', es: '¡cuidado!, atención', ar: 'انتبه!', ur: 'خبردار!، دھیان' },
  { ca: 'envà', es: 'tabique (pared fina que separa)', ar: 'حاجز (جدار رقيق يفصل)', ur: 'پردہ (پتلی دیوار جو الگ کرے)' }
]

// Índex: frases multi-paraula primer (més llargues primer), després paraules soltes
const normalize = (s) => s.toLowerCase()

// ⚠️ Bug corregit el 2026-08-24 (revisió d'alumna nouvinguda):
// `T.jsx` normalitza CADA token del text traient-li l'article apostrofat
// (`l'atzar` → `atzar`, `n'hi` → `hi`), però aquí les paraules de la frase
// es guardaven tal com estaven escrites. Resultat: qualsevol expressió amb
// article apostrofat no s'activava MAI. En quedaven dues de mortes:
// «a l'atzar» i «no n'hi ha prou» — i la segona és especialment greu, perquè
// sense ella «l'actualisme sol no n'hi ha prou» només ensenyava el tooltip
// de `prou` = «suficient», o sigui exactament el contrari del que diu.
// Les paraules de la frase s'han de normalitzar igual que els tokens.
const stripArticle = (w) => w.replace(/^[ldsnmt]['’]/, '')

export const PHRASES = GLOSSARY.filter((e) => e.ca.includes(' '))
  .sort((a, b) => b.ca.split(' ').length - a.ca.split(' ').length)
  .map((e) => ({ ...e, words: normalize(e.ca).split(' ').map(stripArticle) }))

export const WORDS = new Map(
  GLOSSARY.filter((e) => !e.ca.includes(' ')).map((e) => [normalize(e.ca), e])
)

export const MAX_PHRASE_LEN = PHRASES.length
  ? Math.max(...PHRASES.map((p) => p.words.length))
  : 1
