// Glossari CA → ES / AR / UR per a la traducció per hover.
// La web és sempre en català: aquestes traduccions apareixen com a
// tooltip en passar per sobre, perquè l'alumnat nouvingut entengui
// el català sense dependre de la llengua materna.
//
// Les entrades multi-paraula tenen prioritat (es tradueix l'expressió
// sencera quan paraula per paraula no tindria sentit).

export const GLOSSARY = [
  // ── Expressions i frases fetes ──────────────────────────
  { ca: 'es marceix', es: 'se marchita', ar: 'تذبل', ur: 'مرجھا جاتا ہے' },
  { ca: 'feina a casa', es: 'deberes', ar: 'واجب منزلي', ur: 'گھر کا کام' },
  { ca: 'data límit', es: 'fecha límite', ar: 'الموعد النهائي', ur: 'آخری تاریخ' },
  { ca: 'has faltat', es: 'has faltado a clase', ar: 'تغيّبت عن الصف', ur: 'آپ غیر حاضر تھے' },
  { ca: 'idees prèvies', es: 'ideas previas', ar: 'أفكارك المسبقة', ur: 'پہلے سے موجود خیالات' },
  { ca: 'exit tiquet', es: 'ticket de salida', ar: 'بطاقة الخروج', ur: 'ایگزٹ ٹکٹ (اختتامی سوال)' },
  { ca: 'en parelles', es: 'en parejas', ar: 'في أزواج', ur: 'جوڑوں میں' },
  { ca: 'en veu alta', es: 'en voz alta', ar: 'بصوت عالٍ', ur: 'بلند آواز میں' },
  { ca: 'a mà', es: 'a mano', ar: 'يدويًا', ur: 'ہاتھ سے' },
  { ca: 'pas a pas', es: 'paso a paso', ar: 'خطوة بخطوة', ur: 'قدم بہ قدم' },
  { ca: 'per quina raó', es: 'por qué razón', ar: 'لأي سبب', ur: 'کس وجہ سے' },
  { ca: 'posa en comú', es: 'puesta en común', ar: 'شاركها مع الصف', ur: 'سب کے ساتھ شیئر کریں' },
  { ca: 'membrana semipermeable', es: 'membrana semipermeable', ar: 'غشاء شبه نافذ', ur: 'نیم نفوذ پذیر جھلی' },
  { ca: 'respiració cel·lular', es: 'respiración celular', ar: 'التنفس الخلوي', ur: 'خلوی تنفس' },
  { ca: 'divisió cel·lular', es: 'división celular', ar: 'انقسام الخلية', ur: 'خلیے کی تقسیم' },
  { ca: 'cèl·lula mare', es: 'célula madre', ar: 'الخلية الأم', ur: 'مادر خلیہ' },
  { ca: 'cèl·lules filles', es: 'células hijas', ar: 'خلايا وليدة', ur: 'بیٹی خلیے' },
  { ca: 'cèl·lules sexuals', es: 'células sexuales', ar: 'الخلايا الجنسية', ur: 'جنسی خلیے' },
  { ca: 'freqüència cardíaca', es: 'frecuencia cardíaca', ar: 'معدل ضربات القلب', ur: 'دل کی دھڑکن کی رفتار' },
  { ca: 'doble circulació', es: 'doble circulación', ar: 'الدورة الدموية المزدوجة', ur: 'دوہری گردشِ خون' },
  { ca: 'intestí prim', es: 'intestino delgado', ar: 'الأمعاء الدقيقة', ur: 'چھوٹی آنت' },
  { ca: 'intestí gros', es: 'intestino grueso', ar: 'الأمعاء الغليظة', ur: 'بڑی آنت' },
  { ca: 'sistema digestiu', es: 'sistema digestivo', ar: 'الجهاز الهضمي', ur: 'نظامِ ہضم' },
  { ca: 'sistema circulatori', es: 'sistema circulatorio', ar: 'الجهاز الدوري', ur: 'دورانِ خون کا نظام' },
  { ca: 'sistema nerviós', es: 'sistema nervioso', ar: 'الجهاز العصبي', ur: 'اعصابی نظام' },
  { ca: 'sistema endocrí', es: 'sistema endocrino', ar: 'جهاز الغدد الصماء', ur: 'اینڈوکرائن نظام' },
  { ca: 'sistema excretor', es: 'sistema excretor', ar: 'الجهاز الإخراجي', ur: 'اخراجی نظام' },
  { ca: 'medul·la espinal', es: 'médula espinal', ar: 'النخاع الشوكي', ur: 'حرام مغز' },
  { ca: 'arc reflex', es: 'arco reflejo', ar: 'القوس الانعكاسي', ur: 'اضطراری قوس' },
  { ca: 'temps de reacció', es: 'tiempo de reacción', ar: 'زمن رد الفعل', ur: 'ردِعمل کا وقت' },
  { ca: 'àcid làctic', es: 'ácido láctico', ar: 'حمض اللاكتيك', ur: 'لیکٹک ایسڈ' },
  { ca: 'zona aeròbica', es: 'zona aeróbica', ar: 'المنطقة الهوائية', ur: 'ایروبک زون' },
  { ca: 'zona anaeròbica', es: 'zona anaeróbica', ar: 'المنطقة اللاهوائية', ur: 'اینیروبک زون' },
  { ca: 'sèrum fisiològic', es: 'suero fisiológico', ar: 'محلول ملحي طبي', ur: 'فزیولوجیکل سیرم' },
  { ca: 'aigua pura', es: 'agua pura', ar: 'ماء نقي', ur: 'خالص پانی' },
  { ca: 'sense closca', es: 'sin cáscara', ar: 'بدون قشرة', ur: 'بغیر چھلکے کے' },
  { ca: 'bolo alimentici', es: 'bolo alimenticio', ar: 'البلعة الغذائية', ur: 'نوالہ (بولس)' },
  { ca: 'vena porta', es: 'vena porta', ar: 'الوريد البابي', ur: 'پورٹل ورید' },
  { ca: 'hidrats de carboni', es: 'hidratos de carbono', ar: 'الكربوهيدرات', ur: 'کاربوہائیڈریٹس' },
  { ca: 'prova escrita', es: 'examen escrito', ar: 'اختبار كتابي', ur: 'تحریری امتحان' },
  { ca: 'full de treball', es: 'hoja de trabajo', ar: 'ورقة العمل', ur: 'ورک شیٹ' },

  // ── La cèl·lula (SA1) ───────────────────────────────────
  { ca: 'cèl·lula', es: 'célula', ar: 'خلية', ur: 'خلیہ' },
  { ca: 'cèl·lules', es: 'células', ar: 'خلايا', ur: 'خلیے' },
  { ca: 'membrana', es: 'membrana', ar: 'غشاء', ur: 'جھلی' },
  { ca: 'nucli', es: 'núcleo', ar: 'نواة', ur: 'مرکزہ' },
  { ca: 'mitocondri', es: 'mitocondria', ar: 'ميتوكوندريون', ur: 'مائٹوکونڈریا' },
  { ca: 'mitocondris', es: 'mitocondrias', ar: 'ميتوكوندريا', ur: 'مائٹوکونڈریا' },
  { ca: 'orgànul', es: 'orgánulo', ar: 'عضيّة', ur: 'عضوہ' },
  { ca: 'orgànuls', es: 'orgánulos', ar: 'عضيّات', ur: 'عضوے' },
  { ca: 'citoplasma', es: 'citoplasma', ar: 'سيتوبلازم', ur: 'سائٹوپلازم' },
  { ca: 'ADN', es: 'ADN', ar: 'الحمض النووي DNA', ur: 'ڈی این اے' },
  { ca: 'gens', es: 'genes', ar: 'جينات', ur: 'جینز' },
  { ca: 'proteïnes', es: 'proteínas', ar: 'بروتينات', ur: 'پروٹین' },
  { ca: 'teixit', es: 'tejido', ar: 'نسيج', ur: 'بافت' },
  { ca: 'teixits', es: 'tejidos', ar: 'أنسجة', ur: 'بافتیں' },
  { ca: 'òrgan', es: 'órgano', ar: 'عضو', ur: 'عضو' },
  { ca: 'òrgans', es: 'órganos', ar: 'أعضاء', ur: 'اعضاء' },
  { ca: 'organisme', es: 'organismo', ar: 'كائن حي', ur: 'جاندار' },
  { ca: 'procariota', es: 'procariota', ar: 'بدائية النواة', ur: 'پروکیریوٹ' },
  { ca: 'eucariota', es: 'eucariota', ar: 'حقيقية النواة', ur: 'یوکیریوٹ' },
  { ca: 'autòtrofs', es: 'autótrofos', ar: 'ذاتية التغذية', ur: 'خود خوراک ساز' },
  { ca: 'heteròtrofs', es: 'heterótrofos', ar: 'غيرية التغذية', ur: 'غیر خود خوراک ساز' },
  { ca: 'fotosíntesi', es: 'fotosíntesis', ar: 'التمثيل الضوئي', ur: 'ضیائی تالیف' },
  { ca: 'energia', es: 'energía', ar: 'طاقة', ur: 'توانائی' },
  { ca: 'glucosa', es: 'glucosa', ar: 'جلوكوز', ur: 'گلوکوز' },
  { ca: 'oxigen', es: 'oxígeno', ar: 'أكسجين', ur: 'آکسیجن' },
  { ca: 'aliment', es: 'alimento', ar: 'غذاء', ur: 'خوراک' },
  { ca: 'aliments', es: 'alimentos', ar: 'أغذية', ur: 'غذائیں' },
  { ca: 'menjar', es: 'comer / comida', ar: 'الأكل / الطعام', ur: 'کھانا' },
  { ca: 'respirar', es: 'respirar', ar: 'التنفس', ur: 'سانس لینا' },
  { ca: 'osmosi', es: 'ósmosis', ar: 'التناضح (الأسموزية)', ur: 'اوسموسس' },
  { ca: 'semipermeable', es: 'semipermeable', ar: 'شبه نافذ', ur: 'نیم نفوذ پذیر' },
  { ca: 'concentració', es: 'concentración', ar: 'تركيز', ur: 'ارتکاز' },
  { ca: 'solut', es: 'soluto', ar: 'مادة مذابة', ur: 'محلول مادہ' },
  { ca: 'isotònic', es: 'isotónico', ar: 'متساوي التوتر', ur: 'آئسوٹونک' },
  { ca: 'hipertònic', es: 'hipertónico', ar: 'مفرط التوتر', ur: 'ہائپرٹونک' },
  { ca: "s'infla", es: 'se hincha', ar: 'ينتفخ', ur: 'پھول جاتا ہے' },
  { ca: "s'encongeix", es: 'se encoge', ar: 'ينكمش', ur: 'سکڑ جاتا ہے' },
  { ca: 'ou', es: 'huevo', ar: 'بيضة', ur: 'انڈا' },
  { ca: 'vinagre', es: 'vinagre', ar: 'خل', ur: 'سرکہ' },
  { ca: 'closca', es: 'cáscara', ar: 'قشرة', ur: 'چھلکا' },
  { ca: 'sucre', es: 'azúcar', ar: 'سكر', ur: 'چینی' },
  { ca: 'got', es: 'vaso', ar: 'كوب', ur: 'گلاس' },
  { ca: 'gots', es: 'vasos', ar: 'أكواب', ur: 'گلاس' },
  { ca: 'adob', es: 'abono / fertilizante', ar: 'سماد', ur: 'کھاد' },
  { ca: 'mitosi', es: 'mitosis', ar: 'الانقسام المتساوي', ur: 'مائٹوسس' },
  { ca: 'meiosi', es: 'meiosis', ar: 'الانقسام المنصّف', ur: 'مییوسس' },
  { ca: 'idèntiques', es: 'idénticas', ar: 'متطابقة', ur: 'بالکل ایک جیسے' },
  { ca: 'meitat', es: 'mitad', ar: 'نصف', ur: 'آدھا' },
  { ca: 'espermatozoide', es: 'espermatozoide', ar: 'حيوان منوي', ur: 'سپرم' },
  { ca: 'òvul', es: 'óvulo', ar: 'بويضة', ur: 'بیضہ' },
  { ca: 'càncer', es: 'cáncer', ar: 'سرطان', ur: 'کینسر' },
  { ca: 'tumors', es: 'tumores', ar: 'أورام', ur: 'رسولیاں' },
  { ca: 'diferenciació', es: 'diferenciación', ar: 'التمايز', ur: 'تفریق' },
  { ca: 'ferida', es: 'herida', ar: 'جرح', ur: 'زخم' },
  { ca: 'ferides', es: 'heridas', ar: 'جروح', ur: 'زخم' },
  { ca: 'curar', es: 'curar', ar: 'شفاء', ur: 'ٹھیک کرنا' },
  { ca: 'créixer', es: 'crecer', ar: 'النمو', ur: 'بڑھنا' },
  { ca: 'reparar', es: 'reparar', ar: 'إصلاح', ur: 'مرمت کرنا' },
  { ca: 'substituir', es: 'sustituir', ar: 'استبدال', ur: 'بدلنا' },
  { ca: 'neurona', es: 'neurona', ar: 'خلية عصبية', ur: 'نیوران' },
  { ca: 'neurones', es: 'neuronas', ar: 'خلايا عصبية', ur: 'نیورانز' },
  { ca: 'pell', es: 'piel', ar: 'جلد', ur: 'جلد' },
  { ca: 'múscul', es: 'músculo', ar: 'عضلة', ur: 'پٹھا' },
  { ca: 'músculs', es: 'músculos', ar: 'عضلات', ur: 'پٹھے' },
  { ca: 'muscular', es: 'muscular', ar: 'عضلي', ur: 'عضلاتی' },

  // ── El cos humà (SA2) ───────────────────────────────────
  { ca: 'nutrients', es: 'nutrientes', ar: 'مغذيات', ur: 'غذائی اجزاء' },
  { ca: 'nutrient', es: 'nutriente', ar: 'مادة مغذية', ur: 'غذائی جز' },
  { ca: 'midó', es: 'almidón', ar: 'نشا', ur: 'نشاستہ' },
  { ca: 'greixos', es: 'grasas', ar: 'دهون', ur: 'چکنائیاں' },
  { ca: 'fosfolípids', es: 'fosfolípidos', ar: 'فوسفوليبيدات', ur: 'فاسفولپڈز' },
  { ca: 'aminoàcids', es: 'aminoácidos', ar: 'أحماض أمينية', ur: 'امینو ایسڈز' },
  { ca: 'vitamines', es: 'vitaminas', ar: 'فيتامينات', ur: 'وٹامنز' },
  { ca: 'ferro', es: 'hierro', ar: 'حديد', ur: 'فولاد (آئرن)' },
  { ca: 'hemoglobina', es: 'hemoglobina', ar: 'هيموجلوبين', ur: 'ہیموگلوبن' },
  { ca: 'sang', es: 'sangre', ar: 'دم', ur: 'خون' },
  { ca: 'plasma', es: 'plasma', ar: 'بلازما', ur: 'پلازما' },
  { ca: 'eritròcits', es: 'glóbulos rojos', ar: 'كريات الدم الحمراء', ur: 'سرخ خونی خلیے' },
  { ca: 'leucòcits', es: 'glóbulos blancos', ar: 'كريات الدم البيضاء', ur: 'سفید خونی خلیے' },
  { ca: 'plaquetes', es: 'plaquetas', ar: 'صفائح دموية', ur: 'پلیٹلیٹس' },
  { ca: 'anèmia', es: 'anemia', ar: 'فقر الدم', ur: 'خون کی کمی' },
  { ca: 'analítica', es: 'análisis de sangre', ar: 'تحليل الدم', ur: 'خون کا ٹیسٹ' },
  { ca: 'hematòcrit', es: 'hematocrito', ar: 'الهيماتوكريت', ur: 'ہیماٹوکرٹ' },
  { ca: 'digestió', es: 'digestión', ar: 'الهضم', ur: 'ہضم' },
  { ca: 'estómac', es: 'estómago', ar: 'معدة', ur: 'معدہ' },
  { ca: 'esòfag', es: 'esófago', ar: 'مريء', ur: 'غذائی نالی' },
  { ca: 'pàncrees', es: 'páncreas', ar: 'بنكرياس', ur: 'لبلبہ' },
  { ca: 'bilis', es: 'bilis', ar: 'الصفراء', ur: 'صفرا' },
  { ca: 'enzims', es: 'enzimas', ar: 'إنزيمات', ur: 'خامرے (انزائمز)' },
  { ca: 'àcid', es: 'ácido', ar: 'حمض', ur: 'تیزاب' },
  { ca: 'bicarbonat', es: 'bicarbonato', ar: 'بيكربونات', ur: 'بائی کاربونیٹ' },
  { ca: 'quimo', es: 'quimo', ar: 'الكيموس', ur: 'کائم' },
  { ca: 'peristaltisme', es: 'peristaltismo', ar: 'الحركة الدودية', ur: 'پیرسٹالسس' },
  { ca: 'vellositats', es: 'vellosidades', ar: 'زغابات معوية', ur: 'آنتوں کے ریشے' },
  { ca: 'absorció', es: 'absorción', ar: 'امتصاص', ur: 'جذب' },
  { ca: 'microbiota', es: 'microbiota', ar: 'الميكروبيوم المعوي', ur: 'مائکروبایوٹا' },
  { ca: 'bacteris', es: 'bacterias', ar: 'بكتيريا', ur: 'بیکٹیریا' },
  { ca: 'cor', es: 'corazón', ar: 'قلب', ur: 'دل' },
  { ca: 'aurícules', es: 'aurículas', ar: 'أذينان', ur: 'ایٹریا (بالائی خانے)' },
  { ca: 'ventricles', es: 'ventrículos', ar: 'بطينان', ur: 'وینٹریکلز (زیریں خانے)' },
  { ca: 'ventricle', es: 'ventrículo', ar: 'بطين', ur: 'وینٹریکل' },
  { ca: 'vàlvules', es: 'válvulas', ar: 'صمامات', ur: 'والوز' },
  { ca: 'tabi', es: 'tabique', ar: 'حاجز', ur: 'پردہ (سیپٹم)' },
  { ca: 'artèria', es: 'arteria', ar: 'شريان', ur: 'شریان' },
  { ca: 'artèries', es: 'arterias', ar: 'شرايين', ur: 'شریانیں' },
  { ca: 'vena', es: 'vena', ar: 'وريد', ur: 'ورید' },
  { ca: 'venes', es: 'venas', ar: 'أوردة', ur: 'وریدیں' },
  { ca: 'capil·lars', es: 'capilares', ar: 'شعيرات دموية', ur: 'کیپلریز' },
  { ca: 'aorta', es: 'aorta', ar: 'الشريان الأبهر', ur: 'شہ رگ' },
  { ca: 'coronàries', es: 'coronarias', ar: 'الشرايين التاجية', ur: 'کورونری شریانیں' },
  { ca: 'miocardi', es: 'miocardio', ar: 'عضلة القلب', ur: 'دل کا پٹھا' },
  { ca: 'infart', es: 'infarto', ar: 'احتشاء (نوبة قلبية)', ur: 'ہارٹ اٹیک' },
  { ca: 'batec', es: 'latido', ar: 'نبضة', ur: 'دھڑکن' },
  { ca: 'batecs', es: 'latidos', ar: 'نبضات', ur: 'دھڑکنیں' },
  { ca: 'pols', es: 'pulso', ar: 'النبض', ur: 'نبض' },
  { ca: 'canell', es: 'muñeca', ar: 'معصم', ur: 'کلائی' },
  { ca: 'pulmons', es: 'pulmones', ar: 'رئتان', ur: 'پھیپھڑے' },
  { ca: 'alvèols', es: 'alvéolos', ar: 'حويصلات هوائية', ur: 'ہوائی خانے (الویولائی)' },
  { ca: 'alvèol', es: 'alvéolo', ar: 'حويصلة هوائية', ur: 'ہوائی خانہ' },
  { ca: 'hormona', es: 'hormona', ar: 'هرمون', ur: 'ہارمون' },
  { ca: 'hormones', es: 'hormonas', ar: 'هرمونات', ur: 'ہارمونز' },
  { ca: 'adrenalina', es: 'adrenalina', ar: 'أدرينالين', ur: 'ایڈرینالین' },
  { ca: 'insulina', es: 'insulina', ar: 'إنسولين', ur: 'انسولین' },
  { ca: 'glàndula', es: 'glándula', ar: 'غدة', ur: 'غدود' },
  { ca: 'ronyó', es: 'riñón', ar: 'كلية', ur: 'گردہ' },
  { ca: 'ronyons', es: 'riñones', ar: 'كليتان', ur: 'گردے' },
  { ca: 'orina', es: 'orina', ar: 'بول', ur: 'پیشاب' },
  { ca: 'urea', es: 'urea', ar: 'يوريا', ur: 'یوریا' },
  { ca: 'homeòstasi', es: 'homeostasis', ar: 'الاتزان الداخلي', ur: 'ہومیوسٹیسس' },
  { ca: 'nervi', es: 'nervio', ar: 'عصب', ur: 'عصب' },
  { ca: 'nervis', es: 'nervios', ar: 'أعصاب', ur: 'اعصاب' },
  { ca: 'reflex', es: 'reflejo', ar: 'منعكس', ur: 'اضطراری حرکت' },
  { ca: 'cervell', es: 'cerebro', ar: 'دماغ', ur: 'دماغ' },
  { ca: 'fatiga', es: 'fatiga / cansancio', ar: 'تعب', ur: 'تھکاوٹ' },
  { ca: 'esforç', es: 'esfuerzo', ar: 'جهد', ur: 'محنت / زور' },
  { ca: 'exercici', es: 'ejercicio', ar: 'تمرين', ur: 'ورزش' },
  { ca: 'repòs', es: 'reposo', ar: 'راحة', ur: 'آرام' },
  { ca: 'corredor', es: 'corredor', ar: 'عدّاء', ur: 'دوڑنے والا' },
  { ca: 'corredora', es: 'corredora', ar: 'عدّاءة', ur: 'دوڑنے والی' },
  { ca: 'cursa', es: 'carrera', ar: 'سباق', ur: 'دوڑ' },
  { ca: 'residus', es: 'residuos', ar: 'فضلات', ur: 'فضلہ' },

  // ── Instruccions i vocabulari escolar ───────────────────
  { ca: 'observa', es: 'observa', ar: 'لاحظ', ur: 'مشاہدہ کریں' },
  { ca: 'mesura', es: 'mide', ar: 'قِس', ur: 'ناپیں' },
  { ca: 'pesa', es: 'pesa', ar: 'زِن', ur: 'وزن کریں' },
  { ca: 'anota', es: 'anota', ar: 'دوّن', ur: 'لکھ لیں' },
  { ca: 'registra', es: 'registra', ar: 'سجّل', ur: 'درج کریں' },
  { ca: 'dibuixa', es: 'dibuja', ar: 'ارسم', ur: 'بنائیں (ڈرائنگ)' },
  { ca: 'escriu', es: 'escribe', ar: 'اكتب', ur: 'لکھیں' },
  { ca: 'llegeix', es: 'lee', ar: 'اقرأ', ur: 'پڑھیں' },
  { ca: 'explica', es: 'explica', ar: 'اشرح', ur: 'وضاحت کریں' },
  { ca: 'justifica', es: 'justifica', ar: 'برّر', ur: 'دلیل دیں' },
  { ca: 'compara', es: 'compara', ar: 'قارن', ur: 'موازنہ کریں' },
  { ca: 'ordena', es: 'ordena', ar: 'رتّب', ur: 'ترتیب دیں' },
  { ca: 'classifica', es: 'clasifica', ar: 'صنّف', ur: 'درجہ بندی کریں' },
  { ca: 'omple', es: 'rellena', ar: 'املأ', ur: 'بھریں' },
  { ca: 'descarrega', es: 'descarga', ar: 'حمّل', ur: 'ڈاؤن لوڈ کریں' },
  { ca: 'comprova', es: 'comprueba', ar: 'تحقق', ur: 'جانچیں' },
  { ca: 'tria', es: 'elige', ar: 'اختر', ur: 'منتخب کریں' },
  { ca: 'marca', es: 'marca', ar: 'علّم', ur: 'نشان لگائیں' },
  { ca: 'predicció', es: 'predicción', ar: 'توقع', ur: 'پیشگوئی' },
  { ca: 'prediccions', es: 'predicciones', ar: 'توقعات', ur: 'پیشگوئیاں' },
  { ca: 'hipòtesi', es: 'hipótesis', ar: 'فرضية', ur: 'مفروضہ' },
  { ca: 'hipòtesis', es: 'hipótesis', ar: 'فرضيات', ur: 'مفروضے' },
  { ca: 'resultats', es: 'resultados', ar: 'نتائج', ur: 'نتائج' },
  { ca: 'taula', es: 'tabla', ar: 'جدول', ur: 'جدول' },
  { ca: 'gràfica', es: 'gráfica', ar: 'رسم بياني', ur: 'گراف' },
  { ca: 'gràfiques', es: 'gráficas', ar: 'رسوم بيانية', ur: 'گراف' },
  { ca: 'fitxa', es: 'ficha', ar: 'ورقة العمل', ur: 'ورک شیٹ' },
  { ca: 'full', es: 'hoja', ar: 'ورقة', ur: 'کاغذ / شیٹ' },
  { ca: 'apartat', es: 'apartado', ar: 'قسم', ur: 'حصہ' },
  { ca: 'apartats', es: 'apartados', ar: 'أقسام', ur: 'حصے' },
  { ca: 'pista', es: 'pista', ar: 'تلميح', ur: 'اشارہ' },
  { ca: 'pistes', es: 'pistas', ar: 'تلميحات', ur: 'اشارے' },
  { ca: 'pregunta', es: 'pregunta', ar: 'سؤال', ur: 'سوال' },
  { ca: 'preguntes', es: 'preguntas', ar: 'أسئلة', ur: 'سوالات' },
  { ca: 'resposta', es: 'respuesta', ar: 'إجابة', ur: 'جواب' },
  { ca: 'respostes', es: 'respuestas', ar: 'إجابات', ur: 'جوابات' },
  { ca: 'deures', es: 'deberes', ar: 'واجبات', ur: 'ہوم ورک' },
  { ca: 'termini', es: 'plazo', ar: 'مهلة', ur: 'مدت' },
  { ca: 'entrega', es: 'entrega', ar: 'تسليم', ur: 'جمع کرانا' },
  { ca: 'entregues', es: 'entregas', ar: 'تسليمات', ur: 'جمع کرانے کی چیزیں' },
  { ca: 'sessió', es: 'sesión', ar: 'حصة', ur: 'سیشن' },
  { ca: 'sessions', es: 'sesiones', ar: 'حصص', ur: 'سیشنز' },
  { ca: 'prova', es: 'examen', ar: 'اختبار', ur: 'امتحان' },
  { ca: 'rúbrica', es: 'rúbrica', ar: 'سلم التقييم', ur: 'روبرک (جانچ پیمانہ)' },
  { ca: 'pòster', es: 'póster', ar: 'ملصق', ur: 'پوسٹر' },
  { ca: 'grup', es: 'grupo', ar: 'مجموعة', ur: 'گروپ' },
  { ca: 'materials', es: 'materiales', ar: 'أدوات', ur: 'سامان' },
  { ca: 'durada', es: 'duración', ar: 'مدة', ur: 'دورانیہ' },
  { ca: 'objectius', es: 'objetivos', ar: 'أهداف', ur: 'مقاصد' },
  { ca: 'competències', es: 'competencias', ar: 'كفاءات', ur: 'صلاحیتیں' },
  { ca: 'recuperació', es: 'recuperación', ar: 'استدراك / تعويض', ur: 'تلافی' },
  { ca: 'autoavaluació', es: 'autoevaluación', ar: 'تقييم ذاتي', ur: 'خود تشخیص' },
  { ca: 'reflexió', es: 'reflexión', ar: 'تأمل', ur: 'غور و فکر' },
  { ca: 'repte', es: 'reto', ar: 'تحدٍّ', ur: 'چیلنج' },
  { ca: 'enigma', es: 'enigma', ar: 'لغز', ur: 'پہیلی' },
  { ca: 'enigmes', es: 'enigmas', ar: 'ألغاز', ur: 'پہیلیاں' },
  { ca: 'maqueta', es: 'maqueta', ar: 'مجسّم', ur: 'ماڈل' },
  { ca: 'dies', es: 'días', ar: 'أيام', ur: 'دن' },
  { ca: 'setmanes', es: 'semanas', ar: 'أسابيع', ur: 'ہفتے' },
  { ca: 'queden', es: 'quedan / faltan', ar: 'تبقّى', ur: 'باقی ہیں' }
]

// Índex: frases multi-paraula primer (més llargues primer), després paraules soltes
const normalize = (s) => s.toLowerCase()

export const PHRASES = GLOSSARY.filter((e) => e.ca.includes(' '))
  .sort((a, b) => b.ca.split(' ').length - a.ca.split(' ').length)
  .map((e) => ({ ...e, words: normalize(e.ca).split(' ') }))

export const WORDS = new Map(
  GLOSSARY.filter((e) => !e.ca.includes(' ')).map((e) => [normalize(e.ca), e])
)

export const MAX_PHRASE_LEN = PHRASES.length
  ? Math.max(...PHRASES.map((p) => p.words.length))
  : 1
