// Glossari CA → ES / AR / UR per a la traducció per hover.
// La web és sempre en català: aquestes traduccions apareixen com a
// tooltip en passar per sobre, perquè l'alumnat nouvingut entengui
// el català sense dependre de la llengua materna.
//
// Les entrades multi-paraula tenen prioritat (es tradueix l'expressió
// sencera quan paraula per paraula no tindria sentit).

export const GLOSSARY = [
  // ── Expressions i frases fetes ──────────────────────────
  { ca: 'es marceix', es: 'se marchita', ar: 'تذبل', ur: 'مرجھا جاتا ہے' },
  { ca: 'feina a casa', es: 'deberes', ar: 'واجب منزلي', ur: 'گھر کا کام' },
  { ca: 'data límit', es: 'fecha límite', ar: 'الموعد النهائي', ur: 'آخری تاریخ' },
  { ca: 'has faltat', es: 'has faltado a clase', ar: 'تغيّبت عن الصف', ur: 'آپ غیر حاضر تھے' },
  { ca: 'idees prèvies', es: 'ideas previas', ar: 'أفكارك المسبقة', ur: 'پہلے سے موجود خیالات' },
  { ca: 'exit tiquet', es: 'ticket de salida', ar: 'بطاقة الخروج', ur: 'ایگزٹ ٹکٹ (اختتامی سوال)' },
  { ca: 'en parelles', es: 'en parejas', ar: 'في أزواج', ur: 'جوڑوں میں' },
  { ca: 'en veu alta', es: 'en voz alta', ar: 'بصوت عالٍ', ur: 'بلند آواز میں' },
  { ca: 'a mà', es: 'a mano', ar: 'يدويًا', ur: 'ہاتھ سے' },
  { ca: 'pas a pas', es: 'paso a paso', ar: 'خطوة بخطوة', ur: 'قدم بہ قدم' },
  { ca: 'per quina raó', es: 'por qué razón', ar: 'لأي سبب', ur: 'کس وجہ سے' },
  { ca: 'posa en comú', es: 'puesta en común', ar: 'شاركها مع الصف', ur: 'سب کے ساتھ شیئر کریں' },
  { ca: 'membrana semipermeable', es: 'membrana semipermeable', ar: 'غشاء شبه نافذ', ur: 'نیم نفوذ پذیر جھلی' },
  { ca: 'respiració cel·lular', es: 'respiración celular', ar: 'التنفس الخلوي', ur: 'خلوی تنفس' },
  { ca: 'divisió cel·lular', es: 'división celular', ar: 'انقسام الخلية', ur: 'خلیے کی تقسیم' },
  { ca: 'cèl·lula mare', es: 'célula madre', ar: 'الخلية الأم', ur: 'مادر خلیہ' },
  { ca: 'cèl·lules filles', es: 'células hijas', ar: 'خلايا وليدة', ur: 'بیٹی خلیے' },
  { ca: 'cèl·lules sexuals', es: 'células sexuales', ar: 'الخلايا الجنسية', ur: 'جنسی خلیے' },
  { ca: 'freqüència cardíaca', es: 'frecuencia cardíaca', ar: 'معدل ضربات القلب', ur: 'دل کی دھڑکن کی رفتار' },
  { ca: 'doble circulació', es: 'doble circulación', ar: 'الدورة الدموية المزدوجة', ur: 'دوہری گردشِ خون' },
  { ca: 'intestí prim', es: 'intestino delgado', ar: 'الأمعاء الدقيقة', ur: 'چھوٹی آنت' },
  { ca: 'intestí gros', es: 'intestino grueso', ar: 'الأمعاء الغليظة', ur: 'بڑی آنت' },
  { ca: 'sistema digestiu', es: 'sistema digestivo', ar: 'الجهاز الهضمي', ur: 'نظامِ ہضم' },
  { ca: 'sistema circulatori', es: 'sistema circulatorio', ar: 'الجهاز الدوري', ur: 'دورانِ خون کا نظام' },
  { ca: 'sistema nerviós', es: 'sistema nervioso', ar: 'الجهاز العصبي', ur: 'اعصابی نظام' },
  { ca: 'sistema endocrí', es: 'sistema endocrino', ar: 'جهاز الغدد الصماء', ur: 'اینڈوکرائن نظام' },
  { ca: 'sistema excretor', es: 'sistema excretor', ar: 'الجهاز الإخراجي', ur: 'اخراجی نظام' },
  { ca: 'medul·la espinal', es: 'médula espinal', ar: 'النخاع الشوكي', ur: 'حرام مغز' },
  { ca: 'arc reflex', es: 'arco reflejo', ar: 'القوس الانعكاسي', ur: 'اضطراری قوس' },
  { ca: 'temps de reacció', es: 'tiempo de reacción', ar: 'زمن رد الفعل', ur: 'ردِعمل کا وقت' },
  { ca: 'àcid làctic', es: 'ácido láctico', ar: 'حمض اللاكتيك', ur: 'لیکٹک ایسڈ' },
  { ca: 'zona aeròbica', es: 'zona aeróbica', ar: 'المنطقة الهوائية', ur: 'ایروبک زون' },
  { ca: 'zona anaeròbica', es: 'zona anaeróbica', ar: 'المنطقة اللاهوائية', ur: 'اینیروبک زون' },
  { ca: 'sèrum fisiològic', es: 'suero fisiológico', ar: 'محلول ملحي طبي', ur: 'فزیولوجیکل سیرم' },
  { ca: 'aigua pura', es: 'agua pura', ar: 'ماء نقي', ur: 'خالص پانی' },
  { ca: 'sense closca', es: 'sin cáscara', ar: 'بدون قشرة', ur: 'بغیر چھلکے کے' },
  { ca: 'bolo alimentici', es: 'bolo alimenticio', ar: 'البلعة الغذائية', ur: 'نوالہ (بولس)' },
  { ca: 'vena porta', es: 'vena porta', ar: 'الوريد البابي', ur: 'پورٹل ورید' },
  { ca: 'hidrats de carboni', es: 'hidratos de carbono', ar: 'الكربوهيدرات', ur: 'کاربوہائیڈریٹس' },
  { ca: 'prova escrita', es: 'examen escrito', ar: 'اختبار كتابي', ur: 'تحریری امتحان' },
  { ca: 'full de treball', es: 'hoja de trabajo', ar: 'ورقة العمل', ur: 'ورک شیٹ' },

  // ── La cèl·lula (SA1) ───────────────────────────────────
  { ca: 'cèl·lula', es: 'célula', ar: 'خلية', ur: 'خلیہ' },
  { ca: 'cèl·lules', es: 'células', ar: 'خلايا', ur: 'خلیے' },
  { ca: 'membrana', es: 'membrana', ar: 'غشاء', ur: 'جھلی' },
  { ca: 'nucli', es: 'núcleo', ar: 'نواة', ur: 'مرکزہ' },
  { ca: 'mitocondri', es: 'mitocondria', ar: 'ميتوكوندريون', ur: 'مائٹوکونڈریا' },
  { ca: 'mitocondris', es: 'mitocondrias', ar: 'ميتوكوندريا', ur: 'مائٹوکونڈریا' },
  { ca: 'orgànul', es: 'orgánulo', ar: 'عضيّة', ur: 'عضوہ' },
  { ca: 'orgànuls', es: 'orgánulos', ar: 'عضيّات', ur: 'عضوے' },
  { ca: 'citoplasma', es: 'citoplasma', ar: 'سيتوبلازم', ur: 'سائٹوپلازم' },
  { ca: 'ADN', es: 'ADN', ar: 'الحمض النووي DNA', ur: 'ڈی این اے' },
  // «gens» és alhora el plural de gen i l'adverbi «gens ni mica».
  { ca: 'gens', es: 'genes · nada en absoluto', ar: 'جينات · إطلاقًا (ولا قليلًا)', ur: 'جینز · بالکل نہیں' },
  { ca: 'proteïnes', es: 'proteínas', ar: 'بروتينات', ur: 'پروٹین' },
  { ca: 'teixit', es: 'tejido', ar: 'نسيج', ur: 'بافت' },
  { ca: 'teixits', es: 'tejidos', ar: 'أنسجة', ur: 'بافتیں' },
  { ca: 'òrgan', es: 'órgano', ar: 'عضو', ur: 'عضو' },
  { ca: 'òrgans', es: 'órganos', ar: 'أعضاء', ur: 'اعضاء' },
  { ca: 'organisme', es: 'organismo', ar: 'كائن حي', ur: 'جاندار' },
  { ca: 'procariota', es: 'procariota', ar: 'بدائية النواة', ur: 'پروکیریوٹ' },
  { ca: 'eucariota', es: 'eucariota', ar: 'حقيقية النواة', ur: 'یوکیریوٹ' },
  { ca: 'autòtrofs', es: 'autótrofos', ar: 'ذاتية التغذية', ur: 'خود خوراک ساز' },
  { ca: 'heteròtrofs', es: 'heterótrofos', ar: 'غيرية التغذية', ur: 'غیر خود خوراک ساز' },
  { ca: 'fotosíntesi', es: 'fotosíntesis', ar: 'التمثيل الضوئي', ur: 'ضیائی تالیف' },
  { ca: 'energia', es: 'energía', ar: 'طاقة', ur: 'توانائی' },
  { ca: 'glucosa', es: 'glucosa', ar: 'جلوكوز', ur: 'گلوکوز' },
  { ca: 'oxigen', es: 'oxígeno', ar: 'أكسجين', ur: 'آکسیجن' },
  { ca: 'aliment', es: 'alimento', ar: 'غذاء', ur: 'خوراک' },
  { ca: 'aliments', es: 'alimentos', ar: 'أغذية', ur: 'غذائیں' },
  { ca: 'menjar', es: 'comer / comida', ar: 'الأكل / الطعام', ur: 'کھانا' },
  { ca: 'respirar', es: 'respirar', ar: 'التنفس', ur: 'سانس لینا' },
  { ca: 'osmosi', es: 'ósmosis', ar: 'التناضح (الأسموزية)', ur: 'اوسموسس' },
  { ca: 'semipermeable', es: 'semipermeable', ar: 'شبه نافذ', ur: 'نیم نفوذ پذیر' },
  { ca: 'concentració', es: 'concentración', ar: 'تركيز', ur: 'ارتکاز' },
  { ca: 'solut', es: 'soluto', ar: 'مادة مذابة', ur: 'محلول مادہ' },
  { ca: 'isotònic', es: 'isotónico', ar: 'متساوي التوتر', ur: 'آئسوٹونک' },
  { ca: 'hipertònic', es: 'hipertónico', ar: 'مفرط التوتر', ur: 'ہائپرٹونک' },
  { ca: "s'infla", es: 'se hincha', ar: 'ينتفخ', ur: 'پھول جاتا ہے' },
  { ca: "s'encongeix", es: 'se encoge', ar: 'ينكمش', ur: 'سکڑ جاتا ہے' },
  { ca: 'ou', es: 'huevo', ar: 'بيضة', ur: 'انڈا' },
  { ca: 'vinagre', es: 'vinagre', ar: 'خل', ur: 'سرکہ' },
  { ca: 'closca', es: 'cáscara', ar: 'قشرة', ur: 'چھلکا' },
  { ca: 'sucre', es: 'azúcar', ar: 'سكر', ur: 'چینی' },
  { ca: 'got', es: 'vaso', ar: 'كوب', ur: 'گلاس' },
  { ca: 'gots', es: 'vasos', ar: 'أكواب', ur: 'گلاس' },
  { ca: 'adob', es: 'abono / fertilizante', ar: 'سماد', ur: 'کھاد' },
  { ca: 'mitosi', es: 'mitosis', ar: 'الانقسام المتساوي', ur: 'مائٹوسس' },
  { ca: 'meiosi', es: 'meiosis', ar: 'الانقسام المنصّف', ur: 'مییوسس' },
  { ca: 'idèntiques', es: 'idénticas', ar: 'متطابقة', ur: 'بالکل ایک جیسے' },
  { ca: 'meitat', es: 'mitad', ar: 'نصف', ur: 'آدھا' },
  { ca: 'espermatozoide', es: 'espermatozoide', ar: 'حيوان منوي', ur: 'سپرم' },
  { ca: 'òvul', es: 'óvulo', ar: 'بويضة', ur: 'بیضہ' },
  { ca: 'càncer', es: 'cáncer', ar: 'سرطان', ur: 'کینسر' },
  { ca: 'tumors', es: 'tumores', ar: 'أورام', ur: 'رسولیاں' },
  { ca: 'diferenciació', es: 'diferenciación', ar: 'التمايز', ur: 'تفریق' },
  { ca: 'ferida', es: 'herida', ar: 'جرح', ur: 'زخم' },
  { ca: 'ferides', es: 'heridas', ar: 'جروح', ur: 'زخم' },
  { ca: 'curar', es: 'curar', ar: 'شفاء', ur: 'ٹھیک کرنا' },
  { ca: 'créixer', es: 'crecer', ar: 'النمو', ur: 'بڑھنا' },
  { ca: 'reparar', es: 'reparar', ar: 'إصلاح', ur: 'مرمت کرنا' },
  { ca: 'substituir', es: 'sustituir', ar: 'استبدال', ur: 'بدلنا' },
  { ca: 'neurona', es: 'neurona', ar: 'خلية عصبية', ur: 'نیوران' },
  { ca: 'neurones', es: 'neuronas', ar: 'خلايا عصبية', ur: 'نیورانز' },
  { ca: 'pell', es: 'piel', ar: 'جلد', ur: 'جلد' },
  { ca: 'múscul', es: 'músculo', ar: 'عضلة', ur: 'پٹھا' },
  { ca: 'músculs', es: 'músculos', ar: 'عضلات', ur: 'پٹھے' },
  { ca: 'muscular', es: 'muscular', ar: 'عضلي', ur: 'عضلاتی' },

  // ── El cos humà (SA2) ───────────────────────────────────
  { ca: 'nutrients', es: 'nutrientes', ar: 'مغذيات', ur: 'غذائی اجزاء' },
  { ca: 'nutrient', es: 'nutriente', ar: 'مادة مغذية', ur: 'غذائی جز' },
  { ca: 'midó', es: 'almidón', ar: 'نشا', ur: 'نشاستہ' },
  { ca: 'greixos', es: 'grasas', ar: 'دهون', ur: 'چکنائیاں' },
  { ca: 'fosfolípids', es: 'fosfolípidos', ar: 'فوسفوليبيدات', ur: 'فاسفولپڈز' },
  { ca: 'aminoàcids', es: 'aminoácidos', ar: 'أحماض أمينية', ur: 'امینو ایسڈز' },
  { ca: 'vitamines', es: 'vitaminas', ar: 'فيتامينات', ur: 'وٹامنز' },
  { ca: 'ferro', es: 'hierro', ar: 'حديد', ur: 'فولاد (آئرن)' },
  { ca: 'hemoglobina', es: 'hemoglobina', ar: 'هيموجلوبين', ur: 'ہیموگلوبن' },
  { ca: 'sang', es: 'sangre', ar: 'دم', ur: 'خون' },
  { ca: 'plasma', es: 'plasma', ar: 'بلازما', ur: 'پلازما' },
  { ca: 'eritròcits', es: 'glóbulos rojos', ar: 'كريات الدم الحمراء', ur: 'سرخ خونی خلیے' },
  { ca: 'leucòcits', es: 'glóbulos blancos', ar: 'كريات الدم البيضاء', ur: 'سفید خونی خلیے' },
  { ca: 'plaquetes', es: 'plaquetas', ar: 'صفائح دموية', ur: 'پلیٹلیٹس' },
  { ca: 'anèmia', es: 'anemia', ar: 'فقر الدم', ur: 'خون کی کمی' },
  { ca: 'analítica', es: 'análisis de sangre', ar: 'تحليل الدم', ur: 'خون کا ٹیسٹ' },
  { ca: 'hematòcrit', es: 'hematocrito', ar: 'الهيماتوكريت', ur: 'ہیماٹوکرٹ' },
  { ca: 'digestió', es: 'digestión', ar: 'الهضم', ur: 'ہضم' },
  { ca: 'estómac', es: 'estómago', ar: 'معدة', ur: 'معدہ' },
  { ca: 'esòfag', es: 'esófago', ar: 'مريء', ur: 'غذائی نالی' },
  { ca: 'pàncrees', es: 'páncreas', ar: 'بنكرياس', ur: 'لبلبہ' },
  { ca: 'bilis', es: 'bilis', ar: 'الصفراء', ur: 'صفرا' },
  { ca: 'enzims', es: 'enzimas', ar: 'إنزيمات', ur: 'خامرے (انزائمز)' },
  { ca: 'àcid', es: 'ácido', ar: 'حمض', ur: 'تیزاب' },
  { ca: 'bicarbonat', es: 'bicarbonato', ar: 'بيكربونات', ur: 'بائی کاربونیٹ' },
  { ca: 'quimo', es: 'quimo', ar: 'الكيموس', ur: 'کائم' },
  { ca: 'peristaltisme', es: 'peristaltismo', ar: 'الحركة الدودية', ur: 'پیرسٹالسس' },
  { ca: 'vellositats', es: 'vellosidades', ar: 'زغابات معوية', ur: 'آنتوں کے ریشے' },
  { ca: 'absorció', es: 'absorción', ar: 'امتصاص', ur: 'جذب' },
  { ca: 'microbiota', es: 'microbiota', ar: 'الميكروبيوم المعوي', ur: 'مائکروبایوٹا' },
  { ca: 'bacteris', es: 'bacterias', ar: 'بكتيريا', ur: 'بیکٹیریا' },
  { ca: 'cor', es: 'corazón', ar: 'قلب', ur: 'دل' },
  { ca: 'aurícules', es: 'aurículas', ar: 'أذينان', ur: 'ایٹریا (بالائی خانے)' },
  { ca: 'ventricles', es: 'ventrículos', ar: 'بطينان', ur: 'وینٹریکلز (زیریں خانے)' },
  { ca: 'ventricle', es: 'ventrículo', ar: 'بطين', ur: 'وینٹریکل' },
  { ca: 'vàlvules', es: 'válvulas', ar: 'صمامات', ur: 'والوز' },
  { ca: 'tabi', es: 'tabique', ar: 'حاجز', ur: 'پردہ (سیپٹم)' },
  { ca: 'artèria', es: 'arteria', ar: 'شريان', ur: 'شریان' },
  { ca: 'artèries', es: 'arterias', ar: 'شرايين', ur: 'شریانیں' },
  { ca: 'vena', es: 'vena', ar: 'وريد', ur: 'ورید' },
  { ca: 'venes', es: 'venas', ar: 'أوردة', ur: 'وریدیں' },
  { ca: 'capil·lars', es: 'capilares', ar: 'شعيرات دموية', ur: 'کیپلریز' },
  { ca: 'aorta', es: 'aorta', ar: 'الشريان الأبهر', ur: 'شہ رگ' },
  { ca: 'coronàries', es: 'coronarias', ar: 'الشرايين التاجية', ur: 'کورونری شریانیں' },
  { ca: 'miocardi', es: 'miocardio', ar: 'عضلة القلب', ur: 'دل کا پٹھا' },
  { ca: 'infart', es: 'infarto', ar: 'احتشاء (نوبة قلبية)', ur: 'ہارٹ اٹیک' },
  { ca: 'batec', es: 'latido', ar: 'نبضة', ur: 'دھڑکن' },
  { ca: 'batecs', es: 'latidos', ar: 'نبضات', ur: 'دھڑکنیں' },
  { ca: 'pols', es: 'pulso · polvo · polos', ar: 'النبض · الغبار · الأقطاب', ur: 'نبض · گرد · قطبین' },
  { ca: 'canell', es: 'muñeca', ar: 'معصم', ur: 'کلائی' },
  { ca: 'pulmons', es: 'pulmones', ar: 'رئتان', ur: 'پھیپھڑے' },
  { ca: 'alvèols', es: 'alvéolos', ar: 'حويصلات هوائية', ur: 'ہوائی خانے (الویولائی)' },
  { ca: 'alvèol', es: 'alvéolo', ar: 'حويصلة هوائية', ur: 'ہوائی خانہ' },
  { ca: 'hormona', es: 'hormona', ar: 'هرمون', ur: 'ہارمون' },
  { ca: 'hormones', es: 'hormonas', ar: 'هرمونات', ur: 'ہارمونز' },
  { ca: 'adrenalina', es: 'adrenalina', ar: 'أدرينالين', ur: 'ایڈرینالین' },
  { ca: 'insulina', es: 'insulina', ar: 'إنسولين', ur: 'انسولین' },
  { ca: 'glàndula', es: 'glándula', ar: 'غدة', ur: 'غدود' },
  { ca: 'ronyó', es: 'riñón', ar: 'كلية', ur: 'گردہ' },
  { ca: 'ronyons', es: 'riñones', ar: 'كليتان', ur: 'گردے' },
  { ca: 'orina', es: 'orina', ar: 'بول', ur: 'پیشاب' },
  { ca: 'urea', es: 'urea', ar: 'يوريا', ur: 'یوریا' },
  { ca: 'homeòstasi', es: 'homeostasis', ar: 'الاتزان الداخلي', ur: 'ہومیوسٹیسس' },
  { ca: 'nervi', es: 'nervio', ar: 'عصب', ur: 'عصب' },
  { ca: 'nervis', es: 'nervios', ar: 'أعصاب', ur: 'اعصاب' },
  { ca: 'reflex', es: 'reflejo', ar: 'منعكس', ur: 'اضطراری حرکت' },
  { ca: 'cervell', es: 'cerebro', ar: 'دماغ', ur: 'دماغ' },
  { ca: 'fatiga', es: 'fatiga / cansancio', ar: 'تعب', ur: 'تھکاوٹ' },
  { ca: 'esforç', es: 'esfuerzo', ar: 'جهد', ur: 'محنت / زور' },
  { ca: 'exercici', es: 'ejercicio', ar: 'تمرين', ur: 'ورزش' },
  { ca: 'repòs', es: 'reposo', ar: 'راحة', ur: 'آرام' },
  { ca: 'corredor', es: 'corredor', ar: 'عدّاء', ur: 'دوڑنے والا' },
  { ca: 'corredora', es: 'corredora', ar: 'عدّاءة', ur: 'دوڑنے والی' },
  { ca: 'cursa', es: 'carrera', ar: 'سباق', ur: 'دوڑ' },
  { ca: 'residus', es: 'residuos', ar: 'فضلات', ur: 'فضلہ' },

  // ── Instruccions i vocabulari escolar ───────────────────
  { ca: 'observa', es: 'observa', ar: 'لاحظ', ur: 'مشاہدہ کریں' },
  { ca: 'mesura', es: 'mide', ar: 'قِس', ur: 'ناپیں' },
  { ca: 'pesa', es: 'pesa', ar: 'زِن', ur: 'وزن کریں' },
  { ca: 'anota', es: 'anota', ar: 'دوّن', ur: 'لکھ لیں' },
  { ca: 'registra', es: 'registra', ar: 'سجّل', ur: 'درج کریں' },
  { ca: 'dibuixa', es: 'dibuja', ar: 'ارسم', ur: 'بنائیں (ڈرائنگ)' },
  { ca: 'escriu', es: 'escribe', ar: 'اكتب', ur: 'لکھیں' },
  { ca: 'llegeix', es: 'lee', ar: 'اقرأ', ur: 'پڑھیں' },
  { ca: 'explica', es: 'explica', ar: 'اشرح', ur: 'وضاحت کریں' },
  { ca: 'justifica', es: 'justifica', ar: 'برّر', ur: 'دلیل دیں' },
  { ca: 'compara', es: 'compara', ar: 'قارن', ur: 'موازنہ کریں' },
  { ca: 'ordena', es: 'ordena', ar: 'رتّب', ur: 'ترتیب دیں' },
  { ca: 'classifica', es: 'clasifica', ar: 'صنّف', ur: 'درجہ بندی کریں' },
  { ca: 'omple', es: 'rellena', ar: 'املأ', ur: 'بھریں' },
  { ca: 'descarrega', es: 'descarga', ar: 'حمّل', ur: 'ڈاؤن لوڈ کریں' },
  { ca: 'comprova', es: 'comprueba', ar: 'تحقق', ur: 'جانچیں' },
  { ca: 'tria', es: 'elige', ar: 'اختر', ur: 'منتخب کریں' },
  { ca: 'marca', es: 'marca', ar: 'علّم', ur: 'نشان لگائیں' },
  { ca: 'predicció', es: 'predicción', ar: 'توقع', ur: 'پیشگوئی' },
  { ca: 'prediccions', es: 'predicciones', ar: 'توقعات', ur: 'پیشگوئیاں' },
  { ca: 'hipòtesi', es: 'hipótesis', ar: 'فرضية', ur: 'مفروضہ' },
  { ca: 'hipòtesis', es: 'hipótesis', ar: 'فرضيات', ur: 'مفروضے' },
  { ca: 'resultats', es: 'resultados', ar: 'نتائج', ur: 'نتائج' },
  { ca: 'taula', es: 'tabla', ar: 'جدول', ur: 'جدول' },
  { ca: 'gràfica', es: 'gráfica', ar: 'رسم بياني', ur: 'گراف' },
  { ca: 'gràfiques', es: 'gráficas', ar: 'رسوم بيانية', ur: 'گراف' },
  { ca: 'fitxa', es: 'ficha', ar: 'ورقة العمل', ur: 'ورک شیٹ' },
  { ca: 'full', es: 'hoja', ar: 'ورقة', ur: 'کاغذ / شیٹ' },
  { ca: 'apartat', es: 'apartado', ar: 'قسم', ur: 'حصہ' },
  { ca: 'apartats', es: 'apartados', ar: 'أقسام', ur: 'حصے' },
  { ca: 'pista', es: 'pista', ar: 'تلميح', ur: 'اشارہ' },
  { ca: 'pistes', es: 'pistas', ar: 'تلميحات', ur: 'اشارے' },
  { ca: 'pregunta', es: 'pregunta', ar: 'سؤال', ur: 'سوال' },
  { ca: 'preguntes', es: 'preguntas', ar: 'أسئلة', ur: 'سوالات' },
  { ca: 'resposta', es: 'respuesta', ar: 'إجابة', ur: 'جواب' },
  { ca: 'respostes', es: 'respuestas', ar: 'إجابات', ur: 'جوابات' },
  { ca: 'deures', es: 'deberes', ar: 'واجبات', ur: 'ہوم ورک' },
  { ca: 'termini', es: 'plazo', ar: 'مهلة', ur: 'مدت' },
  { ca: 'entrega', es: 'entrega', ar: 'تسليم', ur: 'جمع کرانا' },
  { ca: 'entregues', es: 'entregas', ar: 'تسليمات', ur: 'جمع کرانے کی چیزیں' },
  { ca: 'sessió', es: 'sesión', ar: 'حصة', ur: 'سیشن' },
  { ca: 'sessions', es: 'sesiones', ar: 'حصص', ur: 'سیشنز' },
  // A 4t «prova» gairebé sempre vol dir EVIDÈNCIA, no examen (SA1-SA7).
  { ca: 'prova', es: 'prueba / evidencia', ar: 'دليل / برهان', ur: 'ثبوت / شہادت' },
  { ca: 'rúbrica', es: 'rúbrica', ar: 'سلم التقييم', ur: 'روبرک (جانچ پیمانہ)' },
  { ca: 'pòster', es: 'póster', ar: 'ملصق', ur: 'پوسٹر' },
  { ca: 'grup', es: 'grupo', ar: 'مجموعة', ur: 'گروپ' },
  { ca: 'materials', es: 'materiales', ar: 'أدوات', ur: 'سامان' },
  { ca: 'durada', es: 'duración', ar: 'مدة', ur: 'دورانیہ' },
  { ca: 'objectius', es: 'objetivos', ar: 'أهداف', ur: 'مقاصد' },
  { ca: 'competències', es: 'competencias', ar: 'كفاءات', ur: 'صلاحیتیں' },
  { ca: 'recuperació', es: 'recuperación', ar: 'استدراك / تعويض', ur: 'تلافی' },
  { ca: 'autoavaluació', es: 'autoevaluación', ar: 'تقييم ذاتي', ur: 'خود تشخیص' },
  { ca: 'reflexió', es: 'reflexión', ar: 'تأمل', ur: 'غور و فکر' },
  { ca: 'repte', es: 'reto', ar: 'تحدٍّ', ur: 'چیلنج' },
  { ca: 'enigma', es: 'enigma', ar: 'لغز', ur: 'پہیلی' },
  { ca: 'enigmes', es: 'enigmas', ar: 'ألغاز', ur: 'پہیلیاں' },
  { ca: 'maqueta', es: 'maqueta', ar: 'مجسّم', ur: 'ماڈل' },
  { ca: 'dies', es: 'días', ar: 'أيام', ur: 'دن' },
  { ca: 'setmanes', es: 'semanas', ar: 'أسابيع', ur: 'ہفتے' },
  { ca: 'queden', es: 'quedan / faltan', ar: 'تبقّى', ur: 'باقی ہیں' },

  // ══════════════════════════════════════════════════════════
  // VOCABULARI DE 4t ESO (afegit 2026-08-21)
  // El bloc de dalt venia del projecte de 3r ESO i no cobria
  // res de genètica, evolució, geologia ni origen de la vida.
  // ══════════════════════════════════════════════════════════
  // ── 4t ESO · SA1 · Ciència i pseudociència
  { ca: 'ciència', es: 'ciencia', ar: 'العِلم', ur: 'سائنس' },
  { ca: 'pseudociència', es: 'pseudociencia', ar: 'العِلم الزائف', ur: 'جعلی سائنس' },
  { ca: 'científic', es: 'científico', ar: 'عِلمي', ur: 'سائنسی' },
  { ca: 'científica', es: 'científica', ar: 'عِلمية', ur: 'سائنسی' },
  { ca: 'inferència', es: 'inferencia', ar: 'استنتاج', ur: 'اخذِ نتیجہ' },
  { ca: 'conclusió', es: 'conclusión (lo que deduces de los datos)', ar: 'استنتاج نهائي مبني على الأدلة', ur: 'شواہد سے اخذ کردہ نتیجہ' },
  { ca: 'argument', es: 'argumento', ar: 'حُجّة', ur: 'دلیل' },
  { ca: 'autoritat', es: 'autoridad', ar: 'السلطة (من يقولها)', ur: 'اتھارٹی (کہنے والا)' },
  // A SA1 «garantia» NO és la d'un producte: és allò en què recolzes una
  // afirmació (dades, models, hàbits, autoritat, identitat/valors).
  { ca: 'garantia', es: 'garantía: en qué apoyas lo que afirmas', ar: 'المُسوِّغ: الأساس الذي تبني عليه ادعاءك', ur: 'دلیل کی بنیاد: آپ بات کس چیز پر رکھتے ہیں' },
  { ca: 'hàbit', es: 'hábito / costumbre', ar: 'عادة: «هكذا كان دائمًا»', ur: 'عادت / روایت' },
  { ca: 'identitat', es: 'identidad', ar: 'الهوية: من أنا وبماذا أؤمن', ur: 'شناخت: میں کون ہوں' },
  { ca: 'valors', es: 'valores', ar: 'القيم', ur: 'اقدار' },
  { ca: 'biaix', es: 'sesgo', ar: 'تحيّز: ميل يجعلك ترى ما تريد', ur: 'تعصب / جھکاؤ' },
  { ca: 'cert', es: 'cierto / verdadero', ar: 'أكيد / صحيح', ur: 'یقینی / سچ' },
  { ca: 'certa', es: 'cierta / verdadera', ar: 'أكيدة / صحيحة', ur: 'یقینی / سچی' },
  { ca: 'segur', es: 'seguro', ar: 'متأكد', ur: 'پُریقین' },
  { ca: 'segura', es: 'segura', ar: 'متأكدة', ur: 'پُریقین' },
  { ca: 'afirmació', es: 'afirmación', ar: 'عبارة / ادعاء', ur: 'دعویٰ / بیان' },
  { ca: 'retalla', es: 'recorta', ar: 'قُصّ بالمقص', ur: 'کاٹیں' },
  { ca: 'retallables', es: 'recortables', ar: 'أوراق للقصّ', ur: 'کاٹنے والے کارڈ' },
  { ca: 'enganxa', es: 'pega', ar: 'الصق', ur: 'چپکائیں' },
  { ca: 'consens', es: 'consenso / acuerdo del grupo', ar: 'توافق المجموعة', ur: 'گروپ کا اتفاق' },
  { ca: 'mesures', es: 'medidas (acciones)', ar: 'إجراءات', ur: 'اقدامات' },
  { ca: 'marques', es: 'marcas comerciales', ar: 'علامات تجارية', ur: 'برانڈز' },
  { ca: 'plaça', es: 'plaza', ar: 'ساحة', ur: 'چوک' },
  { ca: 'verificar', es: 'verificar', ar: 'التحقّق', ur: 'تصدیق کرنا' },
  { ca: 'exageració', es: 'exageración', ar: 'مبالغة', ur: 'مبالغہ' },
  { ca: 'opinió', es: 'opinión', ar: 'رأي', ur: 'رائے' },
  { ca: 'criteri', es: 'criterio', ar: 'معيار', ur: 'معیار' },
  { ca: 'mètode', es: 'método', ar: 'منهج / طريقة', ur: 'طریقہ کار' },
  { ca: 'rigor', es: 'rigor', ar: 'دقّة صارمة', ur: 'سختی و احتیاط' },
  { ca: 'fiable', es: 'fiable', ar: 'موثوق', ur: 'قابلِ اعتماد' },
  { ca: 'certesa', es: 'certeza', ar: 'درجة اليقين', ur: 'یقین کا درجہ' },
  { ca: 'contrastable', es: 'contrastable', ar: 'قابل للاختبار', ur: 'قابلِ جانچ' },
  { ca: 'indagació', es: 'indagación', ar: 'الاستقصاء', ur: 'تحقیق و تفتیش' },
  { ca: 'bioètica', es: 'bioética', ar: 'أخلاقيات علم الأحياء', ur: 'حیاتیاتی اخلاقیات' },
  { ca: 'ètica', es: 'ética', ar: 'الأخلاق', ur: 'اخلاقیات' },
  { ca: 'coavaluació', es: 'coevaluación', ar: 'التقييم بين الأقران', ur: 'ہم جماعت تشخیص' },
  { ca: 'congrés', es: 'congreso', ar: 'مؤتمر', ur: 'کانفرنس' },
  { ca: 'tendència', es: 'tendencia', ar: 'اتجاه عام', ur: 'عمومی رجحان' },
  { ca: 'percentatge', es: 'porcentaje', ar: 'نسبة مئوية', ur: 'فیصد' },
  { ca: 'probable', es: 'probable (más que posible)', ar: 'مُرجَّح (أكثر من مجرد ممكن)', ur: 'غالب امکان / زیادہ امکان والا' },
  { ca: 'atzar', es: 'azar', ar: 'الصدفة (بلا سبب ولا قدَر)', ur: 'اتفاقیہ / بے ترتیبی (کوئی وجہ یا قسمت نہیں)' },
  { ca: 'moneda', es: 'moneda', ar: 'قطعة نقدية', ur: 'سکہ' },
  { ca: 'perfil epistèmic', es: 'tu perfil: cómo decides qué te crees', ar: 'طريقتك في تحديد ما تصدّقه', ur: 'آپ کیسے طے کرتے ہیں کہ کیا ماننا ہے' },
  { ca: 'hipòtesi contrastable', es: 'hipótesis contrastable', ar: 'فرضية قابلة للاختبار', ur: 'قابلِ جانچ مفروضہ' },
  { ca: 'qüestió sociocientífica', es: 'cuestión sociocientífica', ar: 'قضية علمية اجتماعية', ur: 'سماجی سائنسی مسئلہ' },
  { ca: 'pòster científic', es: 'póster científico', ar: 'ملصق علمي', ur: 'سائنسی پوسٹر' },
  { ca: 'control negatiu', es: 'control negativo', ar: 'الشاهد السالب', ur: 'منفی کنٹرول' },
  { ca: 'control positiu', es: 'control positivo', ar: 'الشاهد الموجب', ur: 'مثبت کنٹرول' },
  { ca: 'a cegues', es: 'a ciegas', ar: 'تجربة عمياء', ur: 'بلائنڈ ٹیسٹ' },
  // ── 4t ESO · SA2 · La cèl·lula
  { ca: 'interfase', es: 'interfase', ar: 'الطور البيني', ur: 'انٹرفیز' },
  { ca: 'profase', es: 'profase', ar: 'الطور التمهيدي', ur: 'پروفیز' },
  { ca: 'metafase', es: 'metafase', ar: 'الطور الاستوائي', ur: 'میٹا فیز' },
  { ca: 'anafase', es: 'anafase', ar: 'الطور الانفصالي', ur: 'اینا فیز' },
  { ca: 'telofase', es: 'telofase', ar: 'الطور النهائي', ur: 'ٹیلو فیز' },
  { ca: 'cicle cel·lular', es: 'ciclo celular', ar: 'دورة الخلية', ur: 'خلوی چکر' },
  { ca: 'índex mitòtic', es: 'índice mitótico', ar: 'المؤشر الانقسامي', ur: 'مائٹوٹک انڈیکس' },
  { ca: 'tumor', es: 'tumor', ar: 'ورم', ur: 'رسولی' },
  { ca: 'tumoral', es: 'tumoral', ar: 'ورمي', ur: 'رسولی سے متعلق' },
  { ca: 'quimioteràpia', es: 'quimioterapia', ar: 'العلاج الكيميائي', ur: 'کیمو تھراپی' },
  { ca: 'gàmeta', es: 'gameto', ar: 'خلية جنسية (مشيج)', ur: 'جنسی خلیہ' },
  { ca: 'zigot', es: 'cigoto', ar: 'اللاقحة', ur: 'زائیگوٹ' },
  { ca: 'fecundació', es: 'fecundación', ar: 'الإخصاب', ur: 'بارآوری' },
  { ca: 'somàtica', es: 'somática', ar: 'جسدية (خلية الجسم)', ur: 'جسمانی' },
  { ca: 'germinal', es: 'germinal', ar: 'تناسلية (خلية جنسية)', ur: 'تولیدی' },
  // ── 4t ESO · SA3 · El codi de la vida
  { ca: 'arn', es: 'ARN', ar: 'الرنا (RNA)', ur: 'آر این اے' },
  { ca: 'transcripció', es: 'transcripción', ar: 'النسخ', ur: 'نقل (ٹرانسکرپشن)' },
  { ca: 'traducció', es: 'traducción', ar: 'الترجمة', ur: 'ترجمہ (ٹرانسلیشن)' },
  { ca: 'codó', es: 'codón', ar: 'الكودون', ur: 'کوڈون' },
  { ca: 'anticodó', es: 'anticodón', ar: 'الكودون المضاد', ur: 'اینٹی کوڈون' },
  { ca: 'aminoàcid', es: 'aminoácido', ar: 'حمض أميني', ur: 'امینو ایسڈ' },
  { ca: 'proteïna', es: 'proteína', ar: 'بروتين', ur: 'پروٹین' },
  { ca: 'ribosoma', es: 'ribosoma', ar: 'الريبوسوم', ur: 'رائبوسوم' },
  { ca: 'complementarietat', es: 'complementariedad', ar: 'التكامل بين القواعد', ur: 'بیسوں کی تکمیلیت' },
  { ca: 'seqüència', es: 'secuencia', ar: 'تسلسل', ur: 'ترتیب' },
  { ca: 'mutació', es: 'mutación', ar: 'طفرة', ur: 'جینیاتی تبدیلی' },
  { ca: 'embrió', es: 'embrión', ar: 'جنين', ur: 'جنین' },
  { ca: 'soluble', es: 'soluble', ar: 'قابل للذوبان', ur: 'حل پذیر' },
  { ca: 'precipita', es: 'precipita', ar: 'يترسّب', ur: 'جم کر الگ ہوتا ہے' },
  { ca: 'triturar', es: 'triturar', ar: 'يُهرَس', ur: 'پیسنا' },
  { ca: 'doble hèlix', es: 'doble hélice', ar: 'اللولب المزدوج', ur: 'ڈبل ہیلکس' },
  { ca: 'doble cadena', es: 'doble cadena', ar: 'سلسلة مزدوجة', ur: 'دوہری لڑی' },
  { ca: 'arn missatger', es: 'ARN mensajero', ar: 'الرنا الرسول', ur: 'میسنجر آر این اے' },
  { ca: 'tisores moleculars', es: 'tijeras moleculares', ar: 'مقص جزيئي', ur: 'مالیکیولر قینچی' },
  { ca: 'anèmia falciforme', es: 'anemia falciforme', ar: 'فقر الدم المنجلي', ur: 'سکل سیل انیمیا' },
  { ca: 'mutació silenciosa', es: 'mutación silenciosa', ar: 'طفرة صامتة', ur: 'خاموش تبدیلی' },
  // ── 4t ESO · SA4 · Herència
  { ca: 'gen', es: 'gen', ar: 'الجين', ur: 'جین' },
  { ca: 'al·lel', es: 'alelo', ar: 'الأليل', ur: 'ایلیل' },
  { ca: 'genotip', es: 'genotipo', ar: 'النمط الجيني', ur: 'جینوٹائپ' },
  { ca: 'fenotip', es: 'fenotipo', ar: 'النمط الظاهري', ur: 'فینوٹائپ' },
  { ca: 'homozigot', es: 'homocigoto', ar: 'متماثل اللواقح', ur: 'ہومو زائگس' },
  { ca: 'heterozigot', es: 'heterocigoto', ar: 'متغاير اللواقح', ur: 'ہیٹرو زائگس' },
  { ca: 'dominant', es: 'dominante', ar: 'سائد', ur: 'غالب' },
  { ca: 'recessiu', es: 'recesivo', ar: 'متنحٍّ', ur: 'مغلوب' },
  { ca: 'portador', es: 'portador', ar: 'حامل للجين', ur: 'جین کا حامل' },
  { ca: 'portadora', es: 'portadora', ar: 'حاملة للجين', ur: 'جین کی حامل' },
  { ca: 'hemizigot', es: 'hemicigoto: solo tiene una copia del gen', ar: 'يملك نسخة واحدة فقط من الجين (الذكر وكروموسوم X)', ur: 'جین کی صرف ایک نقل رکھنے والا' },
  { ca: 'pedigrí', es: 'árbol genealógico', ar: 'شجرة العائلة', ur: 'خاندانی شجرہ' },
  { ca: 'codominància', es: 'codominancia', ar: 'السيادة المشتركة', ur: 'مشترکہ غلبہ' },
  { ca: 'poligènia', es: 'poligenia', ar: 'تعدد الجينات', ur: 'کثیر جینی وراثت' },
  { ca: 'multifactorial', es: 'multifactorial', ar: 'متعدد العوامل', ur: 'کئی عوامل والا' },
  { ca: 'hemofília', es: 'hemofilia', ar: 'الناعور (الهيموفيليا)', ur: 'ہیموفیلیا' },
  { ca: 'daltonisme', es: 'daltonismo', ar: 'عمى الألوان', ur: 'رنگ اندھا پن' },
  { ca: 'quadre de punnett', es: 'cuadro de Punnett', ar: 'مربع بانيت', ur: 'پنیٹ اسکوائر' },
  { ca: 'consell genètic', es: 'consejo genético', ar: 'الاستشارة الوراثية', ur: 'جینیاتی مشاورت' },
  { ca: 'dominància incompleta', es: 'dominancia incompleta', ar: 'السيادة الناقصة', ur: 'نامکمل غلبہ' },
  { ca: 'al·lelisme múltiple', es: 'alelismo múltiple', ar: 'تعدد الأليلات', ur: 'متعدد ایلیل' },
  { ca: 'grups sanguinis', es: 'grupos sanguíneos', ar: 'فصائل الدم', ur: 'خون کے گروپ' },
  { ca: 'cromosomes sexuals', es: 'cromosomas sexuales', ar: 'الصبغيات الجنسية', ur: 'جنسی کروموسوم' },
  { ca: 'variació contínua', es: 'variación continua', ar: 'تغاير متصل', ur: 'مسلسل تغیر' },
  // ── 4t ESO · SA5 · Evolució
  { ca: 'evolució', es: 'evolución', ar: 'التطوّر', ur: 'ارتقا' },
  { ca: 'adaptació', es: 'adaptación', ar: 'تكيّف', ur: 'موافقت' },
  { ca: 'variabilitat', es: 'variabilidad', ar: 'التباين', ur: 'تنوع' },
  { ca: 'biodiversitat', es: 'biodiversidad', ar: 'التنوع البيولوجي', ur: 'حیاتیاتی تنوع' },
  { ca: 'fixisme', es: 'fijismo', ar: 'ثبات الأنواع', ur: 'ثباتِ انواع' },
  { ca: 'lamarckisme', es: 'lamarckismo', ar: 'اللاماركية', ur: 'لامارک ازم' },
  { ca: 'darwinisme', es: 'darwinismo', ar: 'الداروينية', ur: 'ڈارون ازم' },
  { ca: 'neodarwinisme', es: 'neodarwinismo', ar: 'الداروينية الحديثة', ur: 'نو ڈارون ازم' },
  { ca: 'homologia', es: 'homología', ar: 'التماثل البنيوي', ur: 'ہم ساختی' },
  { ca: 'analogia', es: 'analogía', ar: 'التشابه الوظيفي', ur: 'ہم عملی' },
  { ca: 'espècie', es: 'especie', ar: 'نوع', ur: 'نوع' },
  { ca: 'gènere', es: 'género', ar: 'جنس (تصنيف)', ur: 'جنس (درجہ بندی)' },
  { ca: 'domesticació', es: 'domesticación', ar: 'التدجين', ur: 'پالتو بنانا' },
  { ca: 'húmer', es: 'húmero', ar: 'عظم العضد', ur: 'عضد کی ہڈی' },
  { ca: 'cúbit', es: 'cúbito', ar: 'عظم الزند', ur: 'النا' },
  { ca: 'pelvis', es: 'pelvis', ar: 'الحوض', ur: 'شرونی' },
  { ca: 'còccix', es: 'cóccix', ar: 'العصعص', ur: 'دُم چہ' },
  { ca: 'apèndix', es: 'apéndice', ar: 'الزائدة الدودية', ur: 'اپینڈکس' },
  { ca: 'selecció natural', es: 'selección natural', ar: 'الانتقاء الطبيعي', ur: 'قدرتی انتخاب' },
  { ca: 'selecció artificial', es: 'selección artificial', ar: 'الانتقاء الاصطناعي', ur: 'مصنوعی انتخاب' },
  { ca: 'estructura vestigial', es: 'estructura vestigial', ar: 'بنية أثرية', ur: 'باقیاتی ساخت' },
  { ca: 'nomenclatura binomial', es: 'nomenclatura binomial', ar: 'التسمية الثنائية', ur: 'دو نامی نظام' },
  { ca: 'arbre de semblances', es: 'árbol de semejanzas', ar: 'شجرة التشابهات', ur: 'مشابہت کا شجرہ' },
  // ── 4t ESO · SA6 · Geologia i riscos
  { ca: 'litosfera', es: 'litosfera', ar: 'الغلاف الصخري', ur: 'لیتھوسفیئر' },
  { ca: 'mantell', es: 'manto', ar: 'الوشاح', ur: 'مینٹل' },
  { ca: 'placa', es: 'placa', ar: 'صفيحة', ur: 'پلیٹ' },
  { ca: 'convecció', es: 'convección: lo caliente sube y lo frío baja', ar: 'الحمل الحراري: الساخن يصعد والبارد ينزل', ur: 'گرم مادّے کا اوپر اور ٹھنڈے کا نیچے بہاؤ (کنویکشن)' },
  { ca: 'subducció', es: 'subducción', ar: 'الاندساس', ur: 'سبڈکشن' },
  { ca: 'dorsal', es: 'dorsal oceánica', ar: 'الحيد المحيطي', ur: 'سمندری قلاچ' },
  { ca: 'fossa', es: 'fosa oceánica', ar: 'خندق محيطي', ur: 'سمندری خندق' },
  { ca: 'orogen', es: 'orógeno', ar: 'سلسلة جبلية ناشئة', ur: 'کوہ زائی' },
  { ca: 'divergent', es: 'divergente: se separan', ar: 'متباعد: يبتعدان عن بعضهما', ur: 'ایک دوسرے سے دور ہٹتی ہوئی (ڈائیورجنٹ)' },
  { ca: 'convergent', es: 'convergente: chocan', ar: 'متقارب: يصطدمان', ur: 'ایک دوسرے کی طرف بڑھتی ہوئی (کنورجنٹ)' },
  { ca: 'transformant', es: 'transformante', ar: 'تحويلي', ur: 'ٹرانسفارم' },
  { ca: 'falla', es: 'falla', ar: 'صدع', ur: 'فالٹ (شگاف)' },
  { ca: 'estrat', es: 'estrato', ar: 'طبقة صخرية', ur: 'چٹانی تہہ' },
  { ca: 'superposició', es: 'superposición', ar: 'التراكب', ur: 'تہہ بندی' },
  { ca: 'horitzontalitat', es: 'horizontalidad', ar: 'الأفقية', ur: 'افقیت' },
  { ca: 'intersecció', es: 'intersección', ar: 'التقاطع', ur: 'قطع کرنا' },
  { ca: 'discordança', es: 'discordancia', ar: 'عدم التوافق', ur: 'ناہمواری' },
  { ca: 'erosió', es: 'erosión', ar: 'التعرية', ur: 'کٹاؤ' },
  { ca: 'actualisme', es: 'actualismo', ar: 'مبدأ الحاضر مفتاح الماضي', ur: 'یکسانیت کا اصول' },
  { ca: 'neocatastrofisme', es: 'neocatastrofismo', ar: 'الكارثية الجديدة', ur: 'نو تباہیت' },
  { ca: 'paleozoic', es: 'paleozoico', ar: 'الحقب القديم', ur: 'قدیم حیاتی دور' },
  { ca: 'mesozoic', es: 'mesozoico', ar: 'الحقب الوسيط', ur: 'وسطی حیاتی دور' },
  { ca: 'cenozoic', es: 'cenozoico', ar: 'الحقب الحديث', ur: 'جدید حیاتی دور' },
  { ca: 'calcària', es: 'caliza', ar: 'الحجر الجيري', ur: 'چونا پتھر' },
  { ca: 'gres', es: 'arenisca', ar: 'الحجر الرملي', ur: 'ریتیلا پتھر' },
  { ca: 'cendra', es: 'ceniza', ar: 'رماد', ur: 'راکھ' },
  { ca: 'terratrèmol', es: 'terremoto', ar: 'زلزال', ur: 'زلزلہ' },
  { ca: 'vulcanisme', es: 'vulcanismo', ar: 'النشاط البركاني', ur: 'آتش فشانیت' },
  { ca: 'risc', es: 'riesgo', ar: 'الخطر', ur: 'خطرہ' },
  { ca: 'perillositat', es: 'peligrosidad', ar: 'درجة الخطورة', ur: 'خطرناکی' },
  { ca: 'exposició', es: 'exposición oral · exposición al riesgo (SA6)', ar: 'عرض شفوي · التعرّض للخطر', ur: 'زبانی پیشکش · خطرے کے سامنے ہونا' },
  { ca: 'vulnerabilitat', es: 'vulnerabilidad', ar: 'الهشاشة', ur: 'کمزوری' },
  { ca: 'esllavissada', es: 'deslizamiento de tierra', ar: 'انزلاق أرضي', ur: 'لینڈ سلائیڈ' },
  { ca: 'inundació', es: 'inundación', ar: 'فيضان', ur: 'سیلاب' },
  { ca: 'embassament', es: 'embalse', ar: 'خزان مائي', ur: 'ذخیرۂ آب' },
  { ca: 'sediment', es: 'sedimento', ar: 'رواسب', ur: 'تلچھٹ' },
  { ca: 'delta', es: 'delta', ar: 'دلتا النهر', ur: 'دریائی ڈیلٹا' },
  { ca: 'litologia', es: 'litología', ar: 'نوع الصخر', ur: 'چٹان کی قسم' },
  { ca: 'relleu', es: 'relieve', ar: 'التضاريس', ur: 'ارضی خدوخال' },
  { ca: 'vegetació', es: 'vegetación', ar: 'الغطاء النباتي', ur: 'نباتاتی احاطہ' },
  { ca: 'reforestar', es: 'reforestar', ar: 'إعادة التشجير', ur: 'دوبارہ شجرکاری' },
  { ca: 'simulacre', es: 'simulacro', ar: 'تدريب على الإخلاء', ur: 'مشقی مشق' },
  { ca: 'sismoresistent', es: 'sismorresistente', ar: 'مقاوم للزلازل', ur: 'زلزلہ مزاحم' },
  { ca: 'cicle de wilson', es: 'ciclo de Wilson', ar: 'دورة ويلسون', ur: 'ولسن سائیکل' },
  { ca: 'fòssils guia', es: 'fósiles guía', ar: 'الأحافير الدالة', ur: 'ہدایتی فوسل' },
  { ca: 'deriva continental', es: 'deriva continental', ar: 'زحف القارات', ur: 'براعظمی بہاؤ' },
  { ca: 'datació relativa', es: 'datación relativa', ar: 'التأريخ النسبي', ur: 'اضافی تاریخ سازی' },
  { ca: 'datació absoluta', es: 'datación absoluta', ar: 'التأريخ المطلق', ur: 'مطلق تاریخ سازی' },
  // ── 4t ESO · SA7 · L'origen de tot
  { ca: 'big bang', es: 'Big Bang', ar: 'الانفجار العظيم', ur: 'بگ بینگ' },
  { ca: 'semivida', es: 'vida media: tiempo en que se desintegra la mitad', ar: 'عمر النصف: الزمن الذي يتحلل فيه نصف المادة', ur: 'نصف زندگی: جس میں آدھا مادہ ٹوٹ جاتا ہے' },
  { ca: 'radioactivitat', es: 'radiactividad', ar: 'النشاط الإشعاعي', ur: 'تابکاری' },
  { ca: 'datació', es: 'datación', ar: 'التأريخ (تحديد العمر)', ur: 'تاریخ سازی' },
  { ca: 'meteorit', es: 'meteorito', ar: 'نيزك', ur: 'شہابیہ' },
  { ca: 'exoplaneta', es: 'exoplaneta', ar: 'كوكب خارج المجموعة الشمسية', ur: 'خارجی سیارہ' },
  { ca: 'panspèrmia', es: 'panspermia: la vida vino del espacio', ar: 'البذر الكوني: الحياة جاءت من الفضاء', ur: 'پین اسپرمیا: زندگی خلا سے آئی' },
  { ca: 'astrobiologia', es: 'astrobiología', ar: 'علم الأحياء الفلكي', ur: 'فلکی حیاتیات' },
  { ca: 'especulació', es: 'especulación', ar: 'تكهّن', ur: 'قیاس آرائی' },
  { ca: 'estromatòlits', es: 'estromatolitos: rocas hechas por bacterias antiguas', ar: 'صخور بنَتْها بكتيريا قديمة', ur: 'قدیم بیکٹیریا کی بنائی ہوئی چٹانیں' },
  { ca: 'fumaroles hidrotermals', es: 'fumarolas hidrotermales', ar: 'فوهات مائية حرارية', ur: 'گرم آبی سوراخ' },
  { ca: 'món arn', es: 'mundo ARN', ar: 'عالم الرنا', ur: 'آر این اے کی دنیا' },
  // ── 4t ESO · Vocabulari transversal (surt a totes les SA)
  { ca: 'fòssil', es: 'fósil', ar: 'أحفورة', ur: 'رکاز (فوسل)' },
  { ca: 'dada', es: 'dato', ar: 'مُعطى / بيانات', ur: 'ڈیٹا' },
  { ca: 'model', es: 'modelo', ar: 'نموذج', ur: 'ماڈل' },
  { ca: 'teoria', es: 'teoría', ar: 'نظرية', ur: 'نظریہ' },
  { ca: 'cromosoma', es: 'cromosoma', ar: 'صبغي (كروموسوم)', ur: 'کروموسوم' },
  { ca: 'herència', es: 'herencia', ar: 'الوراثة', ur: 'وراثت' },
  { ca: 'variable', es: 'variable', ar: 'متغيّر', ur: 'متغیر' },
  { ca: 'experiment', es: 'experimento', ar: 'تجربة', ur: 'تجربہ' },
  { ca: 'resultat', es: 'resultado', ar: 'نتيجة', ur: 'نتیجہ' },
  { ca: 'observar', es: 'observar', ar: 'يُلاحِظ', ur: 'مشاہدہ کرنا' },
  { ca: 'inferir', es: 'inferir', ar: 'يستنتج', ur: 'نتیجہ اخذ کرنا' },
  { ca: 'ambient', es: 'ambiente / entorno', ar: 'البيئة', ur: 'ماحول' },
  { ca: 'límit', es: 'límite', ar: 'حدّ', ur: 'حد' },
  { ca: 'temps', es: 'tiempo (cronológico) · el tiempo (meteorología)', ar: 'الزمن · حالة الطقس', ur: 'وقت · موسم' },
  { ca: 'nivell', es: 'nivel', ar: 'مستوى', ur: 'سطح' },
  { ca: 'divisió', es: 'división', ar: 'انقسام', ur: 'تقسیم' },
  { ca: 'reproducció', es: 'reproducción', ar: 'التكاثر', ur: 'تولید' },
  { ca: 'diagnòstic', es: 'diagnóstico', ar: 'تشخيص', ur: 'تشخیص' },
  { ca: 'mostra', es: 'muestra', ar: 'عيّنة', ur: 'نمونہ' },
  { ca: 'gràfic', es: 'gráfico', ar: 'رسم بياني', ur: 'گراف' },
  { ca: 'calor', es: 'calor', ar: 'الحرارة', ur: 'حرارت' },
  { ca: 'ordre', es: 'orden', ar: 'ترتيب', ur: 'ترتیب' },
  { ca: 'mecanisme', es: 'mecanismo', ar: 'آليّة', ur: 'طریقۂ کار' },
  { ca: 'gravetat', es: 'gravedad', ar: 'الجاذبية', ur: 'کششِ ثقل' },
  { ca: 'sorra', es: 'arena', ar: 'رمل', ur: 'ریت' },
  { ca: 'barreja', es: 'mezcla', ar: 'خليط', ur: 'آمیزہ / ملاوٹ' },
  { ca: 'prevenció', es: 'prevención', ar: 'الوقاية', ur: 'روک تھام' },
  { ca: 'correcció', es: 'corrección', ar: 'التصحيح / المعالجة', ur: 'درستی' },
  { ca: 'rellotge', es: 'reloj', ar: 'ساعة', ur: 'گھڑی' },
  { ca: 'postura', es: 'postura', ar: 'موقف', ur: 'مؤقف' },
  { ca: 'benefici', es: 'beneficio', ar: 'فائدة', ur: 'فائدہ' },
  { ca: 'versió', es: 'versión', ar: 'نسخة', ur: 'نسخہ' },
  { ca: 'quadrat', es: 'cuadrado', ar: 'مربّع', ur: 'مربع' },
  { ca: 'cercle', es: 'círculo', ar: 'دائرة', ur: 'دائرہ' },
  { ca: 'alçada', es: 'altura', ar: 'الطول (القامة)', ur: 'قد' },
  { ca: 'nerviós', es: 'nervioso', ar: 'عصبي', ur: 'اعصابی' },
  { ca: 'tòxic', es: 'tóxico', ar: 'سام', ur: 'زہریلا' },
  { ca: 'intern', es: 'interno', ar: 'داخلي', ur: 'اندرونی' },
  { ca: 'extern', es: 'externo', ar: 'خارجي', ur: 'بیرونی' },
  { ca: 'induït', es: 'inducido', ar: 'مُستحَث (بفعل الإنسان)', ur: 'انسانی سبب سے پیدا شدہ' },
  { ca: 'marí', es: 'marino', ar: 'بحري', ur: 'سمندری' },
  { ca: 'relativa', es: 'relativa', ar: 'نسبية', ur: 'اضافی' },
  { ca: 'absoluta', es: 'absoluta', ar: 'مطلقة', ur: 'مطلق' },
  { ca: 'sabó', es: 'jabón', ar: 'صابون', ur: 'صابن' },
  { ca: 'alcohol', es: 'alcohol', ar: 'كحول', ur: 'الکحل' },
  { ca: 'ésser viu', es: 'ser vivo', ar: 'كائن حيّ', ur: 'جاندار' }
]

// Índex: frases multi-paraula primer (més llargues primer), després paraules soltes
const normalize = (s) => s.toLowerCase()

export const PHRASES = GLOSSARY.filter((e) => e.ca.includes(' '))
  .sort((a, b) => b.ca.split(' ').length - a.ca.split(' ').length)
  .map((e) => ({ ...e, words: normalize(e.ca).split(' ') }))

export const WORDS = new Map(
  GLOSSARY.filter((e) => !e.ca.includes(' ')).map((e) => [normalize(e.ca), e])
)

export const MAX_PHRASE_LEN = PHRASES.length
  ? Math.max(...PHRASES.map((p) => p.words.length))
  : 1
